; NOTE: I do not advise hand editing this, use aae gamename -debug and use the debug controls to resize, even if they are weird and need remapped.
; To resize with a certain setting, cropped, bezel, nocrop, etc. Set it first, exit, then run with -debug to set and save.



[astdelux]
full_left=0
full_right=1024
full_bottom=-200
full_top=1050
bezel_left=200
bezel_right=832
bezel_bottom=191
bezel_top=954
crop_left=209
crop_right=875
crop_bottom=229
crop_top=1038
bezcropzoom=1.23
bezcropx=-118
bezcropy=-70
overalpha=1.0

[astdelux1]
full_left=0
full_right=1024
full_bottom=0
full_top=965
bezel_left=126
bezel_right=909
bezel_bottom=248
bezel_top=855
crop_left=91
crop_right=940
crop_bottom=204
crop_top=865
bezcropzoom=1.23
bezcropx=-96
bezcropy=-70
overalpha=1.0

[astdelux2]
full_left=0
full_right=1024
full_bottom=0
full_top=965
bezel_left=126
bezel_right=909
bezel_bottom=248
bezel_top=855
crop_left=91
crop_right=940
crop_bottom=204
crop_top=865
bezcropzoom=1.23
bezcropx=-96
bezcropy=-70
overalpha=1.0


[astdelbz]
full_left=0
full_right=1024
full_bottom=-200
full_top=1050
bezel_left=200
bezel_right=832
bezel_bottom=191
bezel_top=954
crop_left=209
crop_right=875
crop_bottom=229
crop_top=1038
bezcropzoom=1.23
bezcropx=-118
bezcropy=-70
overalpha=1.0

[astdelbz11b]
full_left=0
full_right=1024
full_bottom=-200
full_top=1050
bezel_left=200
bezel_right=832
bezel_bottom=191
bezel_top=954
crop_left=209
crop_right=875
crop_bottom=229
crop_top=1038
bezcropzoom=1.23
bezcropx=-118
bezcropy=-70
overalpha=1.0

[astbz11b]
full_left=0
full_right=1024
full_bottom=-200
full_top=1050
bezel_left=200
bezel_right=832
bezel_bottom=191
bezel_top=954
crop_left=209
crop_right=875
crop_bottom=229
crop_top=1038
bezcropzoom=1.23
bezcropx=-118
bezcropy=-70
overalpha=1.0




[asterock]
full_left=0
full_right=1024
full_bottom=0
full_top=965
bezel_left=178
bezel_right=853
bezel_bottom=90
bezel_top=775
crop_left=99
crop_right=940
crop_bottom=43
crop_top=902
bezcropzoom=1.25
bezcropx=-100
bezcropy=-50
overalpha=.96

[asteroid]
full_left=0
full_right=1024
full_bottom=-225
full_top=1067
bezel_left=203
bezel_right=836
bezel_bottom=-19
bezel_top=817
crop_left=132
crop_right=956
crop_bottom=-85
crop_top=985
bezcropzoom=1.25
bezcropx=-100
bezcropy=-50
overalpha=.96

[asteroid1]
full_left=0
full_right=1024
full_bottom=-225
full_top=1067
bezel_left=203
bezel_right=836
bezel_bottom=-19
bezel_top=817
crop_left=132
crop_right=956
crop_bottom=-85
crop_top=985
bezcropzoom=1.25
bezcropx=-100
bezcropy=-50
overalpha=.96

[asteroidb]
full_left=0
full_right=1024
full_bottom=0
full_top=965
bezel_left=178
bezel_right=853
bezel_bottom=90
bezel_top=775
crop_left=99
crop_right=940
crop_bottom=43
crop_top=902
bezcropzoom=1.25
bezcropx=-100
bezcropy=-50
overalpha=.96

[meteorts]
full_left=0
full_right=1024
full_bottom=0
full_top=965
bezel_left=
bezel_right=
bezel_bottom=
bezel_top=
crop_left=
crop_right=
crop_bottom=
crop_top=
bezcropzoom=
bezcropx=
bezcropy=
overalpha=


[omegrace]
full_left=0
full_right=1023
full_bottom=0
full_top=1023
bezel_left=169
bezel_right=868
bezel_bottom=183
bezel_top=835
crop_left=96
crop_right=943
crop_bottom=205
crop_top=953
bezcropzoom=1.25
bezcropx=-100
bezcropy=-50
overalpha=.96

[omegrace60]
full_left=0
full_right=1023
full_bottom=0
full_top=1023
bezel_left=169
bezel_right=868
bezel_bottom=183
bezel_top=835
crop_left=96
crop_right=943
crop_bottom=205
crop_top=953
bezcropzoom=1.25
bezcropx=-100
bezcropy=-50
overalpha=.96


[gui]
full_left=0
full_right=1024
full_bottom=1083
full_top=6
bezel_left=0
bezel_right=1024
bezel_bottom=1024
bezel_top=0
crop_left=0
crop_right=1024
crop_bottom=1024
crop_top=0
bezcropzoom=
bezcropx=
bezcropy=
overalpha=
