; NOTE: I do not advise hand editing this, use aae gamename -debug and use the debug controls to resize, even if they are weird and need remapped.
; To resize with a certain setting, cropped, bezel, nocrop, etc. Set it first, exit, then run with -debug to set and save.


[armora]
; To stretch to full screen:
full_left=0
full_right=1024
full_bottom=1033
full_top=-11
bezel_left=209
bezel_right=842
bezel_bottom=695
bezel_top=130
crop_left=135
crop_right=964
crop_bottom=883
crop_top=141
bezcropzoom=1.3
bezcropx=-130
bezcropy=-30
overalpha=.96


[astdelux]
full_left=0
full_right=1024
full_bottom=-200
full_top=1050
bezel_left=200
bezel_right=832
bezel_bottom=191
bezel_top=954
crop_left=209
crop_right=875
crop_bottom=229
crop_top=1038
bezcropzoom=1.23
bezcropx=-118
bezcropy=-70
overalpha=1.0

[astdelux1]
full_left=0
full_right=1024
full_bottom=0
full_top=965
bezel_left=126
bezel_right=909
bezel_bottom=248
bezel_top=855
crop_left=91
crop_right=940
crop_bottom=204
crop_top=865
bezcropzoom=1.23
bezcropx=-96
bezcropy=-70
overalpha=1.0

[astdelux2]
full_left=0
full_right=1024
full_bottom=0
full_top=965
bezel_left=126
bezel_right=909
bezel_bottom=248
bezel_top=855
crop_left=91
crop_right=940
crop_bottom=204
crop_top=865
bezcropzoom=1.23
bezcropx=-96
bezcropy=-70
overalpha=1.0

[asterock]
full_left=0
full_right=1024
full_bottom=0
full_top=965
bezel_left=178
bezel_right=853
bezel_bottom=90
bezel_top=775
crop_left=99
crop_right=940
crop_bottom=43
crop_top=902
bezcropzoom=1.25
bezcropx=-100
bezcropy=-50
overalpha=.96

[asteroid]
full_left=0
full_right=1024
full_bottom=-225
full_top=1067
bezel_left=203
bezel_right=836
bezel_bottom=-19
bezel_top=817
crop_left=132
crop_right=956
crop_bottom=-85
crop_top=985
bezcropzoom=1.25
bezcropx=-100
bezcropy=-50
overalpha=.96

[asteroid1]
full_left=0
full_right=1024
full_bottom=0
full_top=965
bezel_left=178
bezel_right=853
bezel_bottom=90
bezel_top=775
crop_left=99
crop_right=940
crop_bottom=43
crop_top=902
bezcropzoom=1.25
bezcropx=-100
bezcropy=-50
overalpha=.96

[asteroidb]
full_left=0
full_right=1024
full_bottom=0
full_top=965
bezel_left=178
bezel_right=853
bezel_bottom=90
bezel_top=775
crop_left=99
crop_right=940
crop_bottom=43
crop_top=902
bezcropzoom=1.25
bezcropx=-100
bezcropy=-50
overalpha=.96

[barrier]
full_left=1056
full_right=-47
full_bottom=-40
full_top=993
bezel_left=794
bezel_right=224
bezel_bottom=72
bezel_top=683
crop_left=843
crop_right=188
crop_bottom=49
crop_top=771
bezcropzoom=1.2
bezcropx=-95
bezcropy=-30
overalpha=.96

[boxingb]
full_left=0
full_right=1023
full_bottom=1023
full_top=0
bezel_left=
bezel_right=
bezel_bottom=
bezel_top=
crop_left=
crop_right=
crop_bottom=
crop_top=
bezcropzoom=1.3
bezcropx=-130
bezcropy=-30
overalpha=.96


[bradley]
full_left=7
full_right=1020
full_bottom=-121
full_top=890
bezel_left=199
bezel_right=821
bezel_bottom=89
bezel_top=800
crop_left=117
crop_right=910
crop_bottom=39
crop_top=945
bezcropzoom=1.30
bezcropx=-115
bezcropy=-65
overalpha=1.0


[bzone]
full_left=0
full_right=1023
full_bottom=0
full_top=1023
bezel_left=199
bezel_right=821
bezel_bottom=37
bezel_top=695
crop_left=134
crop_right=961
crop_bottom=83
crop_top=1009
bezcropzoom=1.30
bezcropx=-115
bezcropy=-65
overalpha=1.0

[bzone2]
full_left=0
full_right=1023
full_bottom=0
full_top=1023
bezel_left=199
bezel_right=821
bezel_bottom=37
bezel_top=695
crop_left=134
crop_right=961
crop_bottom=-61
crop_top=857
bezcropzoom=1.30
bezcropx=-115
bezcropy=-65
overalpha=1.0

[bzonea]
full_left=0
full_right=1023
full_bottom=0
full_top=1023
bezel_left=199
bezel_right=821
bezel_bottom=37
bezel_top=695
crop_left=134
crop_right=961
crop_bottom=-61
crop_top=857
bezcropzoom=1.30
bezcropx=-115
bezcropy=-65
overalpha=1.0


[bzonec]
full_left=0
full_right=1023
full_bottom=0
full_top=1023
bezel_left=199
bezel_right=821
bezel_bottom=37
bezel_top=695
crop_left=134
crop_right=961
crop_bottom=-61
crop_top=857
bezcropzoom=1.30
bezcropx=-115
bezcropy=-65
overalpha=1.0

[bzonep]
full_left=0
full_right=1023
full_bottom=0
full_top=1023
bezel_left=199
bezel_right=821
bezel_bottom=37
bezel_top=695
crop_left=134
crop_right=961
crop_bottom=-61
crop_top=857
bezcropzoom=1.30
bezcropx=-115
bezcropy=-65
overalpha=1.0

[deltrace]
full_left=0
full_right=1023
full_bottom=0
full_top=1023
bezel_left=124
bezel_right=925
bezel_bottom=90
bezel_top=859
crop_left=99
crop_right=943
crop_bottom=44
crop_top=884
bezcropzoom=1.25
bezcropx=-100
bezcropy=-50
overalpha=.96

[demon]
full_left=0
full_right=1023
full_bottom=1023
full_top=0
bezel_left=
bezel_right=
bezel_bottom=
bezel_top=
crop_left=
crop_right=
crop_bottom=
crop_top=
bezcropzoom=1.3
bezcropx=-130
bezcropy=-30
overalpha=.96


[elim2]
full_left=0
full_right=1024
full_bottom=1024
full_top=0
bezel_left=168
bezel_right=843
bezel_bottom=806
bezel_top=203
crop_left=112
crop_right=913
crop_bottom=892
crop_top=152
bezcropzoom=1.22
bezcropx=-110
bezcropy=-90
overalpha=1.0


[elim2a]
full_left=0
full_right=1023
full_bottom=1023
full_top=0

bezel_left=0
bezel_right=1024
bezel_bottom=1024
bezel_top=0
crop_left=129
crop_right=879
crop_bottom=709
crop_top=28
bezcropzoom=1.22
bezcropx=-110
bezcropy=-90
overalpha=1.0

[elim2c]
full_left=0
full_right=1023
full_bottom=1023
full_top=0

bezel_left=0
bezel_right=1024
bezel_bottom=1024
bezel_top=0
crop_left=129
crop_right=879
crop_bottom=709
crop_top=28
bezcropzoom=1.22
bezcropx=-110
bezcropy=-90
overalpha=1.0


[elim2p]
full_left=0
full_right=1023
full_bottom=1023
full_top=0

bezel_left=0
bezel_right=1024
bezel_bottom=1024
bezel_top=0
crop_left=129
crop_right=879
crop_bottom=709
crop_top=28
bezcropzoom=1.22
bezcropx=-110
bezcropy=-90
overalpha=1.0

[elim4]
full_left=0
full_right=1023
full_bottom=1023
full_top=0

bezel_left=
bezel_right=
bezel_bottom=
bezel_top=
crop_left=
crop_right=
crop_bottom=
crop_top=
bezcropzoom=
bezcropx=
bezcropy=
overalpha=

[elim4p]
full_left=0
full_right=1023
full_bottom=1023
full_top=0
bezel_left=
bezel_right=
bezel_bottom=
bezel_top=
crop_left=
crop_right=
crop_bottom=
crop_top=
bezcropzoom=
bezcropx=
bezcropy=
overalpha=


[gui]
full_left=0
full_right=1024
full_bottom=1083
full_top=6
bezel_left=0
bezel_right=1024
bezel_bottom=1024
bezel_top=0
crop_left=0
crop_right=1024
crop_bottom=1024
crop_top=0
bezcropzoom=
bezcropx=
bezcropy=
overalpha=


[llander]
full_left=0
full_right=1024
full_bottom=-143
full_top=1166
bezel_left=185
bezel_right=846
bezel_bottom=90
bezel_top=736
crop_left=99
crop_right=943
crop_bottom=29
crop_top=884
bezcropzoom=1.25
bezcropx=-100
bezcropy=-50
overalpha=.96


[llander1]
full_left=0
full_right=1024
full_bottom=-143
full_top=1166
bezel_left=185
bezel_right=846
bezel_bottom=90
bezel_top=736
crop_left=99
crop_right=943
crop_bottom=29
crop_top=884
bezcropzoom=1.25
bezcropx=-100
bezcropy=-50
overalpha=.96

[main]
force_vsync=1
priority=2
kbleds=1
windowed=0
screenw=1024
screenh=768
gamma=127
bright=127
contrast=127
drawzero=0
widescreen=0


[meteorts]
full_left=0
full_right=1024
full_bottom=0
full_top=965
bezel_left=
bezel_right=
bezel_bottom=
bezel_top=
crop_left=
crop_right=
crop_bottom=
crop_top=
bezcropzoom=
bezcropx=
bezcropy=
overalpha=

[omegrace]
full_left=0
full_right=1023
full_bottom=0
full_top=1023
bezel_left=169
bezel_right=868
bezel_bottom=183
bezel_top=835
crop_left=96
crop_right=943
crop_bottom=205
crop_top=953
bezcropzoom=1.25
bezcropx=-100
bezcropy=-50
overalpha=.96

[qb3]
full_left=7
full_right=1056
full_bottom=1001
full_top=17
bezel_left=205
bezel_right=853
bezel_bottom=96
bezel_top=672
crop_left=97
crop_right=944
crop_bottom=87
crop_top=846
bezcropzoom=1.3
bezcropx=-130
bezcropy=-30
overalpha=.96

[redbaron]
full_left=0
full_right=1023
full_bottom=0
full_top=1023

bezel_left=182
bezel_right=840
bezel_bottom=181
bezel_top=865

crop_left=87
crop_right=934
crop_bottom=149
crop_top=1005
bezcropzoom=1.30
bezcropx=-155
bezcropy=-100
overalpha=1.0

[solarq]
full_left=1023
full_right=0
full_bottom=1023
full_top=0
bezel_left=783
bezel_right=232
bezel_bottom=796
bezel_top=258
crop_left=875
crop_right=139
crop_bottom=852
crop_top=125
bezcropzoom=1.25
bezcropx=-130
bezcropy=-150
overalpha=.96

[spacewar]
full_left=0
full_right=1023
full_bottom=1023
full_top=0
bezel_left=
bezel_right=
bezel_bottom=
bezel_top=
crop_left=
crop_right=
crop_bottom=
crop_top=
bezcropzoom=1.3
bezcropx=-130
bezcropy=-30
overalpha=.96

[spacfura]
full_left=0
full_right=1024
full_bottom=0
full_top=1024
bezel_left=188
bezel_right=839
bezel_bottom=220
bezel_top=787
crop_left=152
crop_right=888
crop_bottom=152
crop_top=822
bezcropzoom=1.20
bezcropx=-95
bezcropy=-110
overalpha=


[spacfurb]
full_left=0
full_right=1024
full_bottom=0
full_top=1024
bezel_left=188
bezel_right=839
bezel_bottom=220
bezel_top=787
crop_left=152
crop_right=888
crop_bottom=152
crop_top=822
bezcropzoom=1.20
bezcropx=-95
bezcropy=-110
overalpha=

[spacfury]
full_left=0
full_right=1024
full_bottom=0
full_top=1024
bezel_left=188
bezel_right=839
bezel_bottom=220
bezel_top=787
crop_left=152
crop_right=888
crop_bottom=152
crop_top=822
bezcropzoom=1.20
bezcropx=-95
bezcropy=-110
overalpha=


[starcas]
full_left=11
full_right=1016
full_bottom=976
full_top=7
bezel_left=151
bezel_right=866
bezel_bottom=746
bezel_top=52
crop_left=117
crop_right=972
crop_bottom=874
crop_top=25
bezcropzoom=1.3
bezcropx=-130
bezcropy=-30
overalpha=.96


[startrek]
full_left=0
full_right=1024
full_bottom=0
full_top=1024
bezel_left=133
bezel_right=889
bezel_bottom=92
bezel_top=904
crop_left=53
crop_right=968
crop_bottom=21
crop_top=946
bezcropzoom=1.21
bezcropx=-107
bezcropy=-130
overalpha=1.0


[sundance]
full_left=1024
full_right=0
full_bottom=1024
full_top=0
bezel_left=205
bezel_right=853
bezel_bottom=96
bezel_top=672
crop_left=97
crop_right=944
crop_bottom=87
crop_top=846
bezcropzoom=1.3
bezcropx=-130
bezcropy=-30
overalpha=.96

[tacscan]
full_left=1024
full_right=0
full_bottom=1024
full_top=0
bezel_left=777
bezel_right=250
bezel_bottom=863
bezel_top=148
crop_left=821
crop_right=209
crop_bottom=971
crop_top=90
bezcropzoom=1.22
bezcropx=-110
bezcropy=-90
overalpha=1.0

[warrior]
full_left=106
full_right=923
full_bottom=925
full_top=53
bezel_left=
bezel_right=
bezel_bottom=
bezel_top=
crop_left=
crop_right=
crop_bottom=
crop_top=
bezcropzoom=1.3
bezcropx=-130
bezcropy=-30
overalpha=.96

[wotw]
full_left=0
full_right=1024
full_bottom=1024
full_top=0
bezel_left=172
bezel_right=858
bezel_bottom=746
bezel_top=147
crop_left=111
crop_right=924
crop_bottom=867
crop_top=108
bezcropzoom=1.30
bezcropx=-152
bezcropy=-100
overalpha=1.0

[wotwc]
full_left=0
full_right=1024
full_bottom=1024
full_top=0
bezel_left=172
bezel_right=858
bezel_bottom=746
bezel_top=147
crop_left=111
crop_right=924
crop_bottom=867
crop_top=108
bezcropzoom=1.30
bezcropx=-152
bezcropy=-100
overalpha=1.0


[zektor]
full_left=0
full_right=1024
full_bottom=1024
full_top=0
bezel_left=186
bezel_right=837
bezel_bottom=791
bezel_top=211
crop_left=159
crop_right=923
crop_bottom=909
crop_top=164
bezcropzoom=1.29
bezcropx=-151
bezcropy=-110
overalpha=1.0

