//= ========================================================================== =
// AAE is a poorly written M.A.M.E (TM) derivitave based on early MAME 
// code, 0.29 through .90 mixed with code of my own. This emulator was 
// created solely for my amusement and learning and is provided only 
// as an archival experience. 
// 
// All MAME code used and abused in this emulator remains the copyright 
// of the dedicated people who spend countless hours creating it. All
// MAME code should be annotated as belonging to the MAME TEAM.
// 
// SOME CODE BELOW IS FROM MAME and COPYRIGHT the MAME TEAM.  
//============================================================================

#pragma once

#ifndef _GAMEKEYS_H
#define _GAMEKEYS_H

#include "aae_mame_driver.h"
#include "inptport.h"


//Input Port Definitions Start Here

INPUT_PORTS_START(gui)
PORT_START("IN0") /* IN0 */
PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_BUTTON1 | IPF_SPULSE) //Start Game
PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_EXIT | IPF_SPULSE) //Exit
PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_BUTTON2 | IPF_SPULSE) //Menu
PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_BUTTON3 | IPF_SPULSE)
PORT_BIT(0x10, IP_ACTIVE_HIGH, IPT_BUTTON4 | IPF_SPULSE)
PORT_BIT(0x20, IP_ACTIVE_HIGH, IPT_BUTTON5 | IPF_SPULSE)
PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_BUTTON6 | IPF_SPULSE)
PORT_BIT(0x80, IP_ACTIVE_HIGH, IPT_UNUSED)
//Note: Mask can be zero

PORT_START("IN1") //IN1
PORT_BITX(0x01, IP_ACTIVE_HIGH, IPT_JOYSTICK_UP | IPF_4WAY | IPF_COUNTER, "UP", OSD_KEY_UP, OSD_JOY_UP)
PORT_BITX(0x02, IP_ACTIVE_HIGH, IPT_JOYSTICK_DOWN | IPF_4WAY | IPF_COUNTER, "DOWN", OSD_KEY_DOWN, OSD_JOY_DOWN)
PORT_BITX(0x04, IP_ACTIVE_HIGH, IPT_JOYSTICK_LEFT | IPF_4WAY | IPF_SPULSE, "RIGHT", OSD_KEY_LEFT, OSD_JOY_LEFT)
PORT_BITX(0x08, IP_ACTIVE_HIGH, IPT_JOYSTICK_RIGHT | IPF_4WAY | IPF_SPULSE, "LEFT", OSD_KEY_RIGHT, OSD_JOY_RIGHT)
PORT_BIT(0x10, IP_ACTIVE_HIGH, IPT_UNUSED)
PORT_BIT(0x20, IP_ACTIVE_HIGH, IPT_UNUSED)
PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_UNUSED)
PORT_BIT(0x80, IP_ACTIVE_HIGH, IPT_UNUSED)

PORT_START("IN2")	/* IN2 */
PORT_ANALOG(0xff, 0x80, IPT_PADDLE | IPF_PLAYER1 | IPF_REVERSE, 25, 10, 32, 0x00, 0xff)
//PORT_ANALOG(mask,def,type,sensitivity,delta,clip,min,max)
//PORT_ANALOGX( 0xff, 0x00, IPT_TRACKBALL_X, 50, 10, 0, 0, 0, IP_KEY_NONE, IP_KEY_NONE, IP_JOY_NONE, IP_JOY_NONE )

//PORT_START	/* IN3 */
//PORT_ANALOGX( 0xff, 0x00, IPT_TRACKBALL_Y, 50, 10, 0, 0, 0, IP_KEY_NONE, IP_KEY_NONE, IP_JOY_NONE, IP_JOY_NONE )
INPUT_PORTS_END

// Asteroid

INPUT_PORTS_START(asteroid)
PORT_START("IN0") /* IN0 */
PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_UNKNOWN)
/* Bit 2 and 3 are handled in the machine dependent part. */
/* Bit 2 is the 3 KHz source and Bit 3 the VG_HALT bit    */
PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_UNKNOWN)
PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_UNKNOWN)
PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_BUTTON3)
PORT_BIT(0x10, IP_ACTIVE_HIGH, IPT_BUTTON1)
PORT_BITX(0x20, IP_ACTIVE_HIGH, IPT_SERVICE, "Diagnostic Step", OSD_KEY_F1, IP_JOY_NONE)
PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_TILT)
PORT_SERVICE(0x80, IP_ACTIVE_HIGH)

PORT_START("IN1") /* IN1 */
PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_COIN1)
PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_COIN2)
PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_COIN3)
PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_START1)
PORT_BIT(0x10, IP_ACTIVE_HIGH, IPT_START2)
PORT_BIT(0x20, IP_ACTIVE_HIGH, IPT_BUTTON2)
PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_JOYSTICK_RIGHT | IPF_2WAY)
PORT_BIT(0x80, IP_ACTIVE_HIGH, IPT_JOYSTICK_LEFT | IPF_2WAY)

PORT_START("DSW1") /* DSW 1 */
PORT_DIPNAME(0x03, 0x00, "Language")
PORT_DIPSETTING(0x00, "English")
PORT_DIPSETTING(0x01, "German")
PORT_DIPSETTING(0x02, "French")
PORT_DIPSETTING(0x03, "Spanish")
PORT_DIPNAME(0x04, 0x04, DEF_STR(Lives))
PORT_DIPSETTING(0x04, "3")
PORT_DIPSETTING(0x00, "4")
PORT_DIPNAME(0x08, 0x00, DEF_STR(Unknown))
PORT_DIPSETTING(0x00, DEF_STR(Off))
PORT_DIPSETTING(0x08, DEF_STR(On))
PORT_DIPNAME(0x10, 0x00, DEF_STR(Unknown))
PORT_DIPSETTING(0x00, DEF_STR(Off))
PORT_DIPSETTING(0x10, DEF_STR(On))
PORT_DIPNAME(0x20, 0x00, DEF_STR(Unknown))
PORT_DIPSETTING(0x00, DEF_STR(Off))
PORT_DIPSETTING(0x20, DEF_STR(On))
PORT_DIPNAME(0xc0, 0x80, DEF_STR(Coinage))
PORT_DIPSETTING(0xc0, DEF_STR(2C_1C))
PORT_DIPSETTING(0x80, DEF_STR(1C_1C))
PORT_DIPSETTING(0x40, DEF_STR(1C_2C))
PORT_DIPSETTING(0x00, DEF_STR(Free_Play))
INPUT_PORTS_END

INPUT_PORTS_START(astdelux)
// PORT_START_TAG("IN0")
PORT_START("IN0") /* IN0 */
PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_UNKNOWN)
/* Bit 2 and 3 are handled in the machine dependent part. */
/* Bit 2 is the 3 KHz source and Bit 3 the VG_HALT bit    */
PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_UNKNOWN)
PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_UNKNOWN)
PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_BUTTON3)
PORT_BIT(0x10, IP_ACTIVE_HIGH, IPT_BUTTON1)
PORT_BITX(0x20, IP_ACTIVE_HIGH, IPT_SERVICE, "Diagnostic Step", OSD_KEY_F1, IP_JOY_NONE)
PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_TILT)
PORT_SERVICE(0x80, IP_ACTIVE_HIGH)

PORT_START("IN1") /* IN1 */
PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_COIN1)
PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_COIN2)
PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_COIN3)
PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_START1)
PORT_BIT(0x10, IP_ACTIVE_HIGH, IPT_START2)
PORT_BIT(0x20, IP_ACTIVE_HIGH, IPT_BUTTON2)
PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_JOYSTICK_RIGHT | IPF_2WAY)
PORT_BIT(0x80, IP_ACTIVE_HIGH, IPT_JOYSTICK_LEFT | IPF_2WAY)

PORT_START("DSW1") /* DSW 1 */
PORT_DIPNAME(0x03, 0x00, "Language")
PORT_DIPSETTING(0x00, "English")
PORT_DIPSETTING(0x01, "German")
PORT_DIPSETTING(0x02, "French")
PORT_DIPSETTING(0x03, "Spanish")
PORT_DIPNAME(0x0c, 0x04, DEF_STR(Lives))
PORT_DIPSETTING(0x00, "2-4")
PORT_DIPSETTING(0x04, "3-5")
PORT_DIPSETTING(0x08, "4-6")
PORT_DIPSETTING(0x0c, "5-7")
PORT_DIPNAME(0x10, 0x00, "Minimum plays")
PORT_DIPSETTING(0x00, "1")
PORT_DIPSETTING(0x10, "2")
PORT_DIPNAME(0x20, 0x00, DEF_STR(Difficulty))
PORT_DIPSETTING(0x00, "Hard")
PORT_DIPSETTING(0x20, "Easy")
PORT_DIPNAME(0xc0, 0x00, DEF_STR(Bonus_Life))
PORT_DIPSETTING(0x00, "10000")
PORT_DIPSETTING(0x40, "12000")
PORT_DIPSETTING(0x80, "15000")
PORT_DIPSETTING(0xc0, "None")

PORT_START("DSW2") /* DSW 2 */
PORT_DIPNAME(0x03, 0x01, DEF_STR(Coinage))
PORT_DIPSETTING(0x00, DEF_STR(2C_1C))
PORT_DIPSETTING(0x01, DEF_STR(1C_1C))
PORT_DIPSETTING(0x02, DEF_STR(1C_2C))
PORT_DIPSETTING(0x03, DEF_STR(Free_Play))
PORT_DIPNAME(0x0c, 0x0c, "Right Coin")
PORT_DIPSETTING(0x00, "*6")
PORT_DIPSETTING(0x04, "*5")
PORT_DIPSETTING(0x08, "*4")
PORT_DIPSETTING(0x0c, "*1")
PORT_DIPNAME(0x10, 0x10, "Center Coin")
PORT_DIPSETTING(0x00, "*2")
PORT_DIPSETTING(0x10, "*1")
PORT_DIPNAME(0xe0, 0x80, "Bonus Coins")
PORT_DIPSETTING(0x60, "1 each 5")
PORT_DIPSETTING(0x80, "2 each 4")
PORT_DIPSETTING(0xa0, "1 each 4")
PORT_DIPSETTING(0xc0, "1 each 2")
PORT_DIPSETTING(0xe0, "None")
INPUT_PORTS_END

//Lunar Lander

INPUT_PORTS_START(llander)
PORT_START("IN0") /* IN0 */
/* Bit 0 is VG_HALT, handled in the machine dependant part */
PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_UNKNOWN)
PORT_BITX(0x02, 0x02, IPT_DIPSWITCH_NAME | IPF_TOGGLE, DEF_STR(Service_Mode), OSD_KEY_F2, IP_JOY_NONE)
PORT_DIPSETTING(0x02, DEF_STR(Off))
PORT_DIPSETTING(0x00, DEF_STR(On))
PORT_BIT(0x04, IP_ACTIVE_LOW, IPT_TILT)
/* Of the rest, Bit 6 is the 3KHz source. 3,4 and 5 are unknown */
PORT_BIT(0x78, IP_ACTIVE_LOW, IPT_UNKNOWN)
PORT_BITX(0x80, IP_ACTIVE_LOW, IPT_SERVICE, "Diagnostic Step", OSD_KEY_F1, IP_JOY_NONE)

PORT_START("IN1") /* IN1 */
PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_START1)
PORT_BIT(0x02, IP_ACTIVE_LOW, IPT_COIN1)
PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_COIN2)
PORT_BIT(0x08, IP_ACTIVE_LOW, IPT_COIN3)
PORT_BITX(0x10, IP_ACTIVE_HIGH, IPT_START2, "Select Game", IP_KEY_DEFAULT, IP_JOY_DEFAULT)
PORT_BITX(0x20, IP_ACTIVE_HIGH, IPT_BUTTON1, "Abort", IP_KEY_DEFAULT, IP_JOY_DEFAULT)
PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_JOYSTICK_RIGHT | IPF_2WAY)
PORT_BIT(0x80, IP_ACTIVE_HIGH, IPT_JOYSTICK_LEFT | IPF_2WAY)

PORT_START("DSW1") /* DSW1 */
PORT_DIPNAME(0x03, 0x01, "Right Coin")
PORT_DIPSETTING(0x00, "*1")
PORT_DIPSETTING(0x01, "*4")
PORT_DIPSETTING(0x02, "*5")
PORT_DIPSETTING(0x03, "*6")
PORT_DIPNAME(0x0c, 0x00, "Language")
PORT_DIPSETTING(0x00, "English")
PORT_DIPSETTING(0x04, "French")
PORT_DIPSETTING(0x08, "Spanish")
PORT_DIPSETTING(0x0c, "German")
PORT_DIPNAME(0x20, 0x00, DEF_STR(Coinage))
PORT_DIPSETTING(0x00, "Normal")
PORT_DIPSETTING(0x20, DEF_STR(Free_Play))
PORT_DIPNAME(0xd0, 0x80, "Fuel units")
PORT_DIPSETTING(0x00, "450")
PORT_DIPSETTING(0x40, "600")
PORT_DIPSETTING(0x80, "750")
PORT_DIPSETTING(0xc0, "900")
PORT_DIPSETTING(0x10, "1100")
PORT_DIPSETTING(0x50, "1300")
PORT_DIPSETTING(0x90, "1550")
PORT_DIPSETTING(0xd0, "1800")

/* The next one is a potentiometer */
PORT_START("IN3")/* IN3 */
PORT_ANALOGX(0xff, 0x00, IPT_PADDLE | IPF_REVERSE, 100, 10, 0, 0, 255, OSD_KEY_UP, OSD_KEY_DOWN, OSD_JOY_UP, OSD_JOY_DOWN)
INPUT_PORTS_END

INPUT_PORTS_START(llander1)
PORT_START("IN0") /* IN0 */
/* Bit 0 is VG_HALT, handled in the machine dependant part */
PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_UNKNOWN)
PORT_BITX(0x02, 0x02, IPT_DIPSWITCH_NAME | IPF_TOGGLE, DEF_STR(Service_Mode), OSD_KEY_F2, IP_JOY_NONE)
PORT_DIPSETTING(0x02, DEF_STR(Off))
PORT_DIPSETTING(0x00, DEF_STR(On))
PORT_BIT(0x04, IP_ACTIVE_LOW, IPT_TILT)
/* Of the rest, Bit 6 is the 3KHz source. 3,4 and 5 are unknown */
PORT_BIT(0x78, IP_ACTIVE_LOW, IPT_UNKNOWN)
PORT_BITX(0x80, IP_ACTIVE_LOW, IPT_SERVICE, "Diagnostic Step", OSD_KEY_F1, IP_JOY_NONE)

PORT_START("IN1") /* IN1 */
PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_START1)
PORT_BIT(0x02, IP_ACTIVE_LOW, IPT_COIN1)
PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_COIN2)
PORT_BIT(0x08, IP_ACTIVE_LOW, IPT_COIN3)
PORT_BITX(0x10, IP_ACTIVE_HIGH, IPT_START2, "Select Game", IP_KEY_DEFAULT, IP_JOY_DEFAULT)
PORT_BITX(0x20, IP_ACTIVE_HIGH, IPT_BUTTON1, "Abort", IP_KEY_DEFAULT, IP_JOY_DEFAULT)
PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_JOYSTICK_RIGHT | IPF_2WAY)
PORT_BIT(0x80, IP_ACTIVE_HIGH, IPT_JOYSTICK_LEFT | IPF_2WAY)

PORT_START("DSW1") /* DSW1 */
PORT_DIPNAME(0x03, 0x01, "Right Coin")
PORT_DIPSETTING(0x00, "*1")
PORT_DIPSETTING(0x01, "*4")
PORT_DIPSETTING(0x02, "*5")
PORT_DIPSETTING(0x03, "*6")
PORT_DIPNAME(0x0c, 0x00, "Language")
PORT_DIPSETTING(0x00, "English")
PORT_DIPSETTING(0x04, "French")
PORT_DIPSETTING(0x08, "Spanish")
PORT_DIPSETTING(0x0c, "German")
PORT_DIPNAME(0x10, 0x00, DEF_STR(Coinage))
PORT_DIPSETTING(0x00, "Normal")
PORT_DIPSETTING(0x10, DEF_STR(Free_Play))
PORT_DIPNAME(0xc0, 0x80, "Fuel units")
PORT_DIPSETTING(0x00, "450")
PORT_DIPSETTING(0x40, "600")
PORT_DIPSETTING(0x80, "750")
PORT_DIPSETTING(0xc0, "900")

/* The next one is a potentiometer */
PORT_START("IN3") /* IN3 */
PORT_ANALOGX(0xff, 0x00, IPT_PADDLE | IPF_REVERSE, 100, 10, 0, 0, 255, OSD_KEY_UP, OSD_KEY_DOWN, OSD_JOY_UP, OSD_JOY_DOWN)
INPUT_PORTS_END

INPUT_PORTS_START(omegrace)
PORT_START("SW0") /* SW0 */
PORT_DIPNAME(0x03, 0x03, "1st Bonus Life")
PORT_DIPSETTING(0x00, "40k")
PORT_DIPSETTING(0x01, "50k")
PORT_DIPSETTING(0x02, "70k")
PORT_DIPSETTING(0x03, "100k")
PORT_DIPNAME(0x0c, 0x0c, "2nd & 3rd Bonus Life")
PORT_DIPSETTING(0x00, "150k 250k")
PORT_DIPSETTING(0x04, "250k 500k")
PORT_DIPSETTING(0x08, "500k 750k")
PORT_DIPSETTING(0x0c, "750k 1500k")
PORT_DIPNAME(0x30, 0x30, "Credit(s)/Ships")
PORT_DIPSETTING(0x00, "1C/2S 2C/4S")
PORT_DIPSETTING(0x10, "1C/2S 2C/5S")
PORT_DIPSETTING(0x20, "1C/3S 2C/6S")
PORT_DIPSETTING(0x30, "1C/3S 2C/7S")
PORT_DIPNAME(0x40, 0x40, DEF_STR(Unused))
PORT_DIPSETTING(0x00, DEF_STR(Off))
PORT_DIPSETTING(0x40, DEF_STR(On))
PORT_DIPNAME(0x80, 0x40, DEF_STR(Unused))
PORT_DIPSETTING(0x00, DEF_STR(Off))
PORT_DIPSETTING(0x80, DEF_STR(On))

PORT_START("SW1") /* SW1 */
PORT_DIPNAME(0x07, 0x07, DEF_STR(Coin_A))
PORT_DIPSETTING(0x06, DEF_STR(2C_1C))
PORT_DIPSETTING(0x07, DEF_STR(1C_1C))
PORT_DIPSETTING(0x03, "4 Coins/5 Credits")
PORT_DIPSETTING(0x04, DEF_STR(3C_4C))
PORT_DIPSETTING(0x05, DEF_STR(2C_3C))
PORT_DIPSETTING(0x00, DEF_STR(1C_2C))
PORT_DIPSETTING(0x01, DEF_STR(1C_3C))
PORT_DIPSETTING(0x02, DEF_STR(1C_5C))
PORT_DIPNAME(0x38, 0x38, DEF_STR(Coin_B))
PORT_DIPSETTING(0x30, DEF_STR(2C_1C))
PORT_DIPSETTING(0x38, DEF_STR(1C_1C))
PORT_DIPSETTING(0x18, "4 Coins/5 Credits")
PORT_DIPSETTING(0x20, DEF_STR(3C_4C))
PORT_DIPSETTING(0x28, DEF_STR(2C_3C))
PORT_DIPSETTING(0x00, DEF_STR(1C_2C))
PORT_DIPSETTING(0x08, DEF_STR(1C_3C))
PORT_DIPSETTING(0x10, DEF_STR(1C_5C))
PORT_DIPNAME(0x40, 0x00, DEF_STR(Free_Play))
PORT_DIPSETTING(0x00, DEF_STR(Off))
PORT_DIPSETTING(0x40, DEF_STR(On))
PORT_DIPNAME(0x80, 0x00, DEF_STR(Cabinet))
PORT_DIPSETTING(0x00, DEF_STR(Upright))
PORT_DIPSETTING(0x80, DEF_STR(Cocktail))

PORT_START("IN2") /* IN2 -port 0x11 */
PORT_BIT(0x01, IP_ACTIVE_LOW, IPT_COIN1)
PORT_BIT(0x02, IP_ACTIVE_LOW, IPT_COIN2)
PORT_BIT(0x04, IP_ACTIVE_LOW, IPT_UNKNOWN)
PORT_BIT(0x08, IP_ACTIVE_LOW, IPT_UNKNOWN)
PORT_BIT(0x10, IP_ACTIVE_LOW, IPT_TILT)
PORT_BIT(0x20, IP_ACTIVE_LOW, IPT_BUTTON2)
PORT_BIT(0x40, IP_ACTIVE_LOW, IPT_BUTTON1)
PORT_BITX(0x80, 0x80, IPT_DIPSWITCH_NAME | IPF_TOGGLE, DEF_STR(Service_Mode), OSD_KEY_F2, IP_JOY_NONE)
PORT_DIPSETTING(0x80, DEF_STR(Off))
PORT_DIPSETTING(0x00, DEF_STR(On))

PORT_START("IN3") /* IN3 - port 0x12 */
PORT_BIT(0x01, IP_ACTIVE_LOW, IPT_BUTTON2 | IPF_COCKTAIL)
PORT_BIT(0x02, IP_ACTIVE_LOW, IPT_BUTTON1 | IPF_COCKTAIL)
PORT_BIT(0x04, IP_ACTIVE_LOW, IPT_START3 | IPF_COCKTAIL)
PORT_BIT(0x08, IP_ACTIVE_LOW, IPT_START4 | IPF_COCKTAIL)
PORT_BIT(0x10, IP_ACTIVE_LOW, IPT_UNKNOWN)
PORT_BIT(0x20, IP_ACTIVE_LOW, IPT_UNKNOWN)
PORT_BIT(0x40, IP_ACTIVE_LOW, IPT_START1)
PORT_BIT(0x80, IP_ACTIVE_LOW, IPT_START2)

PORT_START("IN4") /* IN4 - port 0x15 - spinner */
PORT_ANALOG(0x3f, 0x00, IPT_DIAL, 12, 10, 0, 0, 0)

PORT_START("IN5") /* IN5 - port 0x16 - second spinner */
PORT_ANALOG(0x3f, 0x00, IPT_DIAL | IPF_COCKTAIL, 12, 10, 0, 0, 0)
INPUT_PORTS_END

INPUT_PORTS_START(bzone)
PORT_START("IN0")	/* IN0 */
PORT_BIT(0x01, IP_ACTIVE_LOW, IPT_COIN1)
PORT_BIT(0x02, IP_ACTIVE_LOW, IPT_COIN2)
PORT_BIT(0x0c, IP_ACTIVE_LOW, IPT_UNUSED)
PORT_BITX(0x10, 0x10, IPT_DIPSWITCH_NAME | IPF_TOGGLE, DEF_STR(Service_Mode), OSD_KEY_F2, IP_JOY_NONE)
PORT_DIPSETTING(0x10, DEF_STR(Off))
PORT_DIPSETTING(0x00, DEF_STR(On))
PORT_BITX(0x20, IP_ACTIVE_LOW, IPT_SERVICE, "Diagnostic Step", OSD_KEY_F1, IP_JOY_NONE)
/* bit 6 is the VG HALT bit. We set it to "low" */
/* per default (busy vector processor). */
/* handled by bzone_IN0_r() */
PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_UNKNOWN)
/* bit 7 is tied to a 3khz clock */
/* handled by bzone_IN0_r() */
PORT_BIT(0x80, IP_ACTIVE_HIGH, IPT_UNKNOWN)

PORT_START("DSW0")	/* DSW0 */
PORT_DIPNAME(0x03, 0x01, DEF_STR(Lives))
PORT_DIPSETTING(0x00, "2")
PORT_DIPSETTING(0x01, "3")
PORT_DIPSETTING(0x02, "4")
PORT_DIPSETTING(0x03, "5")
PORT_DIPNAME(0x0c, 0x04, "Missile appears at")
PORT_DIPSETTING(0x00, "5000")
PORT_DIPSETTING(0x04, "10000")
PORT_DIPSETTING(0x08, "20000")
PORT_DIPSETTING(0x0c, "30000")
PORT_DIPNAME(0x30, 0x10, DEF_STR(Bonus_Life))
PORT_DIPSETTING(0x10, "15k and 100k")
PORT_DIPSETTING(0x20, "20k and 100k")
PORT_DIPSETTING(0x30, "50k and 100k")
PORT_DIPSETTING(0x00, "None")
PORT_DIPNAME(0xc0, 0x00, "Language")
PORT_DIPSETTING(0x00, "English")
PORT_DIPSETTING(0x40, "German")
PORT_DIPSETTING(0x80, "French")
PORT_DIPSETTING(0xc0, "Spanish")

PORT_START("DSW1")	/* DSW1 */
PORT_DIPNAME(0x03, 0x02, DEF_STR(Coinage))
PORT_DIPSETTING(0x03, DEF_STR(2C_1C))
PORT_DIPSETTING(0x02, DEF_STR(1C_1C))
PORT_DIPSETTING(0x01, DEF_STR(1C_2C))
PORT_DIPSETTING(0x00, DEF_STR(Free_Play))
PORT_DIPNAME(0x0c, 0x00, DEF_STR(Coin_B))
PORT_DIPSETTING(0x00, "*1")
PORT_DIPSETTING(0x04, "*4")
PORT_DIPSETTING(0x08, "*5")
PORT_DIPSETTING(0x0c, "*6")
PORT_DIPNAME(0x10, 0x00, DEF_STR(Coin_A))
PORT_DIPSETTING(0x00, "*1")
PORT_DIPSETTING(0x10, "*2")
PORT_DIPNAME(0xe0, 0x00, "Bonus Coins")
PORT_DIPSETTING(0x00, "None")
PORT_DIPSETTING(0x20, "3 credits/2 coins")
PORT_DIPSETTING(0x40, "5 credits/4 coins")
PORT_DIPSETTING(0x60, "6 credits/4 coins")
PORT_DIPSETTING(0x80, "6 credits/5 coins")

PORT_START("IN3")	/* IN3 */
PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_JOYSTICKRIGHT_DOWN | IPF_2WAY)
PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_JOYSTICKRIGHT_UP | IPF_2WAY)
PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_JOYSTICKLEFT_DOWN | IPF_2WAY)
PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_JOYSTICKLEFT_UP | IPF_2WAY)
PORT_BIT(0x10, IP_ACTIVE_HIGH, IPT_BUTTON3)
PORT_BIT(0x20, IP_ACTIVE_HIGH, IPT_START1)
PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_START2)
PORT_BIT(0x80, IP_ACTIVE_HIGH, IPT_UNUSED)

PORT_START("IN4")	/* fake port for single joystick control */
/* This fake port is handled via bzone_IN3_r */
PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_JOYSTICK_UP | IPF_8WAY | IPF_CHEAT)
PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_JOYSTICK_DOWN | IPF_8WAY | IPF_CHEAT)
PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_JOYSTICK_LEFT | IPF_8WAY | IPF_CHEAT)
PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_JOYSTICK_RIGHT | IPF_8WAY | IPF_CHEAT)
PORT_BIT(0x10, IP_ACTIVE_HIGH, IPT_BUTTON1 | IPF_CHEAT)
INPUT_PORTS_END

INPUT_PORTS_START(redbaron)
PORT_START("IN0")	/* IN0 */
PORT_BIT(0x01, IP_ACTIVE_LOW, IPT_COIN1)
PORT_BIT(0x02, IP_ACTIVE_LOW, IPT_COIN2)
PORT_BIT(0x0c, IP_ACTIVE_LOW, IPT_UNUSED)
PORT_BITX(0x10, 0x10, IPT_DIPSWITCH_NAME | IPF_TOGGLE, DEF_STR(Service_Mode), OSD_KEY_F2, IP_JOY_NONE)
PORT_DIPSETTING(0x10, DEF_STR(Off))
PORT_DIPSETTING(0x00, DEF_STR(On))
PORT_BITX(0x20, IP_ACTIVE_LOW, IPT_SERVICE, "Diagnostic Step", OSD_KEY_F1, IP_JOY_NONE)
/* bit 6 is the VG HALT bit. We set it to "low" */
/* per default (busy vector processor). */
/* handled by bzone_IN0_r() */
PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_UNKNOWN)
/* bit 7 is tied to a 3khz clock */
/* handled by bzone_IN0_r() */
PORT_BIT(0x80, IP_ACTIVE_HIGH, IPT_UNKNOWN)

PORT_START("DSW0")	/* DSW0 */
/* See the table above if you are really interested */
PORT_DIPNAME(0xff, 0xfd, DEF_STR(Coinage))
PORT_DIPSETTING(0xfd, "Normal")

PORT_START("DSW1")	/* DSW1 */
PORT_DIPNAME(0x03, 0x03, "Language")
PORT_DIPSETTING(0x00, "German")
PORT_DIPSETTING(0x01, "French")
PORT_DIPSETTING(0x02, "Spanish")
PORT_DIPSETTING(0x03, "English")
PORT_DIPNAME(0x0c, 0x04, DEF_STR(Bonus_Life))
PORT_DIPSETTING(0x0c, "2k 10k 30k")
PORT_DIPSETTING(0x08, "4k 15k 40k")
PORT_DIPSETTING(0x04, "6k 20k 50k")
PORT_DIPSETTING(0x00, "None")
PORT_DIPNAME(0x30, 0x20, DEF_STR(Lives))
PORT_DIPSETTING(0x30, "2")
PORT_DIPSETTING(0x20, "3")
PORT_DIPSETTING(0x10, "4")
PORT_DIPSETTING(0x00, "5")
PORT_DIPNAME(0x40, 0x40, "One Play Minimum")
PORT_DIPSETTING(0x40, DEF_STR(Off))
PORT_DIPSETTING(0x00, DEF_STR(On))
PORT_DIPNAME(0x80, 0x80, "Self Adjust Diff")
PORT_DIPSETTING(0x80, DEF_STR(Off))
PORT_DIPSETTING(0x00, DEF_STR(On))

/* IN3 - the real machine reads either the X or Y axis from this port */
/* Instead, we use the two fake 5 & 6 ports and bank-switch the proper */
/* value based on the lsb of the byte written to the sound port */
PORT_START("IN3")
PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_JOYSTICK_LEFT | IPF_4WAY)
PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_JOYSTICK_RIGHT | IPF_4WAY)
PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_JOYSTICK_UP | IPF_4WAY)
PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_JOYSTICK_DOWN | IPF_4WAY)

PORT_START("IN4")	/* IN4 - misc controls */
PORT_BIT(0x3f, IP_ACTIVE_HIGH, IPT_UNKNOWN)
PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_START1)
PORT_BIT(0x80, IP_ACTIVE_HIGH, IPT_BUTTON1)

/* These 2 are fake - they are bank-switched from reads to IN3 */
/* Red Baron doesn't seem to use the full 0-255 range. */
PORT_START("IN5")	/* IN5 */
PORT_ANALOG(0xff, 0x80, IPT_AD_STICK_X, 25, 10, 0, 64, 192)

PORT_START("IN6")/* IN6 */
PORT_ANALOG(0xff, 0x80, IPT_AD_STICK_Y, 25, 10, 0, 64, 192)
INPUT_PORTS_END

INPUT_PORTS_START(bwidow)
PORT_START("IN0")	/* IN0 */
PORT_BIT(0x01, IP_ACTIVE_LOW, IPT_COIN1)
PORT_BIT(0x02, IP_ACTIVE_LOW, IPT_COIN2)
PORT_BIT(0x0c, IP_ACTIVE_LOW, IPT_UNUSED)
PORT_BITX(0x10, 0x10, IPT_DIPSWITCH_NAME | IPF_TOGGLE, "Service Mode", OSD_KEY_F2, IP_JOY_NONE)
PORT_DIPSETTING(0x10, "Off")
PORT_DIPSETTING(0x00, "On")
PORT_BITX(0x20, IP_ACTIVE_LOW, IPT_SERVICE, "Diagnostic Step", OSD_KEY_F1, IP_JOY_NONE)
/* bit 6 is the VG HALT bit. We set it to "low" */
/* per default (busy vector processor). */
PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_UNKNOWN)
/* bit 7 is tied to a 3khz clock */
PORT_BIT(0x80, IP_ACTIVE_HIGH, IPT_UNKNOWN)

PORT_START("DSW0")	/* DSW0 */
PORT_DIPNAME(0x03, 0x00, "Coinage")
PORT_DIPSETTING(0x00, "1 Coin/1 Credit")
PORT_DIPSETTING(0x01, "2 Coins/1 Credit")
PORT_DIPSETTING(0x02, "Free Play")
PORT_DIPSETTING(0x03, "1 Coin/2 Credits")
PORT_DIPNAME(0x0c, 0x00, "Right Coin")
PORT_DIPSETTING(0x00, "*1")
PORT_DIPSETTING(0x04, "*4")
PORT_DIPSETTING(0x08, "*5")
PORT_DIPSETTING(0x0c, "*6")
PORT_DIPNAME(0x10, 0x00, "Left Coin")
PORT_DIPSETTING(0x00, "*1")
PORT_DIPSETTING(0x10, "*2")
PORT_DIPNAME(0xe0, 0x00, "Bonus Coins")
PORT_DIPSETTING(0x00, "None")
PORT_DIPSETTING(0x20, "3 credits/2 coins")
PORT_DIPSETTING(0x40, "5 credits/4 coins")
PORT_DIPSETTING(0x60, "6 credits/4 coins")
PORT_DIPSETTING(0x80, "6 credits/6 coins")
PORT_DIPSETTING(0xa0, "4 credits/3 coins")

PORT_START("DSW1")	/* DSW1 */
PORT_DIPNAME(0x03, 0x01, "Max Start")
PORT_DIPSETTING(0x00, "Lev 13")
PORT_DIPSETTING(0x01, "Lev 21")
PORT_DIPSETTING(0x02, "Lev 37")
PORT_DIPSETTING(0x03, "Lev 53")
PORT_DIPNAME(0x0c, 0x00, DEF_STR(Lives))
PORT_DIPSETTING(0x00, "3")
PORT_DIPSETTING(0x04, "4")
PORT_DIPSETTING(0x08, "5")
PORT_DIPSETTING(0x0c, "6")
PORT_DIPNAME(0x30, 0x10, "Difficulty")
PORT_DIPSETTING(0x00, "Easy")
PORT_DIPSETTING(0x10, "Medium")
PORT_DIPSETTING(0x20, "Hard")
PORT_DIPSETTING(0x30, "Demo")
PORT_DIPNAME(0xc0, 0x00, "Bonus Life")
PORT_DIPSETTING(0x00, "20000")
PORT_DIPSETTING(0x40, "30000")
PORT_DIPSETTING(0x80, "40000")
PORT_DIPSETTING(0xc0, "None")

PORT_START("IN3")	/* IN3 - Movement joystick */
PORT_BIT(0x01, IP_ACTIVE_LOW, IPT_JOYSTICKLEFT_RIGHT)
PORT_BIT(0x02, IP_ACTIVE_LOW, IPT_JOYSTICKLEFT_LEFT)
PORT_BIT(0x04, IP_ACTIVE_LOW, IPT_JOYSTICKLEFT_DOWN)
PORT_BIT(0x08, IP_ACTIVE_LOW, IPT_JOYSTICKLEFT_UP)
PORT_BIT(0x10, IP_ACTIVE_LOW, IPT_UNUSED)
PORT_BIT(0x20, IP_ACTIVE_LOW, IPT_START1)
PORT_BIT(0x40, IP_ACTIVE_LOW, IPT_START2)
PORT_BIT(0x80, IP_ACTIVE_LOW, IPT_UNUSED)

PORT_START("IN4")	/* IN4 - Firing joystick */
PORT_BIT(0x01, IP_ACTIVE_LOW, IPT_JOYSTICKRIGHT_RIGHT)
PORT_BIT(0x02, IP_ACTIVE_LOW, IPT_JOYSTICKRIGHT_LEFT)
PORT_BIT(0x04, IP_ACTIVE_LOW, IPT_JOYSTICKRIGHT_DOWN)
PORT_BIT(0x08, IP_ACTIVE_LOW, IPT_JOYSTICKRIGHT_UP)
PORT_BIT(0x10, IP_ACTIVE_LOW, IPT_UNUSED)
PORT_BIT(0x20, IP_ACTIVE_LOW, IPT_START1)
PORT_BIT(0x40, IP_ACTIVE_LOW, IPT_START2)
PORT_BIT(0x80, IP_ACTIVE_LOW, IPT_UNUSED)
INPUT_PORTS_END

INPUT_PORTS_START(gravitar)
PORT_START("IN0")	/* IN0 */
PORT_BIT(0x01, IP_ACTIVE_LOW, IPT_COIN1)
PORT_BIT(0x02, IP_ACTIVE_LOW, IPT_COIN2)
PORT_BIT(0x0c, IP_ACTIVE_LOW, IPT_UNUSED)
PORT_BITX(0x10, 0x10, IPT_DIPSWITCH_NAME | IPF_TOGGLE, DEF_STR(Service_Mode), OSD_KEY_F2, IP_JOY_NONE)
PORT_DIPSETTING(0x10, DEF_STR(Off))
PORT_DIPSETTING(0x00, DEF_STR(On))
PORT_BITX(0x20, IP_ACTIVE_LOW, IPT_SERVICE, "Diagnostic Step", OSD_KEY_F1, IP_JOY_NONE)
/* bit 6 is the VG HALT bit. We set it to "low" */
/* per default (busy vector processor). */
PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_UNKNOWN)
/* bit 7 is tied to a 3khz clock */
PORT_BIT(0x80, IP_ACTIVE_HIGH, IPT_UNKNOWN)

PORT_START("DSW0")	/* DSW0 */
PORT_BIT(0x03, IP_ACTIVE_HIGH, IPT_UNUSED)
PORT_DIPNAME(0x0c, 0x04, DEF_STR(Lives))
PORT_DIPSETTING(0x00, "3")
PORT_DIPSETTING(0x04, "4")
PORT_DIPSETTING(0x08, "5")
PORT_DIPSETTING(0x0c, "6")
PORT_DIPNAME(0x10, 0x00, DEF_STR(Difficulty))
PORT_DIPSETTING(0x00, "Easy")
PORT_DIPSETTING(0x10, "Hard")
PORT_BIT(0x20, IP_ACTIVE_HIGH, IPT_UNUSED)
PORT_DIPNAME(0xc0, 0x00, DEF_STR(Bonus_Life))
PORT_DIPSETTING(0x00, "10000")
PORT_DIPSETTING(0x40, "20000")
PORT_DIPSETTING(0x80, "30000")
PORT_DIPSETTING(0xc0, "None")

PORT_START("DSW1")	/* DSW1 */
PORT_DIPNAME(0x03, 0x00, DEF_STR(Coinage))
PORT_DIPSETTING(0x01, DEF_STR(2C_1C))
PORT_DIPSETTING(0x00, DEF_STR(1C_1C))
PORT_DIPSETTING(0x03, DEF_STR(1C_2C))
PORT_DIPSETTING(0x02, DEF_STR(Free_Play))
PORT_DIPNAME(0x0c, 0x00, DEF_STR(Coin_B))
PORT_DIPSETTING(0x00, "*1")
PORT_DIPSETTING(0x04, "*4")
PORT_DIPSETTING(0x08, "*5")
PORT_DIPSETTING(0x0c, "*6")
PORT_DIPNAME(0x10, 0x00, DEF_STR(Coin_A))
PORT_DIPSETTING(0x00, "*1")
PORT_DIPSETTING(0x10, "*2")
PORT_DIPNAME(0xe0, 0x00, "Bonus Coins")
PORT_DIPSETTING(0x00, "None")
PORT_DIPSETTING(0x20, "3 credits/2 coins")
PORT_DIPSETTING(0x40, "5 credits/4 coins")
PORT_DIPSETTING(0x60, "6 credits/4 coins")
PORT_DIPSETTING(0x80, "6 credits/6 coins")
PORT_DIPSETTING(0xa0, "4 credits/3 coins")

PORT_START("IN3")	/* IN3 - Player 1 */
PORT_BIT(0x01, IP_ACTIVE_LOW, IPT_BUTTON3)
PORT_BIT(0x02, IP_ACTIVE_LOW, IPT_BUTTON1)
PORT_BIT(0x04, IP_ACTIVE_LOW, IPT_JOYSTICK_RIGHT | IPF_2WAY)
PORT_BIT(0x08, IP_ACTIVE_LOW, IPT_JOYSTICK_LEFT | IPF_2WAY)
PORT_BIT(0x10, IP_ACTIVE_LOW, IPT_BUTTON2)
PORT_BIT(0x20, IP_ACTIVE_LOW, IPT_UNUSED)
PORT_BIT(0x40, IP_ACTIVE_LOW, IPT_UNUSED)
PORT_BIT(0x80, IP_ACTIVE_LOW, IPT_UNUSED)

PORT_START("IN4")	/* IN4 - Player 2 */
PORT_BIT(0x01, IP_ACTIVE_LOW, IPT_UNUSED)
PORT_BIT(0x02, IP_ACTIVE_LOW, IPT_UNUSED)
PORT_BIT(0x04, IP_ACTIVE_LOW, IPT_UNUSED)
PORT_BIT(0x08, IP_ACTIVE_LOW, IPT_UNUSED)
PORT_BIT(0x10, IP_ACTIVE_LOW, IPT_UNUSED)
PORT_BIT(0x20, IP_ACTIVE_LOW, IPT_START1)
PORT_BIT(0x40, IP_ACTIVE_LOW, IPT_START2)
PORT_BIT(0x80, IP_ACTIVE_LOW, IPT_UNUSED)
PORT_START("IN2")      /* IN2 */
PORT_ANALOG(0x0f, 0, IPT_TRACKBALL_Y | IPF_REVERSE, 20, 10, 7, 0, 0)

PORT_START("IN3")      /* IN3 */
PORT_ANALOG(0x0f, 0, IPT_TRACKBALL_X, 20, 10, 7, 0, 0)
INPUT_PORTS_END

INPUT_PORTS_START(spacduel)
PORT_START("IN0")	/* IN0 */
PORT_BIT(0x01, IP_ACTIVE_LOW, IPT_COIN1)
PORT_BIT(0x02, IP_ACTIVE_LOW, IPT_COIN2)
PORT_BIT(0x0c, IP_ACTIVE_LOW, IPT_UNUSED)
//PORT_SERVICE( 0x10, IP_ACTIVE_LOW )
PORT_BITX(0x10, 0x10, IPT_DIPSWITCH_NAME | IPF_TOGGLE, DEF_STR(Service_Mode), OSD_KEY_F2, IP_JOY_NONE)
PORT_DIPSETTING(0x10, DEF_STR(Off))
PORT_DIPSETTING(0x00, DEF_STR(On))
PORT_BITX(0x20, IP_ACTIVE_LOW, IPT_SERVICE, "Diagnostic Step", OSD_KEY_F1, IP_JOY_NONE)
/* bit 6 is the VG HALT bit. We set it to "low" */
/* per default (busy vector processor). */
PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_UNKNOWN)
/* bit 7 is tied to a 3kHz clock */
PORT_BIT(0x80, IP_ACTIVE_HIGH, IPT_UNKNOWN)

PORT_START("DSW0")	/* DSW0 */
PORT_DIPNAME(0x03, 0x01, DEF_STR(Lives))
PORT_DIPSETTING(0x01, "3")
PORT_DIPSETTING(0x00, "4")
PORT_DIPSETTING(0x03, "5")
PORT_DIPSETTING(0x02, "6")
PORT_DIPNAME(0x0c, 0x00, DEF_STR(Difficulty))
PORT_DIPSETTING(0x04, "Easy")
PORT_DIPSETTING(0x00, "Normal")
PORT_DIPSETTING(0x0c, "Medium")
PORT_DIPSETTING(0x08, "Hard")
PORT_DIPNAME(0x30, 0x00, "Language")
PORT_DIPSETTING(0x00, "English")
PORT_DIPSETTING(0x10, "German")
PORT_DIPSETTING(0x20, "French")
PORT_DIPSETTING(0x30, "Spanish")
PORT_DIPNAME(0xc0, 0x00, DEF_STR(Bonus_Life))
PORT_DIPSETTING(0xc0, "8000")
PORT_DIPSETTING(0x00, "10000")
PORT_DIPSETTING(0x40, "15000")
PORT_DIPSETTING(0x80, "None")

PORT_START("DSW1")	/* DSW1 */
PORT_DIPNAME(0x03, 0x00, DEF_STR(Coinage))
PORT_DIPSETTING(0x01, DEF_STR(2C_1C))
PORT_DIPSETTING(0x00, DEF_STR(1C_1C))
PORT_DIPSETTING(0x03, DEF_STR(1C_2C))
PORT_DIPSETTING(0x02, DEF_STR(Free_Play))
PORT_DIPNAME(0x0c, 0x00, DEF_STR(Coin_B))
PORT_DIPSETTING(0x00, "*1")
PORT_DIPSETTING(0x04, "*4")
PORT_DIPSETTING(0x08, "*5")
PORT_DIPSETTING(0x0c, "*6")
PORT_DIPNAME(0x10, 0x00, DEF_STR(Coin_A))
PORT_DIPSETTING(0x00, "*1")
PORT_DIPSETTING(0x10, "*2")
PORT_DIPNAME(0xe0, 0x00, "Bonus Coins")
PORT_DIPSETTING(0x00, "None")
PORT_DIPSETTING(0x20, "3 credits/2 coins")
PORT_DIPSETTING(0xa0, "4 credits/3 coins")
PORT_DIPSETTING(0x40, "5 credits/4 coins")
PORT_DIPSETTING(0x60, "6 credits/4 coins")
PORT_DIPSETTING(0x80, "6 credits/6 coins")

PORT_START("IN3")	// IN3 - Player 1 - spread over 8 memory locations
PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_JOYSTICK_LEFT | IPF_2WAY)
PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_JOYSTICK_RIGHT | IPF_2WAY)
PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_BUTTON1)
PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_BUTTON3)
PORT_BIT(0x10, IP_ACTIVE_HIGH, IPT_BUTTON2)
PORT_BIT(0x20, IP_ACTIVE_HIGH, IPT_START1)
PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_START2)
PORT_BIT(0x80, IP_ACTIVE_HIGH, IPT_UNUSED)

PORT_START("IN4")	// IN4 - Player 2 - spread over 8 memory locations
PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_JOYSTICK_LEFT | IPF_2WAY | IPF_PLAYER2)
PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_JOYSTICK_RIGHT | IPF_2WAY | IPF_PLAYER2)
PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_BUTTON1 | IPF_PLAYER2)
PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_BUTTON2 | IPF_PLAYER2)
PORT_BIT(0x10, IP_ACTIVE_HIGH, IPT_BUTTON3 | IPF_PLAYER2)
PORT_BIT(0x20, IP_ACTIVE_HIGH, IPT_START1)
PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_START2)
PORT_BIT(0x80, IP_ACTIVE_HIGH, IPT_UNUSED)
INPUT_PORTS_END

INPUT_PORTS_START(tempest)
PORT_START("IN0")	/* IN0 */
PORT_BIT(0x01, IP_ACTIVE_LOW, IPT_COIN3)
PORT_BIT(0x02, IP_ACTIVE_LOW, IPT_COIN2)
PORT_BIT(0x04, IP_ACTIVE_LOW, IPT_COIN1)
PORT_BIT(0x08, IP_ACTIVE_LOW, IPT_TILT)
PORT_BITX(0x10, 0x10, IPT_DIPSWITCH_NAME | IPF_TOGGLE, DEF_STR(Service_Mode), OSD_KEY_F2, IP_JOY_NONE)
PORT_DIPSETTING(0x10, DEF_STR(Off))
PORT_DIPSETTING(0x00, DEF_STR(On))
PORT_BITX(0x20, IP_ACTIVE_LOW, IPT_SERVICE, "Diagnostic Step", OSD_KEY_F1, IP_JOY_NONE)
/* bit 6 is the VG HALT bit. We set it to "low" */
/* per default (busy vector processor). */
/* handled by tempest_IN0_r() */
PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_UNKNOWN)
/* bit 7 is tied to a 3khz (?) clock */
/* handled by tempest_IN0_r() */
PORT_BIT(0x80, IP_ACTIVE_HIGH, IPT_UNKNOWN)

PORT_START("IN1")	/* IN1/DSW0 */
/* This is the Tempest spinner input. It only uses 4 bits. */
PORT_ANALOG(0x0f, 0x00, IPT_DIAL | IPF_REVERSE, 25, 20, 0, 0, 0)
/* The next one is reponsible for cocktail mode.
 * According to the documentation, this is not a switch, although
 * it may have been planned to put it on the Math Box PCB, D/E2 )
 */
	PORT_DIPNAME(0x10, 0x10, DEF_STR(Cabinet))
	PORT_DIPSETTING(0x00, DEF_STR(Upright))
	PORT_DIPSETTING(0x10, DEF_STR(Cocktail))
	PORT_BIT(0x20, IP_ACTIVE_HIGH, IPT_UNKNOWN)
	PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_UNKNOWN)
	PORT_BIT(0x80, IP_ACTIVE_HIGH, IPT_UNKNOWN)

	PORT_START("IN2")	/* IN2 */
	PORT_DIPNAME(0x03, 0x00, DEF_STR(Difficulty))
	PORT_DIPSETTING(0x01, "Easy")
	PORT_DIPSETTING(0x00, "Medium1")
	PORT_DIPSETTING(0x03, "Medium2")
	PORT_DIPSETTING(0x02, "Hard")
	PORT_DIPNAME(0x04, 0x00, "Rating")
	PORT_DIPSETTING(0x00, "1, 3, 5, 7, 9")
	PORT_DIPSETTING(0x04, "tied to high score")
	PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_BUTTON2)
	PORT_BIT(0x10, IP_ACTIVE_HIGH, IPT_BUTTON1)
	PORT_BIT(0x20, IP_ACTIVE_HIGH, IPT_START1)
	PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_START2)
	PORT_BIT(0x80, IP_ACTIVE_HIGH, IPT_UNKNOWN)

	PORT_START("DS1")	/* DSW1 - (N13 on analog vector generator PCB */
	PORT_DIPNAME(0x03, 0x00, DEF_STR(Coinage))
	PORT_DIPSETTING(0x01, DEF_STR(2C_1C))
	PORT_DIPSETTING(0x00, DEF_STR(1C_1C))
	PORT_DIPSETTING(0x03, DEF_STR(1C_2C))
	PORT_DIPSETTING(0x02, DEF_STR(Free_Play))
	PORT_DIPNAME(0x0c, 0x00, "Right Coin")
	PORT_DIPSETTING(0x00, "*1")
	PORT_DIPSETTING(0x04, "*4")
	PORT_DIPSETTING(0x08, "*5")
	PORT_DIPSETTING(0x0c, "*6")
	PORT_DIPNAME(0x10, 0x00, "Left Coin")
	PORT_DIPSETTING(0x00, "*1")
	PORT_DIPSETTING(0x10, "*2")
	PORT_DIPNAME(0xe0, 0x00, "Bonus Coins")
	PORT_DIPSETTING(0x00, "None")
	PORT_DIPSETTING(0x80, "1 each 5")
	PORT_DIPSETTING(0x40, "1 each 4 (+Demo)")
	PORT_DIPSETTING(0xa0, "1 each 3")
	PORT_DIPSETTING(0x60, "2 each 4 (+Demo)")
	PORT_DIPSETTING(0x20, "1 each 2")
	PORT_DIPSETTING(0xc0, "Freeze Mode")
	PORT_DIPSETTING(0xe0, "Freeze Mode")

	PORT_START("DS2")	/* DSW2 - (L12 on analog vector generator PCB */
	PORT_DIPNAME(0x01, 0x00, "Minimum")
	PORT_DIPSETTING(0x00, "1 Credit")
	PORT_DIPSETTING(0x01, "2 Credit")
	PORT_DIPNAME(0x06, 0x00, "Language")
	PORT_DIPSETTING(0x00, "English")
	PORT_DIPSETTING(0x02, "French")
	PORT_DIPSETTING(0x04, "German")
	PORT_DIPSETTING(0x06, "Spanish")
	PORT_DIPNAME(0x38, 0x00, DEF_STR(Bonus_Life))
	PORT_DIPSETTING(0x08, "10000")
	PORT_DIPSETTING(0x00, "20000")
	PORT_DIPSETTING(0x10, "30000")
	PORT_DIPSETTING(0x18, "40000")
	PORT_DIPSETTING(0x20, "50000")
	PORT_DIPSETTING(0x28, "60000")
	PORT_DIPSETTING(0x30, "70000")
	PORT_DIPSETTING(0x38, "None")
	PORT_DIPNAME(0xc0, 0x00, DEF_STR(Lives))
	PORT_DIPSETTING(0xc0, "2")
	PORT_DIPSETTING(0x00, "3")
	PORT_DIPSETTING(0x40, "4")
	PORT_DIPSETTING(0x80, "5")
	INPUT_PORTS_END

	INPUT_PORTS_START(starwars)
	PORT_START("IN0")//// IN0 
	PORT_BIT(0x01, IP_ACTIVE_LOW, IPT_COIN2)
	PORT_BIT(0x02, IP_ACTIVE_LOW, IPT_COIN1)
	PORT_BIT(0x04, IP_ACTIVE_LOW, IPT_COIN3)
	PORT_BIT(0x08, IP_ACTIVE_LOW, IPT_TILT)
	PORT_BITX(0x10, 0x10, IPT_DIPSWITCH_NAME | IPF_TOGGLE, "Service Mode", OSD_KEY_F2, IP_JOY_NONE)
	PORT_DIPSETTING(0x10, "Off")
	PORT_DIPSETTING(0x00, "On")
	PORT_BIT(0x20, IP_ACTIVE_HIGH, IPT_UNUSED)
	PORT_BIT(0x40, IP_ACTIVE_LOW, IPT_START2)
	PORT_BIT(0x80, IP_ACTIVE_LOW, IPT_START1)

	PORT_START("IN1")	// IN1 
	PORT_BIT(0x03, IP_ACTIVE_HIGH, IPT_UNUSED)
	PORT_BITX(0x04, IP_ACTIVE_LOW, IPT_SERVICE, "Diagnostic Step", OSD_KEY_F1, IP_JOY_NONE)
	PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_UNUSED)
	PORT_BIT(0x10, IP_ACTIVE_LOW, IPT_BUTTON2)
	PORT_BIT(0x20, IP_ACTIVE_LOW, IPT_BUTTON1)
	// Bit 6 is MATH_RUN - see machine/starwars.c 
	PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_UNUSED)
	// Bit 7 is VG_HALT - see machine/starwars.c 
	PORT_BIT(0x80, IP_ACTIVE_HIGH, IPT_UNUSED)

	PORT_START("DSW")	// DSW0 
	PORT_DIPNAME(0x03, 0x00, "Shields")
	PORT_DIPSETTING(0x00, "6")
	PORT_DIPSETTING(0x01, "7")
	PORT_DIPSETTING(0x02, "8")
	PORT_DIPSETTING(0x03, "9")
	PORT_DIPNAME(0x0c, 0x04, "Difficulty")
	PORT_DIPSETTING(0x00, "Easy")
	PORT_DIPSETTING(0x04, "Moderate")
	PORT_DIPSETTING(0x08, "Hard")
	PORT_DIPSETTING(0x0c, "Hardest")
	PORT_DIPNAME(0x30, 0x00, "Bonus Shields")
	PORT_DIPSETTING(0x00, "0")
	PORT_DIPSETTING(0x10, "1")
	PORT_DIPSETTING(0x20, "2")
	PORT_DIPSETTING(0x30, "3")
	PORT_DIPNAME(0x40, 0x00, "Attract Music")
	PORT_DIPSETTING(0x00, "On")
	PORT_DIPSETTING(0x40, "Off")
	PORT_DIPNAME(0x80, 0x80, "Game Mode")
	PORT_DIPSETTING(0x00, "Freeze")
	PORT_DIPSETTING(0x80, "Normal")

	PORT_START("DS1")// DSW1 
	PORT_DIPNAME(0x03, 0x02, "Credits/Coin")
	PORT_DIPSETTING(0x00, "Free Play")
	PORT_DIPSETTING(0x01, "2")
	PORT_DIPSETTING(0x02, "1")
	PORT_DIPSETTING(0x03, "1/2")
	PORT_BIT(0xfc, IP_ACTIVE_HIGH, IPT_UNKNOWN)

	PORT_START("IN4")	// IN4 
	PORT_ANALOG(0xff, 0x80, IPT_AD_STICK_Y, 70, 30, 0, 0, 255)

	PORT_START("IN5")	// IN5 
	PORT_ANALOG(0xff, 0x80, IPT_AD_STICK_X, 50, 30, 0, 0, 255)
	INPUT_PORTS_END

	//////////////////////////////////////////////////////////

	/*************************************
	 *
	 *	Port definitions
	 *
	 *************************************/

	 /* This fake input port is used for DIP Switch 2
		for all games except Eliminato 4 players */
#define COINAGE PORT_START("DSW2") \
		PORT_DIPNAME( 0x0f, 0x0c, DEF_STR ( Coin_B ) ) \
		PORT_DIPSETTING(	0x00, DEF_STR ( 4C_1C ) ) \
		PORT_DIPSETTING(	0x08, DEF_STR ( 3C_1C ) ) \
		PORT_DIPSETTING(	0x09, "2 Coins/1 Credit 5/3 6/4" ) \
		PORT_DIPSETTING(	0x05, "2 Coins/1 Credit 4/3" ) \
		PORT_DIPSETTING(	0x04, DEF_STR ( 2C_1C ) ) \
		PORT_DIPSETTING(	0x0c, DEF_STR ( 1C_1C ) ) \
		PORT_DIPSETTING(	0x0d, "1 Coin/1 Credit 5/6" ) \
		PORT_DIPSETTING(	0x03, "1 Coin/1 Credit 4/5" ) \
		PORT_DIPSETTING(	0x0b, "1 Coin/1 Credit 2/3" ) \
		PORT_DIPSETTING(	0x02, DEF_STR ( 1C_2C ) ) \
		PORT_DIPSETTING(	0x0f, "1 Coin/2 Credits 4/9" ) \
		PORT_DIPSETTING(	0x07, "1 Coin/2 Credits 5/11" ) \
		PORT_DIPSETTING(	0x0a, DEF_STR ( 1C_3C ) ) \
		PORT_DIPSETTING(	0x06, DEF_STR ( 1C_4C ) ) \
		PORT_DIPSETTING(	0x0e, DEF_STR ( 1C_5C ) ) \
		PORT_DIPSETTING(	0x01, DEF_STR ( 1C_6C ) ) \
		PORT_DIPNAME( 0xf0, 0xc0, DEF_STR ( Coin_A ) ) \
		PORT_DIPSETTING(	0x00, DEF_STR ( 4C_1C ) ) \
		PORT_DIPSETTING(	0x80, DEF_STR ( 3C_1C ) ) \
		PORT_DIPSETTING(	0x90, "2 Coins/1 Credit 5/3 6/4" ) \
		PORT_DIPSETTING(	0x50, "2 Coins/1 Credit 4/3" ) \
		PORT_DIPSETTING(	0x40, DEF_STR ( 2C_1C ) ) \
		PORT_DIPSETTING(	0xc0, DEF_STR ( 1C_1C ) ) \
		PORT_DIPSETTING(	0xd0, "1 Coin/1 Credit 5/6" ) \
		PORT_DIPSETTING(	0x30, "1 Coin/1 Credit 4/5" ) \
		PORT_DIPSETTING(	0xb0, "1 Coin/1 Credit 2/3" ) \
		PORT_DIPSETTING(	0x20, DEF_STR ( 1C_2C ) ) \
		PORT_DIPSETTING(	0xf0, "1 Coin/2 Credits 4/9" ) \
		PORT_DIPSETTING(	0x70, "1 Coin/2 Credits 5/11" ) \
		PORT_DIPSETTING(	0xa0, DEF_STR ( 1C_3C ) ) \
		PORT_DIPSETTING(	0x60, DEF_STR ( 1C_4C ) ) \
		PORT_DIPSETTING(	0xe0, DEF_STR ( 1C_5C ) ) \
		PORT_DIPSETTING(	0x10, DEF_STR ( 1C_6C ) )

	INPUT_PORTS_START(spacfury)
	PORT_START("IN0")	/* IN0 - port 0xf8 */
	/* The next bit is referred to as the Service switch in the self test - it just adds a credit */
	PORT_BIT_IMPULSE(0x20, IP_ACTIVE_LOW, IPT_COIN3, 3)
	PORT_BIT_IMPULSE(0x40, IP_ACTIVE_LOW, IPT_COIN2, 3)
	PORT_BIT_IMPULSE(0x80, IP_ACTIVE_LOW, IPT_COIN1, 3)

	PORT_START("IN1")	/* IN1 - port 0xf9 */
	PORT_BIT(0x10, IP_ACTIVE_LOW, IPT_START2)
	PORT_BIT(0x20, IP_ACTIVE_LOW, IPT_START1)
	PORT_BIT(0xc0, IP_ACTIVE_LOW, IPT_UNUSED)

	PORT_START("IN2")	/* IN2 - port 0xfa */
	PORT_BIT(0x10, IP_ACTIVE_LOW, IPT_JOYSTICK_RIGHT)
	PORT_BIT(0x20, IP_ACTIVE_LOW, IPT_JOYSTICK_LEFT)
	PORT_BIT(0xc0, IP_ACTIVE_LOW, IPT_UNUSED)

	PORT_START("IN3")	/* IN3 - port 0xfb */
	PORT_BIT(0x10, IP_ACTIVE_LOW, IPT_BUTTON2)
	PORT_BIT(0x20, IP_ACTIVE_LOW, IPT_BUTTON1)
	PORT_BIT(0xc0, IP_ACTIVE_LOW, IPT_UNUSED)

	PORT_START("IN4")	/* IN4 - FAKE - lazy way to move the self-test fake input port to 5 */
	PORT_BIT(0xff, IP_ACTIVE_LOW, IPT_UNUSED)

	PORT_START("FAKE1")	/* IN5 - FAKE */
	/* This fake input port is used to get the status of the F2 key, */
	/* and activate the test mode, which is triggered by a NMI */
	PORT_BITX(0x01, IP_ACTIVE_HIGH, IPT_SERVICE, DEF_STR(Service_Mode), OSD_KEY_F2, IP_JOY_NONE)

	PORT_START("DSW1")	/* FAKE */
	/* This fake input port is used for DIP Switch 1 */
/* This fake input port is used for DIP Switch 1 */
PORT_DIPNAME(0x03, 0x01, DEF_STR(Bonus_Life))
PORT_DIPSETTING(0x00, "10000")
PORT_DIPSETTING(0x02, "20000")
PORT_DIPSETTING(0x01, "30000")
PORT_DIPSETTING(0x03, "40000")
PORT_DIPNAME(0x0c, 0x00, DEF_STR(Difficulty))
PORT_DIPSETTING(0x00, "Easy")
PORT_DIPSETTING(0x08, "Normal")
PORT_DIPSETTING(0x04, "Hard")
PORT_DIPSETTING(0x0c, "Very Hard")
PORT_DIPNAME(0x30, 0x30, DEF_STR(Lives))
PORT_DIPSETTING(0x00, "2")
PORT_DIPSETTING(0x20, "3")
PORT_DIPSETTING(0x10, "4")
PORT_DIPSETTING(0x30, "5")
PORT_DIPNAME(0x40, 0x00, DEF_STR(Demo_Sounds))
PORT_DIPSETTING(0x40, DEF_STR(Off))
PORT_DIPSETTING(0x00, DEF_STR(On))
PORT_DIPNAME(0x80, 0x80, DEF_STR(Cabinet))
PORT_DIPSETTING(0x80, DEF_STR(Upright))
PORT_DIPSETTING(0x00, DEF_STR(Cocktail))

COINAGE

PORT_START("IN8")	/* IN8 - port 0xfc */
PORT_BIT(0x10, IP_ACTIVE_HIGH, IPT_BUTTON2 | IPF_PLAYER2)
PORT_BIT(0x20, IP_ACTIVE_LOW, IPT_BUTTON1 | IPF_PLAYER2)
PORT_BIT(0x40, IP_ACTIVE_LOW, IPT_JOYSTICK_LEFT | IPF_PLAYER2)
PORT_BIT(0x80, IP_ACTIVE_LOW, IPT_JOYSTICK_RIGHT | IPF_PLAYER2)
INPUT_PORTS_END

INPUT_PORTS_START(zektor)
PORT_START("IN0")	/* IN0 - port 0xf8 */
/* The next bit is referred to as the Service switch in the self test - it just adds a credit */
PORT_BIT_IMPULSE(0x20, IP_ACTIVE_LOW, IPT_COIN3, 3)
PORT_BIT_IMPULSE(0x40, IP_ACTIVE_LOW, IPT_COIN2, 3)
PORT_BIT_IMPULSE(0x80, IP_ACTIVE_LOW, IPT_COIN1, 3)
PORT_START("IN1")	/* IN1 - port 0xf9 */
PORT_BIT(0xf0, IP_ACTIVE_LOW, IPT_UNUSED)

PORT_START("IN2")	/* IN2 - port 0xfa */
PORT_BIT(0xf0, IP_ACTIVE_LOW, IPT_UNUSED)

PORT_START("IN3")	/* IN3 - port 0xfb */
PORT_BIT(0xf0, IP_ACTIVE_LOW, IPT_UNUSED)

PORT_START("IN4")	/* IN4 - port 0xfc - read in machine/sega.c */
PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_START1)
PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_START2)
PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_BUTTON1)
PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_BUTTON2)
PORT_BIT(0xf0, IP_ACTIVE_HIGH, IPT_UNUSED)

PORT_START("FAKE1")	/* IN5 - FAKE */
/* This fake input port is used to get the status of the F2 key, */
/* and activate the test mode, which is triggered by a NMI */
PORT_BITX(0x01, IP_ACTIVE_HIGH, IPT_SERVICE, DEF_STR(Service_Mode), OSD_KEY_F2, IP_JOY_NONE)

PORT_START("DSW1")	/* FAKE */
/* This fake input port is used for DIP Switch 1 */
PORT_DIPNAME(0x03, 0x01, DEF_STR(Bonus_Life))
PORT_DIPSETTING(0x03, "10000")
PORT_DIPSETTING(0x01, "20000")
PORT_DIPSETTING(0x02, "30000")
PORT_DIPSETTING(0x00, "None")
PORT_DIPNAME(0x0c, 0x00, DEF_STR(Difficulty))
PORT_DIPSETTING(0x00, "Easy")
PORT_DIPSETTING(0x08, "Normal")
PORT_DIPSETTING(0x04, "Hard")
PORT_DIPSETTING(0x0c, "Very Hard")
PORT_DIPNAME(0x30, 0x30, DEF_STR(Lives))
PORT_DIPSETTING(0x00, "2")
PORT_DIPSETTING(0x20, "3")
PORT_DIPSETTING(0x10, "4")
PORT_DIPSETTING(0x30, "5")
PORT_DIPNAME(0x40, 0x00, DEF_STR(Demo_Sounds))
PORT_DIPSETTING(0x40, DEF_STR(Off))
PORT_DIPSETTING(0x00, DEF_STR(On))
PORT_DIPNAME(0x80, 0x80, DEF_STR(Cabinet))
PORT_DIPSETTING(0x80, DEF_STR(Upright))
PORT_DIPSETTING(0x00, DEF_STR(Cocktail))

COINAGE

PORT_START("IN8")		/* IN8 - FAKE port for the dial */
PORT_ANALOG(0xff, 0x00, IPT_DIAL | IPF_CENTER, 100, 10, 0, 0, 0)
INPUT_PORTS_END

INPUT_PORTS_START(startrek)
PORT_START("IN0")	/* IN0 - port 0xf8 */
/* The next bit is referred to as the Service switch in the self test - it just adds a credit */
PORT_BIT_IMPULSE(0x20, IP_ACTIVE_LOW, IPT_COIN3, 3)
PORT_BIT_IMPULSE(0x40, IP_ACTIVE_LOW, IPT_COIN2, 3)
PORT_BIT_IMPULSE(0x80, IP_ACTIVE_LOW, IPT_COIN1, 3)

PORT_START("IN1")	/* IN1 - port 0xf9 */
PORT_BIT(0xf0, IP_ACTIVE_LOW, IPT_UNUSED)

PORT_START("IN2")	/* IN2 - port 0xfa */
PORT_BIT(0xf0, IP_ACTIVE_LOW, IPT_UNUSED)

PORT_START("IN3")	/* IN3 - port 0xfb */
PORT_BIT(0xf0, IP_ACTIVE_LOW, IPT_UNUSED)

PORT_START("IN4")	/* IN4 - port 0xfc - read in machine/sega.c */
PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_START1)
PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_START2)
PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_BUTTON2)
PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_BUTTON1)
PORT_BIT(0x10, IP_ACTIVE_HIGH, IPT_BUTTON3)
PORT_BIT(0x20, IP_ACTIVE_HIGH, IPT_BUTTON4)
PORT_BIT(0xc0, IP_ACTIVE_HIGH, IPT_UNUSED)

PORT_START("FAKE1")	/* IN5 - FAKE */
/* This fake input port is used to get the status of the F2 key, */
/* and activate the test mode, which is triggered by a NMI */
PORT_BITX(0x01, IP_ACTIVE_HIGH, IPT_SERVICE, DEF_STR(Service_Mode), OSD_KEY_F2, IP_JOY_NONE)

PORT_START("DSW1")	/* FAKE */
/* This fake input port is used for DIP Switch 1 */
PORT_DIPNAME(0x03, 0x01, DEF_STR(Bonus_Life))
PORT_DIPSETTING(0x00, "10000")
PORT_DIPSETTING(0x02, "20000")
PORT_DIPSETTING(0x01, "30000")
PORT_DIPSETTING(0x03, "40000")
PORT_DIPNAME(0x0c, 0x00, DEF_STR(Difficulty))
PORT_DIPSETTING(0x00, "Easy")
PORT_DIPSETTING(0x08, "Medium")
PORT_DIPSETTING(0x04, "Hard")
PORT_DIPSETTING(0x0c, "Tournament")
PORT_DIPNAME(0x30, 0x30, "Photon Torpedoes")
PORT_DIPSETTING(0x00, "1")
PORT_DIPSETTING(0x20, "2")
PORT_DIPSETTING(0x10, "3")
PORT_DIPSETTING(0x30, "4")
PORT_DIPNAME(0x40, 0x00, "Demo Sounds?")
PORT_DIPSETTING(0x40, DEF_STR(Off))
PORT_DIPSETTING(0x00, DEF_STR(On))
PORT_DIPNAME(0x80, 0x80, DEF_STR(Cabinet))
PORT_DIPSETTING(0x80, DEF_STR(Upright))
PORT_DIPSETTING(0x00, DEF_STR(Cocktail))

COINAGE

PORT_START("FAKE2")		/* IN8 - dummy port for the dial */
PORT_ANALOG(0xff, 0x00, IPT_DIAL | IPF_CENTER, 100, 10, 0, 0, 0)
INPUT_PORTS_END

INPUT_PORTS_START(tacscan)
PORT_START("IN0")	/* IN0 - port 0xf8 */
/* The next bit is referred to as the Service switch in the self test - it just adds a credit */
PORT_BIT_IMPULSE(0x20, IP_ACTIVE_LOW, IPT_COIN3, 3)
PORT_BIT_IMPULSE(0x40, IP_ACTIVE_LOW, IPT_COIN2, 3)
PORT_BIT_IMPULSE(0x80, IP_ACTIVE_LOW, IPT_COIN1, 3)

PORT_START("IN1")	/* IN1 - port 0xf9 */
PORT_BIT(0xf0, IP_ACTIVE_LOW, IPT_UNUSED)

PORT_START("IN2")	/* IN2 - port 0xfa */
PORT_BIT(0xf0, IP_ACTIVE_LOW, IPT_UNUSED)

PORT_START("IN3")	/* IN3 - port 0xfb */
PORT_BIT(0xf0, IP_ACTIVE_LOW, IPT_UNUSED)

PORT_START("IN4")	/* IN4 - port 0xfc - read in machine/sega.c */
PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_START1)
PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_START2)
PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_BUTTON1)
PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_BUTTON2)
PORT_BIT(0xf0, IP_ACTIVE_HIGH, IPT_UNUSED)

PORT_START("FAKE1")	/* IN5 - FAKE */
/* This fake input port is used to get the status of the F2 key, */
/* and activate the test mode, which is triggered by a NMI */
PORT_BITX(0x01, IP_ACTIVE_HIGH, IPT_SERVICE, DEF_STR(Service_Mode), OSD_KEY_F2, IP_JOY_NONE)

PORT_START("DSW1")	/* FAKE */
/* This fake input port is used for DIP Switch 1 */
PORT_DIPNAME(0x03, 0x01, DEF_STR(Bonus_Life))
PORT_DIPSETTING(0x03, "10000")
PORT_DIPSETTING(0x01, "20000")
PORT_DIPSETTING(0x02, "30000")
PORT_DIPSETTING(0x00, "None")
PORT_DIPNAME(0x0c, 0x00, DEF_STR(Difficulty))
PORT_DIPSETTING(0x00, "Easy")
PORT_DIPSETTING(0x08, "Normal")
PORT_DIPSETTING(0x04, "Hard")
PORT_DIPSETTING(0x0c, "Very Hard")
PORT_DIPNAME(0x30, 0x30, "Number of Ships")
PORT_DIPSETTING(0x00, "2")
PORT_DIPSETTING(0x20, "4")
PORT_DIPSETTING(0x10, "6")
PORT_DIPSETTING(0x30, "8")
PORT_DIPNAME(0x40, 0x00, "Demo Sounds?")
PORT_DIPSETTING(0x40, DEF_STR(Off))
PORT_DIPSETTING(0x00, DEF_STR(On))
PORT_DIPNAME(0x80, 0x80, DEF_STR(Cabinet))
PORT_DIPSETTING(0x80, DEF_STR(Upright))
PORT_DIPSETTING(0x00, DEF_STR(Cocktail))

COINAGE

PORT_START("FAKE2")		/* IN8 - FAKE port for the dial */
PORT_ANALOG(0xff, 0x00, IPT_DIAL | IPF_CENTER, 100, 10, 0, 0, 0)
INPUT_PORTS_END

INPUT_PORTS_START(elim2)
PORT_START("IN0")	/* IN0 - port 0xf8 */
/* The next bit is referred to as the Service switch in the self test - it just adds a credit */
PORT_BIT_IMPULSE(0x20, IP_ACTIVE_LOW, IPT_COIN3, 3)
PORT_BIT_IMPULSE(0x40, IP_ACTIVE_LOW, IPT_COIN2, 3)
PORT_BIT_IMPULSE(0x80, IP_ACTIVE_LOW, IPT_COIN1, 3)

PORT_START("IN1")	/* IN1 - port 0xf9 */
PORT_BIT(0x10, IP_ACTIVE_LOW, IPT_START2)
PORT_BIT(0x20, IP_ACTIVE_LOW, IPT_START1)
PORT_BIT(0xc0, IP_ACTIVE_LOW, IPT_UNUSED)

PORT_START("IN2")	/* IN2 - port 0xfa */
PORT_BIT(0x10, IP_ACTIVE_LOW, IPT_BUTTON2)
PORT_BIT(0x20, IP_ACTIVE_LOW, IPT_JOYSTICK_RIGHT)
PORT_BIT(0x40, IP_ACTIVE_LOW, IPT_JOYSTICK_LEFT)
PORT_BIT(0x80, IP_ACTIVE_LOW, IPT_UNUSED)

PORT_START("IN3")	/* IN3 - port 0xfb */
PORT_BIT(0x10, IP_ACTIVE_LOW, IPT_JOYSTICK_LEFT | IPF_PLAYER2)
PORT_BIT(0x20, IP_ACTIVE_LOW, IPT_BUTTON1)
PORT_BIT(0xc0, IP_ACTIVE_LOW, IPT_UNUSED)

PORT_START("IN4")	/* IN4 - port 0xfc - read in machine/sega.c */
PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_BUTTON1 | IPF_PLAYER2)
PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_BUTTON2 | IPF_PLAYER2)
PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_JOYSTICK_RIGHT | IPF_PLAYER2)
PORT_BIT(0xf8, IP_ACTIVE_HIGH, IPT_UNUSED)

PORT_START("FAKE1")	/* IN5 - FAKE */
/* This fake input port is used to get the status of the F2 key, */
/* and activate the test mode, which is triggered by a NMI */
PORT_BITX(0x01, IP_ACTIVE_HIGH, IPT_SERVICE, DEF_STR(Service_Mode), OSD_KEY_F2, IP_JOY_NONE)

PORT_START("DSW1")	/* FAKE */
/* This fake input port is used for DIP Switch 1 */
PORT_DIPNAME(0x03, 0x02, DEF_STR(Bonus_Life))
PORT_DIPSETTING(0x01, "10000")
PORT_DIPSETTING(0x02, "20000")
PORT_DIPSETTING(0x00, "30000")
PORT_DIPSETTING(0x03, "None")
PORT_DIPNAME(0x0c, 0x00, DEF_STR(Difficulty))
PORT_DIPSETTING(0x00, "Easy")
PORT_DIPSETTING(0x08, "Normal")
PORT_DIPSETTING(0x04, "Hard")
PORT_DIPSETTING(0x0c, "Very Hard")
PORT_DIPNAME(0x30, 0x20, DEF_STR(Lives))
PORT_DIPSETTING(0x20, "3")
PORT_DIPSETTING(0x10, "4")
PORT_DIPSETTING(0x00, "5")
/* 0x30 gives 5 Lives */
PORT_DIPNAME(0x80, 0x80, DEF_STR(Cabinet))
PORT_DIPSETTING(0x80, DEF_STR(Upright))
PORT_DIPSETTING(0x00, DEF_STR(Cocktail))

COINAGE
INPUT_PORTS_END

INPUT_PORTS_START(elim4)
PORT_START("IN0")	/* IN0 - port 0xf8 */
PORT_BIT(0x10, IP_ACTIVE_LOW, IPT_BUTTON1)
/* The next bit is referred to as the Service switch in the self test - it just adds a credit */
PORT_BIT_IMPULSE(0x20, IP_ACTIVE_LOW, IPT_COIN1, 3)
PORT_BIT_IMPULSE(0x40, IP_ACTIVE_LOW, IPT_COIN2, 3)
PORT_BIT_IMPULSE(0x80, IP_ACTIVE_LOW, IPT_COIN3, 3)

PORT_START("IN1")	/* IN1 - port 0xf9 */
PORT_BIT(0x10, IP_ACTIVE_LOW, IPT_BUTTON2)
PORT_BIT(0x20, IP_ACTIVE_LOW, IPT_BUTTON2 | IPF_PLAYER2)
PORT_BIT(0xc0, IP_ACTIVE_LOW, IPT_UNUSED)

PORT_START("IN2")	/* IN2 - port 0xfa */
PORT_BIT(0x10, IP_ACTIVE_LOW, IPT_JOYSTICK_RIGHT)
PORT_BIT(0x20, IP_ACTIVE_LOW, IPT_JOYSTICK_RIGHT | IPF_PLAYER2)
PORT_BIT(0x40, IP_ACTIVE_LOW, IPT_BUTTON1 | IPF_PLAYER2)
PORT_BIT(0x80, IP_ACTIVE_LOW, IPT_UNUSED)

PORT_START("IN3")	/* IN3 - port 0xfb */
PORT_BIT(0x10, IP_ACTIVE_LOW, IPT_JOYSTICK_LEFT)
PORT_BIT(0x20, IP_ACTIVE_LOW, IPT_JOYSTICK_LEFT | IPF_PLAYER2)
PORT_BIT(0xc0, IP_ACTIVE_LOW, IPT_UNUSED)

PORT_START("IN4")	/* IN4 - port 0xfc - read in machine/sega.c */
PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_BUTTON1 | IPF_PLAYER3)
PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_BUTTON2 | IPF_PLAYER3)
PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_JOYSTICK_LEFT | IPF_PLAYER3)
PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_JOYSTICK_RIGHT | IPF_PLAYER3)
PORT_BIT(0x10, IP_ACTIVE_HIGH, IPT_BUTTON1 | IPF_PLAYER4)
PORT_BIT(0x20, IP_ACTIVE_HIGH, IPT_BUTTON2 | IPF_PLAYER4)
PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_JOYSTICK_LEFT | IPF_PLAYER4)
PORT_BIT(0x80, IP_ACTIVE_HIGH, IPT_JOYSTICK_RIGHT | IPF_PLAYER4)

PORT_START("FAKE1")	/* IN5 - FAKE */
/* This fake input port is used to get the status of the F2 key, */
/* and activate the test mode, which is triggered by a NMI */
PORT_BITX(0x01, IP_ACTIVE_HIGH, IPT_SERVICE, DEF_STR(Service_Mode), OSD_KEY_F2, IP_JOY_NONE)

PORT_START("DSW1")	/* FAKE */
/* This fake input port is used for DIP Switch 1 */
PORT_DIPNAME(0x03, 0x02, DEF_STR(Bonus_Life))
PORT_DIPSETTING(0x01, "10000")
PORT_DIPSETTING(0x02, "20000")
PORT_DIPSETTING(0x00, "30000")
PORT_DIPSETTING(0x03, "None")
PORT_DIPNAME(0x0c, 0x00, DEF_STR(Difficulty))
PORT_DIPSETTING(0x00, "Easy")
PORT_DIPSETTING(0x08, "Normal")
PORT_DIPSETTING(0x04, "Hard")
PORT_DIPSETTING(0x0c, "Very Hard")
PORT_DIPNAME(0x30, 0x30, DEF_STR(Lives))
PORT_DIPSETTING(0x20, "3")
PORT_DIPSETTING(0x10, "4")
PORT_DIPSETTING(0x00, "5")
/* 0x30 gives 5 Lives */
PORT_DIPNAME(0x80, 0x80, DEF_STR(Cabinet))
PORT_DIPSETTING(0x80, DEF_STR(Upright))
PORT_DIPSETTING(0x00, DEF_STR(Cocktail))

PORT_START("IN7")  /* That is the coinage port in all the other games */
PORT_BIT(0xff, IP_ACTIVE_LOW, IPT_UNKNOWN)

PORT_START("FAKE2")		/* IN8 - FAKE - port 0xfc - read in machine/sega.c */
PORT_BIT_IMPULSE(0x01, IP_ACTIVE_HIGH, IPT_COIN1, 3)
PORT_BIT_IMPULSE(0x02, IP_ACTIVE_HIGH, IPT_COIN2, 3)
PORT_BIT_IMPULSE(0x04, IP_ACTIVE_HIGH, IPT_COIN3, 3)
PORT_BIT_IMPULSE(0x08, IP_ACTIVE_HIGH, IPT_COIN4, 3)
PORT_BIT(0xf0, IP_ACTIVE_HIGH, IPT_UNUSED)
INPUT_PORTS_END

INPUT_PORTS_START(mhavoc)
PORT_START("IN0")	/* IN0 - alpha (player_1 = 0) */
PORT_BIT(0x03, IP_ACTIVE_HIGH, IPT_UNKNOWN)
PORT_BIT(0x04, IP_ACTIVE_LOW, IPT_JOYSTICK_LEFT)
PORT_BIT(0x08, IP_ACTIVE_LOW, IPT_JOYSTICK_RIGHT)
PORT_BIT(0x10, IP_ACTIVE_LOW, IPT_JOYSTICK_UP)
PORT_BITX(0x20, IP_ACTIVE_LOW, IPT_SERVICE, "Diag Step/Coin C", OSD_KEY_F1, IP_JOY_NONE)
PORT_BIT(0x40, IP_ACTIVE_LOW, IPT_COIN1)	/* Left Coin Switch  */
PORT_BIT(0x80, IP_ACTIVE_LOW, IPT_COIN2)	/* Right Coin */

PORT_START("IN1")	/* IN1 - gamma */
PORT_BIT(0x0f, IP_ACTIVE_LOW, IPT_UNKNOWN)
PORT_BIT(0x10, IP_ACTIVE_LOW, IPT_BUTTON2 | IPF_PLAYER2)
PORT_BIT(0x20, IP_ACTIVE_LOW, IPT_BUTTON1 | IPF_PLAYER2)
PORT_BIT(0x40, IP_ACTIVE_LOW, IPT_BUTTON2)
PORT_BIT(0x80, IP_ACTIVE_LOW, IPT_BUTTON1)

PORT_START("IN2")	/* IN2 - gamma */
PORT_ANALOG(0xff, 0x00, IPT_DIAL | IPF_REVERSE, 100, 40, 0, 0, 0)

PORT_START("DIP1") /* DIP Switch at position 13/14S */
PORT_DIPNAME(0x01, 0x00, "Adaptive Difficulty")
PORT_DIPSETTING(0x01, DEF_STR(Off))
PORT_DIPSETTING(0x00, DEF_STR(On))
PORT_DIPNAME(0x02, 0x00, DEF_STR(Demo_Sounds))
PORT_DIPSETTING(0x02, DEF_STR(Off))
PORT_DIPSETTING(0x00, DEF_STR(On))
PORT_DIPNAME(0x0c, 0x00, DEF_STR(Bonus_Life))
PORT_DIPSETTING(0x0c, "50000")
PORT_DIPSETTING(0x00, "100000")
PORT_DIPSETTING(0x04, "200000")
PORT_DIPSETTING(0x08, "None")
PORT_DIPNAME(0x30, 0x00, DEF_STR(Difficulty))
PORT_DIPSETTING(0x10, "Easy")
PORT_DIPSETTING(0x00, "Medium")
PORT_DIPSETTING(0x30, "Hard")
PORT_DIPSETTING(0x20, "Demo")
PORT_DIPNAME(0xc0, 0x00, DEF_STR(Lives))
PORT_DIPSETTING(0x00, "3 (2 in Free Play)")
PORT_DIPSETTING(0xc0, "4 (3 in Free Play)")
PORT_DIPSETTING(0x80, "5 (4 in Free Play)")
PORT_DIPSETTING(0x40, "6 (5 in Free Play)")

PORT_START("DIP2") /* DIP Switch at position 8S */
PORT_DIPNAME(0x03, 0x03, DEF_STR(Coinage))
PORT_DIPSETTING(0x02, DEF_STR(2C_1C))
PORT_DIPSETTING(0x03, DEF_STR(1C_1C))
PORT_DIPSETTING(0x00, DEF_STR(1C_2C))
PORT_DIPSETTING(0x01, DEF_STR(Free_Play))
PORT_DIPNAME(0x0c, 0x0c, "Right Coin Mech")
PORT_DIPSETTING(0x0c, "x1")
PORT_DIPSETTING(0x08, "x4")
PORT_DIPSETTING(0x04, "x5")
PORT_DIPSETTING(0x00, "x6")
PORT_DIPNAME(0x10, 0x10, "Left Coin Mech")
PORT_DIPSETTING(0x10, "x1")
PORT_DIPSETTING(0x00, "x2")
PORT_DIPNAME(0xe0, 0xe0, "Bonus Credits")
PORT_DIPSETTING(0x80, "2 each 4")
PORT_DIPSETTING(0x40, "1 each 3")
PORT_DIPSETTING(0xa0, "1 each 4")
PORT_DIPSETTING(0x60, "1 each 5")
PORT_DIPSETTING(0xe0, "None")

PORT_START("IN5")	/* IN5 - dummy for player_1 = 1 on alpha */
PORT_BIT(0x3f, IP_ACTIVE_HIGH, IPT_UNUSED)
PORT_DIPNAME(0x40, 0x40, "Credit to start")
PORT_DIPSETTING(0x40, "1")
PORT_DIPSETTING(0x00, "2")
PORT_BITX(0x80, 0x80, IPT_DIPSWITCH_NAME | IPF_TOGGLE, DEF_STR(Service_Mode), OSD_KEY_F2, IP_JOY_NONE)
PORT_DIPSETTING(0x00, DEF_STR(On))
PORT_DIPSETTING(0x80, DEF_STR(Off))

INPUT_PORTS_END

INPUT_PORTS_START(mhavocp)
PORT_START("IN0")	/* IN0 - alpha (player_1 = 0) */
PORT_BIT(0x0f, IP_ACTIVE_HIGH, IPT_UNKNOWN)
/* PORT_BIT ( 0x10, IP_ACTIVE_LOW, IPT_SERVICE, "Diag Step", OSD_KEY_T, IP_JOY_NONE ) */
PORT_BIT(0x10, IP_ACTIVE_LOW, IPT_UNKNOWN)
PORT_BITX(0x20, IP_ACTIVE_LOW, IPT_SERVICE, "Diag Step/Coin C", OSD_KEY_F1, IP_JOY_NONE)
PORT_BIT(0x40, IP_ACTIVE_LOW, IPT_COIN1)	/* Left Coin Switch  */
PORT_BIT(0x80, IP_ACTIVE_LOW, IPT_COIN2)	/* Right Coin */

PORT_START("IN1")	/* IN1 - gamma */
PORT_BIT(0x0f, IP_ACTIVE_LOW, IPT_UNKNOWN)
PORT_BIT(0x10, IP_ACTIVE_LOW, IPT_BUTTON2 | IPF_PLAYER2)
PORT_BIT(0x20, IP_ACTIVE_LOW, IPT_BUTTON1 | IPF_PLAYER2)
PORT_BIT(0x40, IP_ACTIVE_LOW, IPT_BUTTON2)
PORT_BIT(0x80, IP_ACTIVE_LOW, IPT_BUTTON1)

PORT_START("IN2")	/* IN2 - gamma */
PORT_ANALOG(0xff, 0x00, IPT_DIAL | IPF_REVERSE, 100, 10, 0, 0, 0)

PORT_START("DIP1") /* DIP Switch at position 13/14S */
PORT_DIPNAME(0x03, 0x00, DEF_STR(Lives))
PORT_DIPSETTING(0x00, "1")
PORT_DIPSETTING(0x01, "2")
PORT_DIPSETTING(0x02, "3")
PORT_DIPSETTING(0x03, "4")
PORT_DIPNAME(0x0c, 0x00, DEF_STR(Bonus_Life))
PORT_DIPSETTING(0x0c, "50000")
PORT_DIPSETTING(0x00, "100000")
PORT_DIPSETTING(0x04, "200000")
PORT_DIPSETTING(0x08, "None")
PORT_DIPNAME(0x30, 0x00, DEF_STR(Difficulty))
PORT_DIPSETTING(0x10, "Easy")
PORT_DIPSETTING(0x00, "Medium")
PORT_DIPSETTING(0x30, "Hard")
PORT_DIPSETTING(0x20, "Demo")
PORT_DIPNAME(0xc0, 0x00, DEF_STR(Lives))
PORT_DIPSETTING(0x00, "3 (2 in Free Play)")
PORT_DIPSETTING(0xc0, "4 (3 in Free Play)")
PORT_DIPSETTING(0x80, "5 (4 in Free Play)")
PORT_DIPSETTING(0x40, "6 (5 in Free Play)")

PORT_START("DIP2") /* DIP Switch at position 8S */
PORT_DIPNAME(0x03, 0x03, DEF_STR(Coinage))
PORT_DIPSETTING(0x02, DEF_STR(2C_1C))
PORT_DIPSETTING(0x03, DEF_STR(1C_1C))
PORT_DIPSETTING(0x00, DEF_STR(1C_2C))
PORT_DIPSETTING(0x01, DEF_STR(Free_Play))
PORT_DIPNAME(0x0c, 0x0c, "Right Coin Mechanism")
PORT_DIPSETTING(0x0c, "x1")
PORT_DIPSETTING(0x08, "x4")
PORT_DIPSETTING(0x04, "x5")
PORT_DIPSETTING(0x00, "x6")
PORT_DIPNAME(0x10, 0x10, "Left Coin Mechanism")
PORT_DIPSETTING(0x10, "x1")
PORT_DIPSETTING(0x00, "x2")
PORT_DIPNAME(0xe0, 0xe0, "Bonus Credits")
PORT_DIPSETTING(0x80, "2 each 4")
PORT_DIPSETTING(0x40, "1 each 3")
PORT_DIPSETTING(0xa0, "1 each 4")
PORT_DIPSETTING(0x60, "1 each 5")
PORT_DIPSETTING(0xe0, "None")

PORT_START("IN5")	/* IN5 - dummy for player_1 = 1 on alpha */
PORT_BIT(0x3f, IP_ACTIVE_HIGH, IPT_UNUSED)
PORT_DIPNAME(0x40, 0x40, "Credit to start")
PORT_DIPSETTING(0x40, "1")
PORT_DIPSETTING(0x00, "2")
PORT_BITX(0x80, 0x80, IPT_DIPSWITCH_NAME | IPF_TOGGLE, DEF_STR(Service_Mode), OSD_KEY_F2, IP_JOY_NONE)
PORT_DIPSETTING(0x00, DEF_STR(On))
PORT_DIPSETTING(0x80, DEF_STR(Off))
INPUT_PORTS_END

INPUT_PORTS_START(alphaone)
PORT_START("IN0")	/* IN0 - alpha (player_1 = 0) */
PORT_BIT(0x03, IP_ACTIVE_HIGH, IPT_UNKNOWN)
PORT_BIT(0x7c, IP_ACTIVE_LOW, IPT_UNKNOWN)
PORT_BIT(0x80, IP_ACTIVE_LOW, IPT_BUTTON1)

PORT_START("IN1")	/* IN1 - gamma */
PORT_BIT(0x0f, IP_ACTIVE_LOW, IPT_UNKNOWN)
PORT_SERVICE(0x10, IP_ACTIVE_LOW)
PORT_BIT(0x20, IP_ACTIVE_LOW, IPT_COIN3)
PORT_BIT(0x40, IP_ACTIVE_LOW, IPT_COIN2)
PORT_BIT(0x80, IP_ACTIVE_LOW, IPT_COIN1)

PORT_START("IN2")	/* IN2 - gamma */
PORT_ANALOG(0xff, 0x00, IPT_DIAL | IPF_REVERSE, 100, 40, 0, 0, 0)
INPUT_PORTS_END

INPUT_PORTS_START(quantum)
PORT_START("IN0")	/* IN0 */
/* YHALT here MUST BE ALWAYS 0  */
PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_UNKNOWN)	/* vg YHALT */
PORT_BIT(0x02, IP_ACTIVE_LOW, IPT_COIN3)
PORT_BIT(0x04, IP_ACTIVE_LOW, IPT_START1)
PORT_BIT(0x08, IP_ACTIVE_LOW, IPT_START2)
PORT_BIT(0x10, IP_ACTIVE_LOW, IPT_COIN2)
PORT_BIT(0x20, IP_ACTIVE_LOW, IPT_COIN1)
PORT_BIT(0x40, IP_ACTIVE_LOW, IPT_UNKNOWN)
PORT_BITX(0x80, 0x80, IPT_DIPSWITCH_NAME | IPF_TOGGLE, DEF_STR(Service_Mode), OSD_KEY_F2, IP_JOY_NONE)
PORT_DIPSETTING(0x80, DEF_STR(Off))
PORT_DIPSETTING(0x00, DEF_STR(On))

/* first POKEY is SW2, second is SW1 -- more confusion! */
PORT_START("DSW0") /* DSW0 */
PORT_DIPNAME(0xc0, 0x00, DEF_STR(Coinage))
PORT_DIPSETTING(0x80, DEF_STR(2C_1C))
PORT_DIPSETTING(0x00, DEF_STR(1C_1C))
PORT_DIPSETTING(0xc0, DEF_STR(1C_2C))
PORT_DIPSETTING(0x40, DEF_STR(Free_Play))
PORT_DIPNAME(0x30, 0x00, "Right Coin")
PORT_DIPSETTING(0x00, "*1")
PORT_DIPSETTING(0x20, "*4")
PORT_DIPSETTING(0x10, "*5")
PORT_DIPSETTING(0x30, "*6")
PORT_DIPNAME(0x08, 0x00, "Left Coin")
PORT_DIPSETTING(0x00, "*1")
PORT_DIPSETTING(0x08, "*2")
PORT_DIPNAME(0x07, 0x00, "Bonus Coins")
PORT_DIPSETTING(0x00, "None")
PORT_DIPSETTING(0x01, "1 each 5")
PORT_DIPSETTING(0x02, "1 each 4")
PORT_DIPSETTING(0x05, "1 each 3")
PORT_DIPSETTING(0x06, "2 each 4")
PORT_START("DSW1") /* DSW1 */
PORT_BIT(0xff, IP_ACTIVE_HIGH, IPT_UNKNOWN)
/*
		PORT_START("IN2")     // IN2
		PORT_ANALOG(0x0f, 0, IPT_TRACKBALL_Y | IPF_REVERSE, 20, 10, 7, 0, 0)
		PORT_START("IN3")      // IN3
		PORT_ANALOG(0x0f, 0, IPT_TRACKBALL_X, 20, 10, 7, 0, 0)
		INPUT_PORTS_END
		*/

	PORT_START("IN2")     // IN2
	PORT_ANALOG(0x0f, 0, IPT_TRACKBALL_X | IPF_REVERSE, 20, 10, 7, 0, 0)
	PORT_START("IN3")      // IN3
	PORT_ANALOG(0x0f, 0, IPT_TRACKBALL_Y, 20, 10, 7, 0, 0)
	INPUT_PORTS_END


	/***************************************************************************

		 Spacewar

	***************************************************************************/

	INPUT_PORTS_START(spacewar)
	PORT_START("IN0") /* switches */
	PORT_DIPNAME(0x03, 0x00, "Time")
	PORT_DIPSETTING(0x03, "0:45/coin")
	PORT_DIPSETTING(0x00, "1:00/coin")
	PORT_DIPSETTING(0x01, "1:30/coin")
	PORT_DIPSETTING(0x02, "2:00/coin")
	PORT_BIT(0x04, IP_ACTIVE_LOW, IPT_BUTTON1 | IPF_PLAYER2)
	PORT_BIT(0x08, IP_ACTIVE_LOW, IPT_BUTTON3 | IPF_PLAYER2)
	PORT_BIT(0x10, IP_ACTIVE_LOW, IPT_BUTTON1 | IPF_PLAYER1)
	PORT_BIT(0x20, IP_ACTIVE_LOW, IPT_BUTTON3 | IPF_PLAYER1)
	PORT_DIPNAME(0x40, 0x40, DEF_STR(Unknown))
	PORT_DIPSETTING(0x40, DEF_STR(Off))
	PORT_DIPSETTING(0x00, DEF_STR(On))
	PORT_BIT(0x80, IP_ACTIVE_LOW, IPT_COIN1)

	PORT_START("INPUTS") /* inputs high */
	PORT_BIT(0x8000, IP_ACTIVE_LOW, IPT_BUTTON2 | IPF_PLAYER1)
	PORT_BIT(0x4000, IP_ACTIVE_LOW, IPT_JOYSTICK_LEFT | IPF_2WAY | IPF_PLAYER2)
	PORT_BIT(0x2000, IP_ACTIVE_LOW, IPT_JOYSTICK_RIGHT | IPF_2WAY | IPF_PLAYER1)
	PORT_BIT(0x1000, IP_ACTIVE_LOW, IPT_JOYSTICK_RIGHT | IPF_2WAY | IPF_PLAYER2)
	PORT_BITX(0x0800, IP_ACTIVE_LOW, 0, "Option 0", OSD_KEY_0_PAD, IP_JOY_NONE)
	PORT_BITX(0x0400, IP_ACTIVE_LOW, 0, "Option 5", OSD_KEY_5_PAD, IP_JOY_NONE)
	PORT_BIT(0x0200, IP_ACTIVE_LOW, IPT_BUTTON2 | IPF_PLAYER2)
	PORT_BIT(0x0100, IP_ACTIVE_LOW, IPT_JOYSTICK_LEFT | IPF_2WAY | IPF_PLAYER1)
	PORT_BITX(0x0080, IP_ACTIVE_LOW, 0, "Option 7", OSD_KEY_7_PAD, IP_JOY_NONE)
	PORT_BITX(0x0040, IP_ACTIVE_LOW, 0, "Option 2", OSD_KEY_2_PAD, IP_JOY_NONE)
	PORT_BITX(0x0020, IP_ACTIVE_LOW, 0, "Option 6", OSD_KEY_6_PAD, IP_JOY_NONE)
	PORT_BITX(0x0010, IP_ACTIVE_LOW, 0, "Option 1", OSD_KEY_1_PAD, IP_JOY_NONE)
	PORT_BITX(0x0008, IP_ACTIVE_LOW, 0, "Option 9", OSD_KEY_9_PAD, IP_JOY_NONE)
	PORT_BITX(0x0004, IP_ACTIVE_LOW, 0, "Option 4", OSD_KEY_4_PAD, IP_JOY_NONE)
	PORT_BITX(0x0002, IP_ACTIVE_LOW, 0, "Option 8", OSD_KEY_8_PAD, IP_JOY_NONE)
	PORT_BITX(0x0001, IP_ACTIVE_LOW, 0, "Option 3", OSD_KEY_3_PAD, IP_JOY_NONE)


	PORT_START("IN2") /* joystick X */
	PORT_BIT(0xff, IP_ACTIVE_LOW, IPT_UNUSED)

	PORT_START("IN3") /* joystick Y */
	PORT_BIT(0xff, IP_ACTIVE_LOW, IPT_UNUSED)
	INPUT_PORTS_END


	/***************************************************************************

		  Barrier

	***************************************************************************/

	INPUT_PORTS_START(barrier)
	PORT_START("IN0") /* switches */
	PORT_DIPNAME(0x01, 0x00, DEF_STR(Lives))
	PORT_DIPSETTING(0x00, "3")
	PORT_DIPSETTING(0x01, "5")
	PORT_DIPNAME(0x02, 0x02, DEF_STR(Demo_Sounds))
	PORT_DIPSETTING(0x00, DEF_STR(Off))
	PORT_DIPSETTING(0x02, DEF_STR(On))
	PORT_DIPNAME(0x04, 0x04, DEF_STR(Unknown))
	PORT_DIPSETTING(0x04, DEF_STR(Off))
	PORT_DIPSETTING(0x00, DEF_STR(On))
	PORT_DIPNAME(0x08, 0x08, DEF_STR(Unknown))
	PORT_DIPSETTING(0x08, DEF_STR(Off))
	PORT_DIPSETTING(0x00, DEF_STR(On))
	PORT_DIPNAME(0x10, 0x10, DEF_STR(Unknown))
	PORT_DIPSETTING(0x10, DEF_STR(Off))
	PORT_DIPSETTING(0x00, DEF_STR(On))
	PORT_DIPNAME(0x20, 0x20, DEF_STR(Unknown))
	PORT_DIPSETTING(0x20, DEF_STR(Off))
	PORT_DIPSETTING(0x00, DEF_STR(On))
	PORT_DIPNAME(0x40, 0x40, DEF_STR(Unknown))
	PORT_DIPSETTING(0x40, DEF_STR(Off))
	PORT_DIPSETTING(0x00, DEF_STR(On))
	PORT_BIT(0x80, IP_ACTIVE_LOW, IPT_COIN1)

	PORT_START("INPUTS") /* inputs */
	PORT_BITX(0x0001, IP_ACTIVE_LOW, 0, "Skill A", OSD_KEY_A, IP_JOY_NONE)
	PORT_BIT(0x0002, IP_ACTIVE_LOW, IPT_UNUSED)
	PORT_BITX(0x0004, IP_ACTIVE_LOW, 0, "Skill B", OSD_KEY_B, IP_JOY_NONE)
	PORT_BIT(0x0008, IP_ACTIVE_LOW, IPT_JOYSTICK_DOWN | IPF_4WAY | IPF_PLAYER1)
	PORT_BIT(0x0010, IP_ACTIVE_LOW, IPT_START2)
	PORT_BIT(0x0020, IP_ACTIVE_LOW, IPT_UNUSED)
	PORT_BITX(0x0040, IP_ACTIVE_LOW, 0, "Skill C", OSD_KEY_C, IP_JOY_NONE)
	PORT_BIT(0x0080, IP_ACTIVE_LOW, IPT_UNUSED)
	PORT_BIT(0x0100, IP_ACTIVE_LOW, IPT_JOYSTICK_LEFT | IPF_4WAY | IPF_PLAYER2)
	PORT_BIT(0x0200, IP_ACTIVE_LOW, IPT_JOYSTICK_RIGHT | IPF_4WAY | IPF_PLAYER1)
	PORT_BIT(0x0400, IP_ACTIVE_LOW, IPT_JOYSTICK_DOWN | IPF_4WAY | IPF_PLAYER2)
	PORT_BIT(0x0800, IP_ACTIVE_LOW, IPT_START1)
	PORT_BIT(0x1000, IP_ACTIVE_LOW, IPT_JOYSTICK_UP | IPF_4WAY | IPF_PLAYER1)
	PORT_BIT(0x2000, IP_ACTIVE_LOW, IPT_JOYSTICK_UP | IPF_4WAY | IPF_PLAYER2)
	PORT_BIT(0x4000, IP_ACTIVE_LOW, IPT_JOYSTICK_LEFT | IPF_4WAY | IPF_PLAYER1)
	PORT_BIT(0x8000, IP_ACTIVE_LOW, IPT_JOYSTICK_RIGHT | IPF_4WAY | IPF_PLAYER2)

	PORT_START("IN2") /* analog stick X - unused */
	PORT_BIT(0xff, IP_ACTIVE_LOW, IPT_UNUSED)

	PORT_START("IN3") /* analog stick Y - unused */
	PORT_BIT(0xff, IP_ACTIVE_LOW, IPT_UNUSED)
	INPUT_PORTS_END

	/***************************************************************************

	  Star Hawk

	***************************************************************************/

	/* TODO: 4way or 8way stick? */
	INPUT_PORTS_START(starhawk)
	PORT_START("SWITCHES")
	PORT_DIPNAME(0x03, 0x03, DEF_STR(Game_Time))
	PORT_DIPSETTING(0x03, "2:00/4:00")
	PORT_DIPSETTING(0x01, "1:30/3:00")
	PORT_DIPSETTING(0x02, "1:00/2:00")
	PORT_DIPSETTING(0x00, "0:45/1:30")
	PORT_BIT(0x04, IP_ACTIVE_LOW, IPT_START1)
	PORT_BIT(0x08, IP_ACTIVE_LOW, IPT_BUTTON1 | IPF_PLAYER2)
	PORT_BIT(0x10, IP_ACTIVE_LOW, IPT_START2)
	PORT_BIT(0x20, IP_ACTIVE_LOW, IPT_BUTTON1 | IPF_PLAYER1)
	PORT_DIPNAME(0x40, 0x40, DEF_STR(Unknown))
	PORT_DIPSETTING(0x40, DEF_STR(Off))
	PORT_DIPSETTING(0x00, DEF_STR(On))
	PORT_BIT(0x80, IP_ACTIVE_LOW, IPT_COIN1)

	PORT_START("INPUTS") /* input */
	PORT_BIT(0x8000, IP_ACTIVE_LOW, IPT_BUTTON4 | IPF_PLAYER2)
	PORT_BIT(0x4000, IP_ACTIVE_LOW, IPT_BUTTON2 | IPF_PLAYER1)
	PORT_BIT(0x2000, IP_ACTIVE_LOW, IPT_BUTTON3 | IPF_PLAYER2)
	PORT_BIT(0x1000, IP_ACTIVE_LOW, IPT_BUTTON3 | IPF_PLAYER1)
	PORT_BIT(0x0800, IP_ACTIVE_LOW, IPT_JOYSTICK_UP | IPF_8WAY | IPF_PLAYER2)
	PORT_BIT(0x0400, IP_ACTIVE_LOW, IPT_JOYSTICK_LEFT | IPF_8WAY | IPF_PLAYER2)
	PORT_BIT(0x0200, IP_ACTIVE_LOW, IPT_BUTTON4 | IPF_PLAYER1)
	PORT_BIT(0x0100, IP_ACTIVE_LOW, IPT_BUTTON2 | IPF_PLAYER2)
	PORT_BIT(0x0080, IP_ACTIVE_LOW, IPT_UNUSED)
	PORT_BIT(0x0040, IP_ACTIVE_LOW, IPT_UNUSED)
	PORT_BIT(0x0020, IP_ACTIVE_LOW, IPT_JOYSTICK_DOWN | IPF_8WAY | IPF_PLAYER2)
	PORT_BIT(0x0010, IP_ACTIVE_LOW, IPT_JOYSTICK_RIGHT | IPF_8WAY | IPF_PLAYER2)
	PORT_BIT(0x0008, IP_ACTIVE_LOW, IPT_JOYSTICK_DOWN | IPF_8WAY | IPF_PLAYER1)
	PORT_BIT(0x0004, IP_ACTIVE_LOW, IPT_JOYSTICK_RIGHT | IPF_8WAY | IPF_PLAYER1)
	PORT_BIT(0x0002, IP_ACTIVE_LOW, IPT_JOYSTICK_LEFT | IPF_8WAY | IPF_PLAYER1)
	PORT_BIT(0x0001, IP_ACTIVE_LOW, IPT_JOYSTICK_UP | IPF_8WAY | IPF_PLAYER1)

	PORT_START("IN2") /* analog stick X - unused */
	PORT_BIT(0xff, IP_ACTIVE_LOW, IPT_UNUSED)

	PORT_START("IN3") /* analog stick Y - unused */
	PORT_BIT(0xff, IP_ACTIVE_LOW, IPT_UNUSED)
	INPUT_PORTS_END

	/***************************************************************************

	  Star Castle

	***************************************************************************/

	INPUT_PORTS_START(starcas)

	PORT_START("SWITCHES")
	PORT_DIPNAME(0x03, 0x03, DEF_STR(Lives))
	PORT_DIPSETTING(0x03, "3")
	PORT_DIPSETTING(0x01, "4")
	PORT_DIPSETTING(0x02, "5")
	PORT_DIPSETTING(0x00, "6")
	PORT_DIPNAME(0x0c, 0x0c, DEF_STR(Coinage))
	PORT_DIPSETTING(0x04, DEF_STR(2C_1C))
	PORT_DIPSETTING(0x00, DEF_STR(4C_3C))
	PORT_DIPSETTING(0x0c, DEF_STR(1C_1C))
	PORT_DIPSETTING(0x08, DEF_STR(2C_3C))
	PORT_DIPNAME(0x10, 0x10, DEF_STR(Unknown))
	PORT_DIPSETTING(0x10, DEF_STR(Off))
	PORT_DIPSETTING(0x00, DEF_STR(On))
	PORT_DIPNAME(0x20, 0x20, DEF_STR(Unknown))
	PORT_DIPSETTING(0x20, DEF_STR(Off))
	PORT_DIPSETTING(0x00, DEF_STR(On))
	PORT_SERVICE(0x40, IP_ACTIVE_HIGH)
	PORT_BIT(0x80, IP_ACTIVE_LOW, IPT_COIN1)

	PORT_START("INPUTS")
	PORT_BIT(0x0001, IP_ACTIVE_LOW, IPT_START1)
	PORT_BIT(0x0002, IP_ACTIVE_LOW, IPT_UNUSED)
	PORT_BIT(0x0004, IP_ACTIVE_LOW, IPT_START2)
	PORT_BIT(0x0038, IP_ACTIVE_LOW, IPT_UNUSED)
	PORT_BIT(0x0040, IP_ACTIVE_LOW, IPT_JOYSTICK_LEFT | IPF_2WAY)
	PORT_BIT(0x0080, IP_ACTIVE_LOW, IPT_UNUSED)
	PORT_BIT(0x0100, IP_ACTIVE_LOW, IPT_JOYSTICK_RIGHT | IPF_2WAY)
	PORT_BIT(0x0200, IP_ACTIVE_LOW, IPT_UNUSED)
	PORT_BIT(0x0400, IP_ACTIVE_LOW, IPT_BUTTON2)
	PORT_BIT(0x0800, IP_ACTIVE_LOW, IPT_UNUSED)
	PORT_BIT(0x1000, IP_ACTIVE_LOW, IPT_BUTTON1)
	PORT_BIT(0xe000, IP_ACTIVE_LOW, IPT_UNUSED)


	PORT_START("IN2") /* analog stick X - unused */
	PORT_BIT(0xff, IP_ACTIVE_LOW, IPT_UNUSED)

	PORT_START("IN3") /* analog stick Y - unused */
	PORT_BIT(0xff, IP_ACTIVE_LOW, IPT_UNUSED)
	INPUT_PORTS_END

	/***************************************************************************

	  Tailgunner

	***************************************************************************/

	INPUT_PORTS_START(tailg)

	PORT_START("SWITCHES")
	PORT_DIPNAME(0x23, 0x23, "Shield Points")
	PORT_DIPSETTING(0x00, "15")
	PORT_DIPSETTING(0x02, "20")
	PORT_DIPSETTING(0x01, "30")
	PORT_DIPSETTING(0x03, "40")
	PORT_DIPSETTING(0x20, "50")
	PORT_DIPSETTING(0x22, "60")
	PORT_DIPSETTING(0x21, "70")
	PORT_DIPSETTING(0x23, "80")
	PORT_DIPNAME(0x04, 0x04, DEF_STR(Coinage))
	PORT_DIPSETTING(0x00, DEF_STR(2C_1C))
	PORT_DIPSETTING(0x04, DEF_STR(1C_1C))
	PORT_DIPNAME(0x08, 0x08, DEF_STR(Unknown))
	PORT_DIPSETTING(0x08, DEF_STR(Off))
	PORT_DIPSETTING(0x00, DEF_STR(On))
	PORT_DIPNAME(0x10, 0x10, DEF_STR(Unknown))
	PORT_DIPSETTING(0x10, DEF_STR(Off))
	PORT_DIPSETTING(0x00, DEF_STR(On))
	PORT_DIPNAME(0x40, 0x40, DEF_STR(Unknown))
	PORT_DIPSETTING(0x40, DEF_STR(Off))
	PORT_DIPSETTING(0x00, DEF_STR(On))
	PORT_BIT(0x80, IP_ACTIVE_LOW, IPT_COIN1)

	PORT_START("INPUTS")
	PORT_BIT(0x001f, IP_ACTIVE_LOW, IPT_UNUSED)
	PORT_BIT(0x0020, IP_ACTIVE_LOW, IPT_BUTTON1)
	PORT_BIT(0x0040, IP_ACTIVE_LOW, IPT_BUTTON2)
	PORT_BIT(0x0080, IP_ACTIVE_LOW, IPT_START1)
	PORT_BIT(0xff00, IP_ACTIVE_LOW, IPT_UNUSED)

	PORT_START("ANALOGX") /* analog stick X */
	PORT_ANALOG(0xff, 0x80, IPT_AD_STICK_X, 100, 5, 0, 0x20, 0xe0)

	PORT_START("ANALOGY")/* analog stick Y */
	PORT_ANALOG(0xff, 0x80, IPT_AD_STICK_Y, 100, 5, 0, 0x20, 0xe0)

	INPUT_PORTS_END

	/***************************************************************************

	  Ripoff - Input fixed

	***************************************************************************/

	INPUT_PORTS_START(ripoff)
	PORT_START("IN0") /* switches */
	PORT_DIPNAME(0x03, 0x03, DEF_STR(Lives))
	PORT_DIPSETTING(0x01, "4")
	PORT_DIPSETTING(0x03, "8")
	PORT_DIPSETTING(0x00, "12")
	PORT_DIPSETTING(0x02, "16")
	PORT_DIPNAME(0x0c, 0x00, DEF_STR(Coinage))
	PORT_DIPSETTING(0x04, DEF_STR(2C_1C))
	PORT_DIPSETTING(0x0c, DEF_STR(4C_3C))
	PORT_DIPSETTING(0x00, DEF_STR(1C_1C))
	PORT_DIPSETTING(0x08, DEF_STR(2C_3C))
	PORT_DIPNAME(0x10, 0x10, DEF_STR(Demo_Sounds))
	PORT_DIPSETTING(0x00, DEF_STR(Off))
	PORT_DIPSETTING(0x10, DEF_STR(On))
	PORT_DIPNAME(0x20, 0x00, "Scores")
	PORT_DIPSETTING(0x00, "Individual")
	PORT_DIPSETTING(0x20, "Combined")
	PORT_SERVICE(0x40, IP_ACTIVE_LOW)
	PORT_BIT(0x80, IP_ACTIVE_LOW, IPT_COIN1)

	PORT_START("INPUTS") /* inputs */
	PORT_BIT(0x8000, IP_ACTIVE_LOW, IPT_BUTTON2 | IPF_PLAYER1)
	PORT_BIT(0x4000, IP_ACTIVE_LOW, IPT_JOYSTICK_RIGHT | IPF_2WAY | IPF_PLAYER1)
	PORT_BIT(0x2000, IP_ACTIVE_LOW, IPT_BUTTON1 | IPF_PLAYER1)
	PORT_BIT(0x1000, IP_ACTIVE_LOW, IPT_JOYSTICK_LEFT | IPF_2WAY | IPF_PLAYER1)
	PORT_BIT(0x0800, IP_ACTIVE_LOW, IPT_UNUSED)
	PORT_BIT(0x0400, IP_ACTIVE_LOW, IPT_UNUSED)
	PORT_BIT(0x0200, IP_ACTIVE_LOW, IPT_UNUSED)
	PORT_BIT(0x0100, IP_ACTIVE_LOW, IPT_UNUSED)
	PORT_BIT(0x0080, IP_ACTIVE_LOW, IPT_UNUSED)
	PORT_BIT(0x0040, IP_ACTIVE_LOW, IPT_UNUSED)
	PORT_BIT(0x0020, IP_ACTIVE_LOW, IPT_BUTTON1 | IPF_PLAYER2)
	PORT_BIT(0x0010, IP_ACTIVE_LOW, IPT_BUTTON2 | IPF_PLAYER2)
	PORT_BIT(0x0008, IP_ACTIVE_LOW, IPT_START2)
	PORT_BIT(0x0004, IP_ACTIVE_LOW, IPT_JOYSTICK_RIGHT | IPF_2WAY | IPF_PLAYER2)
	PORT_BIT(0x0002, IP_ACTIVE_LOW, IPT_START1)
	PORT_BIT(0x0001, IP_ACTIVE_LOW, IPT_JOYSTICK_LEFT | IPF_2WAY | IPF_PLAYER2)

	PORT_START("IN2") /* analog stick X - unused */
	PORT_BIT(0xff, IP_ACTIVE_LOW, IPT_UNUSED)

	PORT_START("IN3")/* analog stick Y - unused */
	PORT_BIT(0xff, IP_ACTIVE_LOW, IPT_UNUSED)
	INPUT_PORTS_END

	INPUT_PORTS_START(speedfrk)
	PORT_START("SWITCHES")
	PORT_DIPNAME(0x03, 0x02, "Extra Time")
	PORT_DIPSETTING(0x00, "69")
	PORT_DIPSETTING(0x01, "99")
	PORT_DIPSETTING(0x02, "129")
	PORT_DIPSETTING(0x03, "159")
	PORT_DIPNAME(0x04, 0x04, DEF_STR(Unknown))
	PORT_DIPSETTING(0x04, DEF_STR(Off))
	PORT_DIPSETTING(0x00, DEF_STR(On))
	PORT_DIPNAME(0x08, 0x08, DEF_STR(Unknown))
	PORT_DIPSETTING(0x08, DEF_STR(Off))
	PORT_DIPSETTING(0x00, DEF_STR(On))
	PORT_DIPNAME(0x10, 0x10, DEF_STR(Unknown))
	PORT_DIPSETTING(0x10, DEF_STR(Off))
	PORT_DIPSETTING(0x00, DEF_STR(On))
	PORT_DIPNAME(0x20, 0x20, DEF_STR(Unknown))
	PORT_DIPSETTING(0x20, DEF_STR(Off))
	PORT_DIPSETTING(0x00, DEF_STR(On))
	PORT_DIPNAME(0x40, 0x40, DEF_STR(Unknown))
	PORT_DIPSETTING(0x40, DEF_STR(Off))
	PORT_DIPSETTING(0x00, DEF_STR(On))
	PORT_BIT(0x80, IP_ACTIVE_LOW, IPT_COIN1)

	PORT_START("INPUTS") /* inputs */
	PORT_BIT(0x8000, IP_ACTIVE_LOW, IPT_UNUSED)
	PORT_BIT(0x4000, IP_ACTIVE_LOW, IPT_UNUSED)
	PORT_BIT(0x2000, IP_ACTIVE_LOW, IPT_UNUSED)
	PORT_BIT(0x1000, IP_ACTIVE_LOW, IPT_UNUSED)
	PORT_BIT(0x0800, IP_ACTIVE_LOW, IPT_UNUSED)
	PORT_BIT(0x0400, IP_ACTIVE_LOW, IPT_UNUSED)
	PORT_BIT(0x0200, IP_ACTIVE_LOW, IPT_UNUSED)
	PORT_BIT(0x0100, IP_ACTIVE_LOW, IPT_BUTTON1 | IPF_PLAYER1) /* gas */
	PORT_BIT(0x0080, IP_ACTIVE_LOW, IPT_START1)
	PORT_BIT(0x0070, IP_ACTIVE_LOW, IPT_UNUSED) /* gear shift, fake below */
	PORT_BIT(0x000f, IP_ACTIVE_LOW, IPT_UNUSED) /* steering wheel, fake below */

	PORT_START("WHEEL")/* fake - steering wheel (in4) */
	PORT_ANALOG(0xff, 0x00, IPT_DIAL, 100, 1, 0, 0x00, 0xff)

	PORT_START("GEAR") /* fake - gear shift (in5) */
	PORT_BIT(0x0f, IP_ACTIVE_HIGH, IPT_UNUSED)
	PORT_BITX(0x10, IP_ACTIVE_LOW, IPT_JOYSTICK_DOWN | IPF_PLAYER2, "1st gear", IP_KEY_DEFAULT, IP_JOY_DEFAULT)
	PORT_BITX(0x20, IP_ACTIVE_LOW, IPT_JOYSTICK_LEFT | IPF_PLAYER2, "2nd gear", IP_KEY_DEFAULT, IP_JOY_DEFAULT)
	PORT_BITX(0x40, IP_ACTIVE_LOW, IPT_JOYSTICK_RIGHT | IPF_PLAYER2, "3rd gear", IP_KEY_DEFAULT, IP_JOY_DEFAULT)
	PORT_BITX(0x80, IP_ACTIVE_LOW, IPT_JOYSTICK_UP | IPF_PLAYER2, "4th gear", IP_KEY_DEFAULT, IP_JOY_DEFAULT)
	INPUT_PORTS_END



	/***************************************************************************

	  Sundance

	***************************************************************************/

	INPUT_PORTS_START(sundance)
	PORT_START("SWITCHES")
	PORT_DIPNAME(0x03, 0x02, "Time")
	PORT_DIPSETTING(0x00, "0:45/coin")
	PORT_DIPSETTING(0x02, "1:00/coin")
	PORT_DIPSETTING(0x01, "1:30/coin")
	PORT_DIPSETTING(0x03, "2:00/coin")
	PORT_DIPNAME(0x04, 0x00, DEF_STR(Language))
	PORT_DIPSETTING(0x04, DEF_STR(Japanese))
	PORT_DIPSETTING(0x00, DEF_STR(English))
	PORT_DIPNAME(0x08, 0x08, DEF_STR(Coinage)) // supposedly coinage, doesn't work
	PORT_DIPSETTING(0x08, "1 coin/2 players")
	PORT_DIPSETTING(0x00, "2 coins/2 players")
	PORT_DIPNAME(0x10, 0x10, DEF_STR(Unknown))
	PORT_DIPSETTING(0x10, DEF_STR(Off))
	PORT_DIPSETTING(0x00, DEF_STR(On))
	PORT_DIPNAME(0x20, 0x20, DEF_STR(Unknown))
	PORT_DIPSETTING(0x20, DEF_STR(Off))
	PORT_DIPSETTING(0x00, DEF_STR(On))
	PORT_DIPNAME(0x40, 0x40, DEF_STR(Unknown))
	PORT_DIPSETTING(0x40, DEF_STR(Off))
	PORT_DIPSETTING(0x00, DEF_STR(On))
	PORT_BIT(0x80, IP_ACTIVE_LOW, IPT_COIN1)

	PORT_START("INPUTS") /* inputs */
	PORT_BIT(0x8000, IP_ACTIVE_LOW, IPT_UNUSED) /* player 1 motion */
	PORT_BIT(0x4000, IP_ACTIVE_LOW, IPT_UNUSED) /* player 2 motion */
	PORT_BIT(0x2000, IP_ACTIVE_LOW, IPT_UNUSED) /* player 1 motion */
	PORT_BIT(0x1000, IP_ACTIVE_LOW, IPT_UNUSED) /* player 2 motion */
	PORT_BIT(0x0800, IP_ACTIVE_LOW, IPT_UNUSED) /* 2 suns */
	PORT_BIT(0x0400, IP_ACTIVE_LOW, IPT_UNUSED) /* player 1 motion */
	PORT_BIT(0x0200, IP_ACTIVE_LOW, IPT_UNUSED) /* player 2 motion */
	PORT_BIT(0x0100, IP_ACTIVE_LOW, IPT_UNUSED) /* player 1 motion */
	PORT_BIT(0x0080, IP_ACTIVE_LOW, IPT_BUTTON1 | IPF_PLAYER1)
	PORT_BIT(0x0040, IP_ACTIVE_LOW, IPT_UNUSED) /* 4 suns */
	PORT_BIT(0x0020, IP_ACTIVE_LOW, IPT_UNUSED) /* Grid */
	PORT_BIT(0x0010, IP_ACTIVE_LOW, IPT_UNUSED) /* 3 suns */
	PORT_BIT(0x0008, IP_ACTIVE_LOW, IPT_START2)
	PORT_BIT(0x0004, IP_ACTIVE_LOW, IPT_START1)
	PORT_BIT(0x0002, IP_ACTIVE_LOW, IPT_BUTTON1 | IPF_PLAYER2)
	PORT_BIT(0x0001, IP_ACTIVE_LOW, IPT_UNUSED) /* player 2 motion */

	PORT_START("PAD1")
	PORT_BITX(0x0001, IP_ACTIVE_HIGH, IPT_BUTTON1 | IPF_PLAYER1, "P1 Pad 1", OSD_KEY_7_PAD, IP_JOY_NONE)
	PORT_BITX(0x0002, IP_ACTIVE_HIGH, IPT_BUTTON2 | IPF_PLAYER1, "P1 Pad 2", OSD_KEY_8_PAD, IP_JOY_NONE)
	PORT_BITX(0x0004, IP_ACTIVE_HIGH, IPT_BUTTON3 | IPF_PLAYER1, "P1 Pad 3", OSD_KEY_9_PAD, IP_JOY_NONE)
	PORT_BITX(0x0008, IP_ACTIVE_HIGH, IPT_BUTTON4 | IPF_PLAYER1, "P1 Pad 4", OSD_KEY_4_PAD, IP_JOY_NONE)
	PORT_BITX(0x0010, IP_ACTIVE_HIGH, IPT_BUTTON5 | IPF_PLAYER1, "P1 Pad 5", OSD_KEY_5_PAD, IP_JOY_NONE)
	PORT_BITX(0x0020, IP_ACTIVE_HIGH, IPT_BUTTON6 | IPF_PLAYER1, "P1 Pad 6", OSD_KEY_6_PAD, IP_JOY_NONE)
	PORT_BITX(0x0040, IP_ACTIVE_HIGH, IPT_BUTTON7 | IPF_PLAYER1, "P1 Pad 7", OSD_KEY_1_PAD, IP_JOY_NONE)
	PORT_BITX(0x0080, IP_ACTIVE_HIGH, IPT_BUTTON8 | IPF_PLAYER1, "P1 Pad 8", OSD_KEY_2_PAD, IP_JOY_NONE)
	PORT_BITX(0x0100, IP_ACTIVE_HIGH, IPT_BUTTON9 | IPF_PLAYER1, "P1 Pad 9", OSD_KEY_3_PAD, IP_JOY_NONE)

	PORT_START("PAD2")
	PORT_BITX(0x0001, IP_ACTIVE_HIGH, IPT_BUTTON1 | IPF_PLAYER2, "P2 Pad 1", OSD_KEY_Q, IP_JOY_NONE)
	PORT_BITX(0x0002, IP_ACTIVE_HIGH, IPT_BUTTON2 | IPF_PLAYER2, "P2 Pad 2", OSD_KEY_W, IP_JOY_NONE)
	PORT_BITX(0x0004, IP_ACTIVE_HIGH, IPT_BUTTON3 | IPF_PLAYER2, "P2 Pad 3", OSD_KEY_E, IP_JOY_NONE)
	PORT_BITX(0x0008, IP_ACTIVE_HIGH, IPT_BUTTON4 | IPF_PLAYER2, "P2 Pad 4", OSD_KEY_A, IP_JOY_NONE)
	PORT_BITX(0x0010, IP_ACTIVE_HIGH, IPT_BUTTON5 | IPF_PLAYER2, "P2 Pad 5", OSD_KEY_S, IP_JOY_NONE)
	PORT_BITX(0x0020, IP_ACTIVE_HIGH, IPT_BUTTON6 | IPF_PLAYER2, "P2 Pad 6", OSD_KEY_D, IP_JOY_NONE)
	PORT_BITX(0x0040, IP_ACTIVE_HIGH, IPT_BUTTON7 | IPF_PLAYER2, "P2 Pad 7", OSD_KEY_Z, IP_JOY_NONE)
	PORT_BITX(0x0080, IP_ACTIVE_HIGH, IPT_BUTTON8 | IPF_PLAYER2, "P2 Pad 8", OSD_KEY_X, IP_JOY_NONE)
	PORT_BITX(0x0100, IP_ACTIVE_HIGH, IPT_BUTTON9 | IPF_PLAYER2, "P2 Pad 9", OSD_KEY_C, IP_JOY_NONE)

	INPUT_PORTS_END

	/***************************************************************************

	  Warrior

	***************************************************************************/

	INPUT_PORTS_START(warrior)

	PORT_START("SWITCHES")
	PORT_DIPNAME(0x01, 0x01, DEF_STR(Unknown))
	PORT_DIPSETTING(0x01, DEF_STR(Off))
	PORT_DIPSETTING(0x00, DEF_STR(On))
	PORT_DIPNAME(0x02, 0x02, DEF_STR(Unknown))
	PORT_DIPSETTING(0x02, DEF_STR(Off))
	PORT_DIPSETTING(0x00, DEF_STR(On))
	PORT_SERVICE(0x04, IP_ACTIVE_HIGH)
	PORT_DIPNAME(0x08, 0x08, DEF_STR(Unknown))
	PORT_DIPSETTING(0x08, DEF_STR(Off))
	PORT_DIPSETTING(0x00, DEF_STR(On))
	PORT_DIPNAME(0x10, 0x10, DEF_STR(Unknown))
	PORT_DIPSETTING(0x10, DEF_STR(Off))
	PORT_DIPSETTING(0x00, DEF_STR(On))
	PORT_DIPNAME(0x20, 0x20, DEF_STR(Unknown))
	PORT_DIPSETTING(0x20, DEF_STR(Off))
	PORT_DIPSETTING(0x00, DEF_STR(On))
	PORT_DIPNAME(0x40, 0x40, DEF_STR(Unknown))
	PORT_DIPSETTING(0x40, DEF_STR(Off))
	PORT_DIPSETTING(0x00, DEF_STR(On))
	PORT_BIT(0x80, IP_ACTIVE_LOW, IPT_COIN1)

	PORT_START("INPUTS") /* inputs */
	PORT_BIT(0x8000, IP_ACTIVE_LOW, IPT_UNKNOWN)
	PORT_BIT(0x4000, IP_ACTIVE_LOW, IPT_START1)
	PORT_BIT(0x2000, IP_ACTIVE_LOW, IPT_START2)
	PORT_BIT(0x1000, IP_ACTIVE_LOW, IPT_BUTTON1 | IPF_PLAYER1)
	PORT_BIT(0x0800, IP_ACTIVE_LOW, IPT_JOYSTICK_DOWN | IPF_PLAYER1)
	PORT_BIT(0x0400, IP_ACTIVE_LOW, IPT_JOYSTICK_UP | IPF_PLAYER1)
	PORT_BIT(0x0200, IP_ACTIVE_LOW, IPT_JOYSTICK_LEFT | IPF_PLAYER1)
	PORT_BIT(0x0100, IP_ACTIVE_LOW, IPT_JOYSTICK_RIGHT | IPF_PLAYER1)
	PORT_BIT(0x0080, IP_ACTIVE_LOW, IPT_UNKNOWN)
	PORT_BIT(0x0040, IP_ACTIVE_LOW, IPT_UNKNOWN)
	PORT_BIT(0x0020, IP_ACTIVE_LOW, IPT_UNKNOWN)
	PORT_BIT(0x0010, IP_ACTIVE_LOW, IPT_BUTTON1 | IPF_PLAYER2)
	PORT_BIT(0x0008, IP_ACTIVE_LOW, IPT_JOYSTICK_DOWN | IPF_PLAYER2)
	PORT_BIT(0x0004, IP_ACTIVE_LOW, IPT_JOYSTICK_UP | IPF_PLAYER2)
	PORT_BIT(0x0002, IP_ACTIVE_LOW, IPT_JOYSTICK_LEFT | IPF_PLAYER2)
	PORT_BIT(0x0001, IP_ACTIVE_LOW, IPT_JOYSTICK_RIGHT | IPF_PLAYER2)

	PORT_START("IN2") /* analog stick X - unused */
	PORT_BIT(0xff, IP_ACTIVE_LOW, IPT_UNUSED)

	PORT_START("IN3") /* analog stick Y - unused */
	PORT_BIT(0xff, IP_ACTIVE_LOW, IPT_UNUSED)
	INPUT_PORTS_END

	/***************************************************************************

	  Armor Attack

	***************************************************************************/

	INPUT_PORTS_START(armora)
	PORT_START("SWITCHES")
	PORT_DIPNAME(0x03, 0x03, DEF_STR(Lives))
	PORT_DIPSETTING(0x00, "2")
	PORT_DIPSETTING(0x02, "3")
	PORT_DIPSETTING(0x01, "4")
	PORT_DIPSETTING(0x03, "5")
	PORT_DIPNAME(0x0c, 0x0c, DEF_STR(Coinage))
	PORT_DIPSETTING(0x04, DEF_STR(2C_1C))
	PORT_DIPSETTING(0x00, DEF_STR(4C_3C))
	PORT_DIPSETTING(0x0c, DEF_STR(1C_1C))
	PORT_DIPSETTING(0x08, DEF_STR(2C_3C))
	PORT_DIPNAME(0x10, 0x00, DEF_STR(Demo_Sounds))
	PORT_DIPSETTING(0x10, DEF_STR(Off))
	PORT_DIPSETTING(0x00, DEF_STR(On))
	PORT_DIPNAME(0x20, 0x20, DEF_STR(Unknown))
	PORT_DIPSETTING(0x20, DEF_STR(Off))
	PORT_DIPSETTING(0x00, DEF_STR(On))
	PORT_SERVICE(0x40, IP_ACTIVE_HIGH)
	PORT_BIT(0x80, IP_ACTIVE_LOW, IPT_COIN1)

	PORT_START("INPUTS") /* inputs */
	PORT_BIT(0x8000, IP_ACTIVE_LOW, IPT_BUTTON2 | IPF_PLAYER1)
	PORT_BIT(0x4000, IP_ACTIVE_LOW, IPT_JOYSTICK_RIGHT | IPF_2WAY | IPF_PLAYER1)
	PORT_BIT(0x2000, IP_ACTIVE_LOW, IPT_BUTTON1 | IPF_PLAYER1)
	PORT_BIT(0x1000, IP_ACTIVE_LOW, IPT_JOYSTICK_LEFT | IPF_2WAY | IPF_PLAYER1)
	PORT_BIT(0x0800, IP_ACTIVE_LOW, IPT_UNUSED)
	PORT_BIT(0x0400, IP_ACTIVE_LOW, IPT_UNUSED)
	PORT_BIT(0x0200, IP_ACTIVE_LOW, IPT_UNUSED)
	PORT_BIT(0x0100, IP_ACTIVE_LOW, IPT_UNUSED)
	PORT_BIT(0x0080, IP_ACTIVE_LOW, IPT_UNUSED)
	PORT_BIT(0x0040, IP_ACTIVE_LOW, IPT_UNUSED)
	PORT_BIT(0x0020, IP_ACTIVE_LOW, IPT_BUTTON1 | IPF_PLAYER2)
	PORT_BIT(0x0010, IP_ACTIVE_LOW, IPT_BUTTON2 | IPF_PLAYER2)
	PORT_BIT(0x0008, IP_ACTIVE_LOW, IPT_START2)
	PORT_BIT(0x0004, IP_ACTIVE_LOW, IPT_JOYSTICK_RIGHT | IPF_2WAY | IPF_PLAYER2)
	PORT_BIT(0x0002, IP_ACTIVE_LOW, IPT_START1)
	PORT_BIT(0x0001, IP_ACTIVE_LOW, IPT_JOYSTICK_LEFT | IPF_2WAY | IPF_PLAYER2)

	PORT_START("IN2") /* analog stick X - unused */
	PORT_BIT(0xff, IP_ACTIVE_LOW, IPT_UNUSED)

	PORT_START("IN3") /* analog stick Y - unused */
	PORT_BIT(0xff, IP_ACTIVE_LOW, IPT_UNUSED)
	INPUT_PORTS_END

	/***************************************************************************

	  Solar Quest

	***************************************************************************/

	INPUT_PORTS_START(solarq)
	PORT_START("SWITCHES")
	PORT_DIPNAME(0x05, 0x05, DEF_STR(Coinage))
	PORT_DIPSETTING(0x01, DEF_STR(2C_1C))
	PORT_DIPSETTING(0x00, DEF_STR(4C_3C))
	PORT_DIPSETTING(0x05, DEF_STR(1C_1C))
	PORT_DIPSETTING(0x04, DEF_STR(2C_3C))
	PORT_DIPNAME(0x02, 0x02, DEF_STR(Bonus_Life))
	PORT_DIPSETTING(0x02, "25 captures")
	PORT_DIPSETTING(0x00, "40 captures")
	PORT_DIPNAME(0x18, 0x10, DEF_STR(Lives))
	PORT_DIPSETTING(0x18, "2")
	PORT_DIPSETTING(0x08, "3")
	PORT_DIPSETTING(0x10, "4")
	PORT_DIPSETTING(0x00, "5")
	PORT_DIPNAME(0x20, 0x20, DEF_STR(Free_Play))
	PORT_DIPSETTING(0x20, DEF_STR(Off))
	PORT_DIPSETTING(0x00, DEF_STR(On))
	PORT_SERVICE(0x40, IP_ACTIVE_HIGH)
	PORT_BIT(0x80, IP_ACTIVE_LOW, IPT_COIN1)

	PORT_START("INPUTS") /* inputs */
	PORT_BIT(0x8000, IP_ACTIVE_LOW, IPT_UNUSED)
	PORT_BIT(0x4000, IP_ACTIVE_LOW, IPT_UNUSED)
	PORT_BIT(0x2000, IP_ACTIVE_LOW, IPT_UNUSED)
	PORT_BIT(0x1000, IP_ACTIVE_LOW, IPT_UNUSED)
	PORT_BIT(0x0800, IP_ACTIVE_LOW, IPT_UNUSED)
	PORT_BIT(0x0400, IP_ACTIVE_LOW, IPT_UNUSED)
	PORT_BIT(0x0200, IP_ACTIVE_LOW, IPT_UNUSED)
	PORT_BIT(0x0100, IP_ACTIVE_LOW, IPT_UNUSED)
	PORT_BIT(0x0080, IP_ACTIVE_LOW, IPT_UNUSED)
	PORT_BIT(0x0040, IP_ACTIVE_LOW, IPT_UNUSED)
	PORT_BIT(0x0020, IP_ACTIVE_LOW, IPT_JOYSTICK_LEFT | IPF_2WAY | IPF_PLAYER1)
	PORT_BIT(0x0010, IP_ACTIVE_LOW, IPT_JOYSTICK_RIGHT | IPF_2WAY | IPF_PLAYER1)
	PORT_BIT(0x0008, IP_ACTIVE_LOW, IPT_START1) /* also hyperspace */
	PORT_BIT(0x0008, IP_ACTIVE_LOW, IPT_BUTTON3 | IPF_PLAYER1)
	PORT_BIT(0x0004, IP_ACTIVE_LOW, IPT_BUTTON2 | IPF_PLAYER1)
	PORT_BIT(0x0002, IP_ACTIVE_LOW, IPT_BUTTON1 | IPF_PLAYER1)
	PORT_BIT(0x0001, IP_ACTIVE_LOW, IPT_START2) /* also nova */
	PORT_BIT(0x0001, IP_ACTIVE_LOW, IPT_BUTTON4 | IPF_PLAYER1)

	PORT_START("IN2") /* analog stick X - unused */
	PORT_BIT(0xff, IP_ACTIVE_LOW, IPT_UNUSED)

	PORT_START("IN3")/* analog stick Y - unused */
	PORT_BIT(0xff, IP_ACTIVE_LOW, IPT_UNUSED)
	INPUT_PORTS_END

	/***************************************************************************

	  Demon

	***************************************************************************/

	INPUT_PORTS_START(demon)
	PORT_START("SWITCHES")
	PORT_DIPNAME(0x03, 0x03, DEF_STR(Coinage))
	PORT_DIPSETTING(0x01, DEF_STR(2C_1C))
	PORT_DIPSETTING(0x00, DEF_STR(4C_3C))
	PORT_DIPSETTING(0x03, DEF_STR(1C_1C))
	PORT_DIPSETTING(0x02, DEF_STR(2C_3C))
	PORT_DIPNAME(0x0c, 0x00, DEF_STR(Lives))
	PORT_DIPSETTING(0x00, "3")
	PORT_DIPSETTING(0x04, "4")
	PORT_DIPSETTING(0x08, "5")
	PORT_DIPSETTING(0x0c, "6")
	PORT_DIPNAME(0x30, 0x30, "Starting Difficulty")
	PORT_DIPSETTING(0x30, "1")
	PORT_DIPSETTING(0x10, "5")
	PORT_DIPSETTING(0x00, "10")
	/*	PORT_DIPSETTING(    0x20, "1" )*/
	PORT_DIPNAME(0x40, 0x40, DEF_STR(Free_Play))
	PORT_DIPSETTING(0x40, DEF_STR(Off))
	PORT_DIPSETTING(0x00, DEF_STR(On))
	PORT_BIT(0x80, IP_ACTIVE_LOW, IPT_COIN1)

	PORT_START("INPUTS")/* inputs */
	PORT_BIT(0x0001, IP_ACTIVE_LOW, IPT_START1)
	PORT_BIT(0x0002, IP_ACTIVE_LOW, IPT_START2)
	PORT_BIT(0x0004, IP_ACTIVE_LOW, IPT_JOYSTICK_LEFT | IPF_2WAY | IPF_PLAYER1)
	PORT_BIT(0x0008, IP_ACTIVE_LOW, IPT_JOYSTICK_RIGHT | IPF_2WAY | IPF_PLAYER1)
	PORT_BIT(0x0010, IP_ACTIVE_LOW, IPT_BUTTON2 | IPF_PLAYER1)
	PORT_BIT(0x0020, IP_ACTIVE_LOW, IPT_BUTTON1 | IPF_PLAYER1)
	PORT_BIT(0x0040, IP_ACTIVE_LOW, IPT_UNKNOWN)
	PORT_SERVICE(0x0080, IP_ACTIVE_LOW)
	PORT_BIT(0x0100, IP_ACTIVE_LOW, IPT_TILT)
	PORT_BIT(0x0200, IP_ACTIVE_LOW, IPT_BUTTON3 | IPF_PLAYER1)
	PORT_BIT(0x0400, IP_ACTIVE_LOW, IPT_BUTTON3 | IPF_PLAYER2)
	PORT_BIT(0x0800, IP_ACTIVE_LOW, IPT_JOYSTICK_LEFT | IPF_2WAY | IPF_PLAYER2)
	PORT_BIT(0x1000, IP_ACTIVE_LOW, IPT_JOYSTICK_RIGHT | IPF_2WAY | IPF_PLAYER2)
	PORT_BIT(0x2000, IP_ACTIVE_LOW, IPT_BUTTON2 | IPF_PLAYER2)
	PORT_BIT(0x4000, IP_ACTIVE_LOW, IPT_BUTTON1 | IPF_PLAYER2)
	PORT_BIT(0x8000, IP_ACTIVE_LOW, IPT_UNKNOWN) /* also mapped to Button 3, player 2 */


	PORT_START("IN2") /* analog stick X - unused */
	PORT_BIT(0xff, IP_ACTIVE_LOW, IPT_UNUSED)

	PORT_START("IN3") /* analog stick Y - unused */
	PORT_BIT(0xff, IP_ACTIVE_LOW, IPT_UNUSED)
	INPUT_PORTS_END

	/***************************************************************************

	  War of the Worlds

	***************************************************************************/

	INPUT_PORTS_START(wotw)
	PORT_START("SWITCHES")
	PORT_DIPNAME(0x01, 0x01, DEF_STR(Unknown))
	PORT_DIPSETTING(0x01, DEF_STR(Off))
	PORT_DIPSETTING(0x00, DEF_STR(On))
	PORT_DIPNAME(0x02, 0x02, DEF_STR(Lives))
	PORT_DIPSETTING(0x02, "3")
	PORT_DIPSETTING(0x00, "5")
	PORT_DIPNAME(0x04, 0x04, DEF_STR(Unknown))
	PORT_DIPSETTING(0x04, DEF_STR(Off))
	PORT_DIPSETTING(0x00, DEF_STR(On))
	PORT_DIPNAME(0x08, 0x08, DEF_STR(Coinage))
	PORT_DIPSETTING(0x08, DEF_STR(1C_1C))
	PORT_DIPSETTING(0x00, DEF_STR(2C_3C))
	PORT_DIPNAME(0x10, 0x10, DEF_STR(Unknown))
	PORT_DIPSETTING(0x10, DEF_STR(Off))
	PORT_DIPSETTING(0x00, DEF_STR(On))
	PORT_DIPNAME(0x20, 0x20, DEF_STR(Free_Play))
	PORT_DIPSETTING(0x20, DEF_STR(Off))
	PORT_DIPSETTING(0x00, DEF_STR(On))
	PORT_SERVICE(0x40, IP_ACTIVE_LOW)
	PORT_BIT(0x80, IP_ACTIVE_LOW, IPT_COIN1)

	PORT_START("INPUTS") /* inputs */
	PORT_BIT(0x8000, IP_ACTIVE_LOW, IPT_UNUSED)
	PORT_BIT(0x4000, IP_ACTIVE_LOW, IPT_UNUSED)
	PORT_BIT(0x2000, IP_ACTIVE_LOW, IPT_UNUSED)
	PORT_BIT(0x1000, IP_ACTIVE_LOW, IPT_BUTTON1)
	PORT_BIT(0x0800, IP_ACTIVE_LOW, IPT_UNUSED)
	PORT_BIT(0x0400, IP_ACTIVE_LOW, IPT_BUTTON2)
	PORT_BIT(0x0200, IP_ACTIVE_LOW, IPT_UNUSED)
	PORT_BIT(0x0100, IP_ACTIVE_LOW, IPT_JOYSTICK_RIGHT | IPF_2WAY)
	PORT_BIT(0x0080, IP_ACTIVE_LOW, IPT_UNUSED)
	PORT_BIT(0x0040, IP_ACTIVE_LOW, IPT_JOYSTICK_LEFT | IPF_2WAY)
	PORT_BIT(0x0020, IP_ACTIVE_LOW, IPT_UNUSED)
	PORT_BIT(0x0010, IP_ACTIVE_LOW, IPT_UNUSED)
	PORT_BIT(0x0008, IP_ACTIVE_LOW, IPT_UNUSED)
	PORT_BIT(0x0004, IP_ACTIVE_LOW, IPT_START2)
	PORT_BIT(0x0002, IP_ACTIVE_LOW, IPT_UNUSED)
	PORT_BIT(0x0001, IP_ACTIVE_LOW, IPT_START1)

	PORT_START("IN2") /* analog stick X - unused */
	PORT_BIT(0xff, IP_ACTIVE_LOW, IPT_UNUSED)

	PORT_START("IN3") /* analog stick Y - unused */
	PORT_BIT(0xff, IP_ACTIVE_LOW, IPT_UNUSED)
	INPUT_PORTS_END

	/***************************************************************************

	  Boxing Bugs

	***************************************************************************/

	INPUT_PORTS_START(boxingb)
	PORT_START("SWITCHES")
	PORT_DIPNAME(0x03, 0x03, DEF_STR(Coinage))
	PORT_DIPSETTING(0x01, DEF_STR(2C_1C))
	PORT_DIPSETTING(0x00, DEF_STR(4C_3C))
	PORT_DIPSETTING(0x03, DEF_STR(1C_1C))
	PORT_DIPSETTING(0x02, DEF_STR(2C_3C))
	PORT_DIPNAME(0x04, 0x00, DEF_STR(Lives))
	PORT_DIPSETTING(0x04, "3")
	PORT_DIPSETTING(0x00, "5")
	PORT_DIPNAME(0x08, 0x00, DEF_STR(Bonus_Life))
	PORT_DIPSETTING(0x00, "30,000")
	PORT_DIPSETTING(0x08, "50,000")
	PORT_DIPNAME(0x10, 0x00, DEF_STR(Demo_Sounds))
	PORT_DIPSETTING(0x10, DEF_STR(Off))
	PORT_DIPSETTING(0x00, DEF_STR(On))
	PORT_DIPNAME(0x20, 0x20, DEF_STR(Free_Play))
	PORT_DIPSETTING(0x20, DEF_STR(Off))
	PORT_DIPSETTING(0x00, DEF_STR(On))
	PORT_SERVICE(0x40, IP_ACTIVE_LOW)
	PORT_BIT(0x80, IP_ACTIVE_LOW, IPT_COIN1)

	PORT_START("INPUTS") /* inputs */
	PORT_BIT(0xf000, IP_ACTIVE_HIGH, IPT_UNUSED)	/* dial */
	PORT_BIT(0x0800, IP_ACTIVE_LOW, IPT_UNUSED)
	PORT_BIT(0x0400, IP_ACTIVE_LOW, IPT_UNUSED)
	PORT_BIT(0x0200, IP_ACTIVE_LOW, IPT_UNUSED)
	PORT_BIT(0x0100, IP_ACTIVE_LOW, IPT_UNUSED)
	PORT_BIT(0x0080, IP_ACTIVE_LOW, IPT_UNUSED)
	PORT_BIT(0x0040, IP_ACTIVE_LOW, IPT_UNUSED)
	PORT_BIT(0x0020, IP_ACTIVE_LOW, IPT_BUTTON1 | IPF_PLAYER1)
	PORT_BIT(0x0010, IP_ACTIVE_LOW, IPT_BUTTON2 | IPF_PLAYER1)
	PORT_BIT(0x0008, IP_ACTIVE_LOW, IPT_BUTTON3 | IPF_PLAYER1)
	PORT_BIT(0x0008, IP_ACTIVE_LOW, IPT_START1)
	PORT_BIT(0x0004, IP_ACTIVE_LOW, IPT_BUTTON3 | IPF_PLAYER2)
	PORT_BIT(0x0004, IP_ACTIVE_LOW, IPT_START2)
	PORT_BIT(0x0002, IP_ACTIVE_LOW, IPT_BUTTON2 | IPF_PLAYER2)
	PORT_BIT(0x0001, IP_ACTIVE_LOW, IPT_BUTTON1 | IPF_PLAYER2)

	PORT_START("IN2") /* analog stick X - unused */
	PORT_BIT(0xff, IP_ACTIVE_LOW, IPT_UNUSED)

	PORT_START("IN3") /* analog stick Y - unused */
	PORT_BIT(0xff, IP_ACTIVE_LOW, IPT_UNUSED)

	PORT_START("DIAL")/* fake (in4) */
	PORT_ANALOG(0xff, 0x80, IPT_DIAL, 100, 5, 0, 0x00, 0xff)
	INPUT_PORTS_END


		/*************************************
		 *
		 *	Port definitions
		 *
		 *************************************/

		INPUT_PORTS_START(aztarac)
		PORT_START("IN0") /* IN0 */
		PORT_ANALOG(0x1f, 0xf, IPT_AD_STICK_X | IPF_CENTER, 100, 1,0, 0, 0x1e)
		//PORT_ANALOG(0xff, 0x80, IPT_AD_STICK_X, 100, 5, 0, 0x20, 0xe0)

		PORT_START("IN1") /* IN1 */
		//PORT_ANALOG(0x1f, 0xf, IPT_AD_STICK_Y | IPF_CENTER | IPF_REVERSE, 100, 1, 0, 0x1e)
		PORT_ANALOG(0x1f, 0xf, IPT_AD_STICK_Y | IPF_CENTER | IPF_REVERSE, 100, 1,  0, 0, 0xe1)

		PORT_START("IN2")
		//PORT_ANALOGX(0xff, 0x00, IPT_DIAL | IPF_REVERSE, 25, 10, 0, 0, ,0, KEYCODE_Z, KEYCODE_X,0,0)
		PORT_ANALOGX(0xff, 0x00, IPT_DIAL | IPF_REVERSE, 100, 10, 0, 0, 0, OSD_KEY_UP, OSD_KEY_DOWN, 0, 0)

	


		PORT_START("IN3")
		PORT_BIT(0x02, IP_ACTIVE_LOW, IPT_BUTTON1)
		PORT_BIT(0x01, IP_ACTIVE_LOW, IPT_BUTTON2)
		PORT_BIT(0x04, IP_ACTIVE_LOW, IPT_START1)
		PORT_BIT(0x08, IP_ACTIVE_LOW, IPT_START2)
		PORT_BIT(0x10, IP_ACTIVE_LOW, IPT_COIN1)
		PORT_BIT(0x20, IP_ACTIVE_LOW, IPT_UNKNOWN)
		PORT_BIT(0x40, IP_ACTIVE_LOW, IPT_UNKNOWN)
		PORT_BITX(0x80, IP_ACTIVE_LOW, IPT_SERVICE, "Diagnostic Step", OSD_KEY_F1, IP_JOY_NONE)
		INPUT_PORTS_END


#endif