/***************************************************************************

  astrocde_video.cpp

  Bally Astrocade style video hardware.
  Ported from MAME 0.57 src/vidhrdw/astrocde.c to AAE.
  Original MAME driver by Nicola Salmoria, Mike Coates, Frank Palazzolo.

  See astrocde_video.h for the hardware overview and the list of
  differences from the MAME original.

***************************************************************************/

#include <cmath>     /* sin, cos, floor for the palette */
#include <cstring>
#include <cstdlib>

#include "aae_mame_driver.h"
#include "astrocde_video.h"
#include "old_mame_raster.h"

#define SCREEN_WIDTH 320
#define MAX_LINES 204

#define MAX_INT_PER_FRAME 256

/* This value affects the star layout, the value is correct since
   it is mentioned in the docs and perfectly matches screen shots.
 */
#define CLOCKS_PER_LINE 455

/* This value affects the star blinking and the sparkle patterns.
   It is just a guess, aiming to a supposed 60Hz refresh rate, and has
   not been verified.
 */
#define CLOCKS_PER_FRAME (CLOCKS_PER_LINE*262)

#define RNG_PERIOD 131071	/* 2^17-1 */

unsigned char* wow_videoram = nullptr;

static int magic_expand_color, magic_control, magic_expand_count, magic_shift_leftover;
static int collision;

static int* rng = nullptr;
static int* star = nullptr;

static int line_colors[MAX_INT_PER_FRAME][8];
static int colorsplit[MAX_INT_PER_FRAME];
static int BackgroundData, VerticalBlank;

static int sparkle[MAX_INT_PER_FRAME][4];	/* sparkle[line][0] is star enable */

/* Scanline interrupt system */
static int NextScanInt = 0;
static int CurrentScan = 0;
static int InterruptFlag = 0;

/* Pattern board registers */
static int pb_src, pb_mode, pb_skip, pb_dest, pb_length, pb_loops;

/* B&W monitor simulation: pen & 7 keeps luminance, drops hue. */
static int bw_monitor = 0;

void astrocde_set_bw_monitor(int enable)
{
	bw_monitor = enable ? 1 : 0;
}

static void wow_update_line(struct osd_bitmap* bitmap, int line);

/****************************************************************************
 * Palette
 ****************************************************************************/

void astrocde_init_palette(unsigned char* palette, unsigned char* colortable, const unsigned char* color_prom)
{
	/* This routine builds a palette using a transformation from */
	/* the YUV (Y, B-Y, R-Y) to the RGB color space */

	int i, j;

	float Y, RY, BY;	/* Y, R-Y, and B-Y signals as generated by the game */
						/* Y = Luminance -> (0 to 1) */
						/* R-Y = Color along R-Y axis -> C*(-1 to +1) */
						/* B-Y = Color along B-Y axis -> C*(-1 to +1) */
	float R, G, B;

	float brightest = 1.0f;	/* Approx. Luminance values for the extremes -> (0 to 1) */
	float dimmest = 0.0f;
	float C = 0.75f;		/* Approx. Chroma intensity */

	(void)colortable;
	(void)color_prom;

	/* The astrocade has a 256 color palette                 */
	/* 32 colors, with 8 luminance levels for each color     */
	/* The 32 colors circle around the YUV color space,      */
	/* with the exception of the first 8 which are grayscale */

	/* Note: to simulate a B&W monitor, set C=0 and all      */
	/*       colors will appear as the first 8 grayscales    */

	for (i = 0; i < 32; i++)
	{
		RY = C * (float)sin(i * 2.0 * 3.14159 / 32.0);
		if (i == 0)
			BY = 0;
		else
			BY = C * (float)cos(i * 2.0 * 3.14159 / 32.0);

		for (j = 0; j < 8; j++)
		{
			Y = (j / 7.0f) * (brightest - dimmest) + dimmest;

			/* Transform to RGB */

			R = (RY + Y) * 255;
			G = (Y - 0.299f * (RY + Y) - 0.114f * (BY + Y)) / 0.587f * 255;
			B = (BY + Y) * 255;

			/* Clipping, in case of saturation */

			if (R < 0) R = 0;
			if (R > 255) R = 255;
			if (G < 0) G = 0;
			if (G > 255) G = 255;
			if (B < 0) B = 0;
			if (B > 255) B = 255;

			/* Round, and set the value */

			*palette++ = (unsigned char)floor(R + .5f);
			*palette++ = (unsigned char)floor(G + .5f);
			*palette++ = (unsigned char)floor(B + .5f);
		}
	}
}

/****************************************************************************
 * Scanline Interrupt System
 ****************************************************************************/

void astrocde_interrupt_enable_w(UINT16 port, UINT8 data, struct z80PortWrite* pPW)
{
	(void)port; (void)pPW;

	InterruptFlag = data;

	/* bit 0: 1 = disable interrupts */
	interrupt_enable_w(0, (data & 0x01) ? 0 : 1, nullptr);

	/* bit 4 arms the Gorf special interrupt -- omitted until a Gorf
	   driver exists (Space Zap never sets it). */
}

void astrocde_interrupt_w(UINT16 port, UINT8 data, struct z80PortWrite* pPW)
{
	(void)port; (void)pPW;

	/* A write to 0F triggers an interrupt at that scanline */
	NextScanInt = data;
}

/*
 * AAE equivalent of MAME's wow_interrupt(): registered as int_cpu with
 * div=256 / ipf=256, so it runs once per scanline slot. Renders the line
 * that just completed, latches the color registers forward to the next
 * line, and fires the Z80 INT (vector set via interrupt_vector_w on port
 * 0x0d) when the programmed scanline is reached.
 */
void astrocde_scanline_interrupt(void)
{
	int i, next;

	/* Top of a new display frame (the previous frame has already been
	   presented -- render() runs after cpu_run's 256 passes): wipe the
	   bitmap before drawing line 0 so stale rendering can't persist. */
	if (CurrentScan == 0)
		osd_clearbitmap(main_bitmap);

	wow_update_line(main_bitmap, CurrentScan);

	next = (CurrentScan + 1) % MAX_INT_PER_FRAME;
	for (i = 0; i < 8; i++)
		line_colors[next][i] = line_colors[CurrentScan][i];
	for (i = 0; i < 4; i++)
		sparkle[next][i] = sparkle[CurrentScan][i];
	colorsplit[next] = colorsplit[CurrentScan];

	CurrentScan = next;

	/* Scanline interrupt enabled ? (cpu_do_int_imm also respects the
	   per-CPU enable set by astrocde_interrupt_enable_w bit 0) */
	if ((InterruptFlag & 0x08) && (CurrentScan == NextScanInt))
		cpu_do_int_imm(CPU0, INT_TYPE_INT);
}

/* ======================================================================= */

UINT16 wow_video_retrace_r(UINT16 port, struct z80PortRead* pPR)
{
	(void)port; (void)pPR;
	return (UINT16)CurrentScan;
}

UINT16 wow_intercept_r(UINT16 port, struct z80PortRead* pPR)
{
	int res;

	(void)port; (void)pPR;

	res = collision;
	collision = 0;

	return (UINT16)res;
}

/* Switches color registers at this zone - 40 zones */

void astrocde_colour_split_w(UINT16 port, UINT8 data, struct z80PortWrite* pPW)
{
	(void)port; (void)pPW;

	colorsplit[CurrentScan] = 2 * (data & 0x3f);

	BackgroundData = ((data & 0xc0) >> 6) * 0x55;
}

/* This selects commercial (high res, arcade) or
				  consumer (low res, astrocade) mode */

void astrocde_mode_w(UINT16 port, UINT8 data, struct z80PortWrite* pPW)
{
	(void)port; (void)data; (void)pPW;
	/*	astrocade_mode = data & 0x01; */
}

void astrocde_vertical_blank_w(UINT16 port, UINT8 data, struct z80PortWrite* pPW)
{
	(void)port; (void)pPW;

	if (VerticalBlank != data)
	{
		VerticalBlank = data;
	}
}

static void colour_register_put(int offset, int data)
{
	line_colors[CurrentScan][offset & 7] = data;
}

void astrocde_colour_register_w(UINT16 port, UINT8 data, struct z80PortWrite* pPW)
{
	(void)pPW;
	colour_register_put(port & 7, data);
}

void astrocde_colour_block_w(UINT16 port, UINT8 data, struct z80PortWrite* pPW)
{
	static int color_reg_num = 7;

	(void)port; (void)pPW;

	colour_register_put(color_reg_num, data);

	color_reg_num = (color_reg_num - 1) & 7;
}

/****************************************************************************
 * Video / magic RAM
 ****************************************************************************/

/* Store into the 16KB video RAM (index 0-0x3fff). wow_videoram points at
   the CPU region backing 0x4000-0x7fff, so plain CPU reads of that range
   (MRA_RAM) and pattern-board source reads see the same bytes. */
static inline void videoram_put(int offset, int data)
{
	if ((offset >= 0) && (offset < 0x4000) && (wow_videoram[offset] != data))
	{
		/* data may exceed 0xff mid-pipeline (backwards shift); the store
		   truncates, exactly like MAME's unsigned char videoram array. */
		wow_videoram[offset] = (unsigned char)data;
	}
}

void wow_videoram_w(UINT32 address, UINT8 data, struct MemoryWriteByte* psMemWrite)
{
	/* The AAE Z80 core passes handlers the offset relative to the range
	   start (addr - lowAddr), so 'address' is already the 0-based video
	   RAM index -- do NOT subtract 0x4000 here. */
	(void)psMemWrite;
	videoram_put((int)address, data);
}

void astrocde_magic_expand_color_w(UINT16 port, UINT8 data, struct z80PortWrite* pPW)
{
	(void)port; (void)pPW;
	magic_expand_color = data;
}

void astrocde_magic_control_w(UINT16 port, UINT8 data, struct z80PortWrite* pPW)
{
	(void)port; (void)pPW;

	magic_control = data;

	magic_expand_count = 0;		/* reset flip-flop for expand mode on write to this register */
	magic_shift_leftover = 0;	/* reset shift buffer on write to this register */

	if (magic_control & 0x04)
		LOG_INFO("astrocde: unsupported MAGIC ROTATE mode");
}

static void copywithflip(int offset, int data)
{
	int shift, data1;

	if (magic_control & 0x40)	/* copy backwards */
	{
		int bits, stib, k;

		bits = data;
		stib = 0;
		for (k = 0; k < 4; k++)
		{
			stib >>= 2;
			stib |= (bits & 0xc0);
			bits <<= 2;
		}

		data = stib;
	}

	shift = magic_control & 3;
	data1 = 0;
	if (magic_control & 0x40)	/* copy backwards */
	{
		while (shift > 0)
		{
			data1 <<= 2;
			data1 |= (data & 0xc0) >> 6;
			data <<= 2;
			shift--;
		}
	}
	else
	{
		while (shift > 0)
		{
			data1 >>= 2;
			data1 |= (data & 0x03) << 6;
			data >>= 2;
			shift--;
		}
	}
	data |= magic_shift_leftover;
	magic_shift_leftover = data1;

	if (magic_control & 0x30)
	{
		/* TODO: the collision detection should be made */
		/* independently for each of the four pixels    */

		if (data && wow_videoram[offset])
			collision |= 0xff;
		else collision &= 0x0f;
	}

	if (magic_control & 0x20) data ^= wow_videoram[offset];	/* draw in XOR mode */
	else if (magic_control & 0x10) data |= wow_videoram[offset];	/* draw in OR mode */
	videoram_put(offset, data);
}

void wow_magicram_w(UINT32 address, UINT8 data, struct MemoryWriteByte* psMemWrite)
{
	int offset = (int)(address & 0x3fff);

	(void)psMemWrite;

	if (magic_control & 0x08)	/* expand mode */
	{
		int bits, bibits, k;

		bits = data;
		if (magic_expand_count) bits <<= 4;
		bibits = 0;
		for (k = 0; k < 4; k++)
		{
			bibits <<= 2;
			if (bits & 0x80) bibits |= (magic_expand_color >> 2) & 0x03;
			else bibits |= magic_expand_color & 0x03;
			bits <<= 1;
		}

		copywithflip(offset, bibits);

		magic_expand_count ^= 1;
	}
	else copywithflip(offset, data);
}

/****************************************************************************
 * Pattern board blitter (ports 0x78-0x7e)
 ****************************************************************************/

/* MAME writes blit destinations through cpu_writemem16 so they hit the
   magic RAM / video RAM handlers. Mirror the write side of the memory
   map here: 0x0000-0x3fff magic RAM, 0x4000-0x7fff video RAM, 0xd000
   and up plain RAM (region-backed). ROM ranges are ignored. */
static void pattern_board_write(int addr, int data)
{
	if (addr < 0)
		return;
	addr &= 0xffff;

	if (addr < 0x4000)
		wow_magicram_w((UINT32)addr, (UINT8)data, nullptr);
	else if (addr < 0x8000)
		videoram_put(addr - 0x4000, data);
	else if (addr >= 0xd000)
		Machine->memory_region[CPU0][addr] = (unsigned char)data;
	/* 0x8000-0xcfff is ROM: writes are dropped, like MWA_ROM */
}

void astrocde_pattern_board_w(UINT16 port, UINT8 data, struct z80PortWrite* pPW)
{
	int offset = port - 0x78;
	unsigned char* RAM = Machine->memory_region[CPU0];

	(void)pPW;

	switch (offset)
	{
		case 0:
			pb_src = data;
			break;
		case 1:
			pb_src = pb_src + data * 256;
			break;
		case 2:
			pb_mode = data & 0x3f;			/* register is 6 bit wide */
			break;
		case 3:
			pb_skip = data;
			break;
		case 4:
			pb_dest = pb_skip + data * 256;	/* register 3 is shared between skip and dest */
			break;
		case 5:
			pb_length = data;
			break;
		case 6:
			pb_loops = data;
			break;
	}

	if (offset == 6)	/* trigger blit */
	{
		int i, j;

		/* MAME steals 4*(length+1)*(loops+1) Z80 cycles here so Gorf's
		   text scrolling isn't too fast. Space Zap doesn't need it and
		   the AAE Z80 has no cycle-steal hook; revisit for Gorf. */

		for (i = 0; i <= pb_loops; i++)
		{
			for (j = 0; j <= pb_length; j++)
			{
				if (!(pb_mode & 0x08) || j < pb_length)
				{
					if (pb_mode & 0x01)			/* Direction */
						RAM[pb_src & 0xffff] = RAM[pb_dest & 0xffff];
					else
						pattern_board_write(pb_dest, RAM[pb_src & 0xffff]);	/* ASG 971005 */
				}
				/* close out writes in case of shift... I think this is wrong */
				else if (j == pb_length)
					pattern_board_write(pb_dest, 0);

				if ((j & 1) || !(pb_mode & 0x02))  /* Expand Mode - don't increment source on odd loops */
					if (pb_mode & 0x04) pb_src++;	/* Constant mode - don't increment at all! */

				if (pb_mode & 0x20) pb_dest++;		/* copy forwards */
				else pb_dest--;						/* backwards */
			}

			if ((j & 1) && (pb_mode & 0x02))		/* always increment source at end of line */
				if (pb_mode & 0x04) pb_src++;		/* Constant mode - don't increment at all! */

			if ((pb_mode & 0x08) && (pb_mode & 0x04)) /* Correct src if in flush mode */
				pb_src--;                             /* and NOT in Constant mode */

			if (pb_mode & 0x20) pb_dest--;			/* copy forwards */
			else pb_dest++;							/* backwards */

			pb_dest += (int)((signed char)pb_skip);	/* extend the sign of the skip register */
		}
	}
}

/****************************************************************************
 * Star field
 ****************************************************************************/

static void init_star_field(void)
{
	int generator;
	int count, x, y;

	generator = 0;

	/* this 17-bit shifter with XOR feedback has a period of 2^17-1 iterations */
	for (count = 0; count < RNG_PERIOD; count++)
	{
		int bit1, bit2;

		generator <<= 1;
		bit1 = (~generator >> 17) & 1;
		bit2 = (generator >> 5) & 1;

		if (bit1 ^ bit2) generator |= 1;

		rng[count] = generator & 0x1ffff;
	}

	/* calculate stars positions */
	count = 0;
	for (y = 0; y < MAX_LINES; y++)
	{
		for (x = -16; x < CLOCKS_PER_LINE - 16; x++)	/* perfect values determined with screen shots */
		{
			if (x >= Machine->visible_area.min_x &&
				x <= Machine->visible_area.max_x &&
				y >= Machine->visible_area.min_y &&
				y <= Machine->visible_area.max_y)
			{
				if ((rng[count] & 0x1fe00) == 0x0fe00)
					star[x + SCREEN_WIDTH * y] = 1;
				else
					star[x + SCREEN_WIDTH * y] = 0;
			}

			count++;
		}
	}

	/* now convert the rng values to Y adjustments that will be used at runtime */
	for (count = 0; count < RNG_PERIOD; count++)
	{
		int r;

		r = rng[count];
		rng[count] = (((r >> 12) & 1) << 3) +
					 (((r >> 8) & 1) << 2) +
					 (((r >> 4) & 1) << 1) +
					 (((r >> 0) & 1) << 0);
	}
}

/****************************************************************************
 * Start / stop
 ****************************************************************************/

void astrocde_vh_stop(void)
{
	free(rng);
	rng = nullptr;
	free(star);
	star = nullptr;
	wow_videoram = nullptr;
}

int astrocde_vh_start(void)
{
	rng = (int*)malloc(RNG_PERIOD * sizeof(rng[0]));
	star = (int*)malloc(SCREEN_WIDTH * MAX_LINES * sizeof(star[0]));

	if (!rng || !star)
	{
		astrocde_vh_stop();
		return 1;
	}

	/* video RAM lives in the CPU region at 0x4000-0x7fff */
	wow_videoram = &Machine->memory_region[CPU0][0x4000];

	/* AAE restarts games in-process, so reset everything MAME could
	   rely on being freshly zeroed statics. */
	memset(rng, 0, RNG_PERIOD * sizeof(rng[0]));
	memset(star, 0, SCREEN_WIDTH * MAX_LINES * sizeof(star[0]));
	memset(sparkle, 0, sizeof(sparkle));
	memset(line_colors, 0, sizeof(line_colors));
	memset(colorsplit, 0, sizeof(colorsplit));

	CurrentScan = 0;
	NextScanInt = 0;
	InterruptFlag = 0;
	collision = 0;
	BackgroundData = 0;
	VerticalBlank = 0;

	magic_expand_color = 0;
	magic_control = 0;
	magic_expand_count = 0;
	magic_shift_leftover = 0;

	pb_src = pb_mode = pb_skip = pb_dest = pb_length = pb_loops = 0;

	return 0;
}

int astrocde_stars_vh_start(void)
{
	int res;

	res = astrocde_vh_start();
	if (res)
		return res;

	sparkle[0][0] = 1;	/* wow doesn't initialize this */
	init_star_field();

	return res;
}

/****************************************************************************
 * Line rendering
 ****************************************************************************/

static void wow_update_line(struct osd_bitmap* bitmap, int line)
{
	/* Copy one line to bitmap, using current color register settings */

	int memloc;
	int i, x;
	int data, color;
	int rngoffs;

	if (line >= MAX_LINES) return;

	/* MAME uses cpu_getcurrentframe(); the AAE `frames` global serves
	   the same purpose (only used to animate the sparkle pattern). */
	rngoffs = (int)(((unsigned long long)(frames % RNG_PERIOD) * CLOCKS_PER_FRAME) % RNG_PERIOD);

	memloc = line * 80;

	for (i = 0; i < 80; i++, memloc++)
	{
		if (line < VerticalBlank)
			data = wow_videoram[memloc];
		else
			data = BackgroundData;

		for (x = i * 4 + 3; x >= i * 4; x--)
		{
			int pen, scol;

			color = data & 0x03;
			if (i < colorsplit[line]) color += 4;

			if ((data & 0x03) == 0)
			{
				if (sparkle[line][0])
				{
					if (star[x + SCREEN_WIDTH * line])
					{
						scol = rng[(rngoffs + x + CLOCKS_PER_LINE * line) % RNG_PERIOD];
						pen = (line_colors[line][color] & ~7) + scol / 2;
					}
					else
						pen = 0;
				}
				else
					pen = line_colors[line][color];
			}
			else
			{
				if (sparkle[line][data & 0x03])
				{
					scol = rng[(rngoffs + x + CLOCKS_PER_LINE * line) % RNG_PERIOD];
					pen = (line_colors[line][color] & ~7) + scol / 2;
				}
				else
					pen = line_colors[line][color];
			}

			pen &= 0xff;
			if (bw_monitor)
				pen &= 0x07;	/* B&W monitor: luminance only */

			plot_pixel(bitmap, x, line, Machine->pens[pen]);

			data >>= 2;
		}
	}
}
