/***************************************************************************

  mappy.cpp  --  AAE driver for Mappy and related Namco games

  Hardware family: Namco Super Pac-Man board (dual 6809, custom I/O, Namco sound)
  Games covered:
    mappy     - Mappy (US)           1983 Namco
    mappyjp   - Mappy (Japan)        1983 Namco
    digdug2   - Dig Dug 2            1985 Namco
    motos     - Motos                1985 Namco
    todruaga  - Tower of Druaga      1984 Namco

  Memory map (CPU 1):
    0000-07ff  video RAM
    0800-0fff  color RAM
    1000-177f  general RAM
    1780-17ff  sprite RAM area 1 (sprite number and color)
    1800-1f7f  general RAM
    1f80-1fff  sprite RAM area 2 (x, y position)
    2000-277f  general RAM
    2780-27ff  sprite RAM area 3 (high bit of y, flip flags, size flags)
    3800-3fff  scroll register map
    4040-43ff  RAM shared with CPU 2 (sound CPU)
    4800-480f  custom I/O chip 1
    4810-481f  custom I/O chip 2
    5002-5003  CPU 1 interrupt enable
    500a-500b  CPU 2 (sound) enable
    8000       watchdog timer
    a000-ffff  ROM (mappy), 8000-ffff (digdug2, motos, todruaga)

  Memory map (CPU 2 / sound):
    0000-003f  Namco sound registers
    0040-03ff  RAM shared with CPU 1
    2000-2001  CPU 2 interrupt enable
    2006-2007  sound enable
    e000-ffff  ROM

  Interrupts:
    CPU 1 IRQ: generated by VBLANK
    CPU 2 IRQ: generated by VBLANK

  Converted from MAME 0.33 mappy driver by Aaron Giles / Mirko Buffoni / JROK
 
***************************************************************************/

#include "aae_mame_driver.h"
#include "mappy.h"
#include "old_mame_raster.h"
#include "driver_registry.h"
#include "namco.h"
#include "timer.h"

#pragma warning( disable : 4838 4003 )
extern int m6809_slapstic;

// ---------------------------------------------------------------------------
// Shared state
// ---------------------------------------------------------------------------

/* shared RAM between main CPU and sound CPU (at offset 0x40 in CPU2 space) */
static unsigned char mappy_sharedram_buf[0x3c0];
unsigned char* mappy_sharedram = mappy_sharedram_buf;

/* custom I/O chip register banks */
static unsigned char mappy_customio_1_buf[16];
static unsigned char mappy_customio_2_buf[16];
unsigned char* mappy_customio_1 = mappy_customio_1_buf;
unsigned char* mappy_customio_2 = mappy_customio_2_buf;

static unsigned char interrupt_enable_1 = 0;
static unsigned char interrupt_enable_2 = 0;

/* credit tracking for custom I/O emulation */
static int credits = 0;


// ---------------------------------------------------------------------------
// Namco sound interface -- 8 voices, matches original mappy hardware
// ---------------------------------------------------------------------------

static struct namco_interface namco_interface =
{
    23920,	/* sample rate (approximate value) */
    8,		/* number of voices */
    220,	/* playback volume */
    REGION_SOUND1	/* memory region */
};

// ---------------------------------------------------------------------------
// Machine init
// ---------------------------------------------------------------------------

void mappy_init_machine(void)
{
    credits = 0;
}

void motos_init_machine(void)
{
    credits = 0;
}


// ---------------------------------------------------------------------------
// Shared RAM handlers
// The sound CPU sits in a tight polling loop waiting for work; spinning it
// until the next interrupt avoids burning host CPU cycles.
// ---------------------------------------------------------------------------

READ_HANDLER(mappy_sharedram_r)
{
    return mappy_sharedram[address];
}

READ_HANDLER(mappy_sharedram_r2)
{
    /* speed hack: detect the idle loop in the sound CPU and yield */
   // if (address == 0x010a - 0x40 && mappy_sharedram[address] == 0)
    //    cpu_spinuntil_int();
    return mappy_sharedram[address];
}

READ_HANDLER(digdug2_sharedram_r2)
{
    /* Dig Dug 2 idle loop is at a different address */
   // if (address == 0x0a1 - 0x40 && mappy_sharedram[address] == 0
    //    && cpu_getpc() == 0xe383)
     //   cpu_spinuntil_int();
    return mappy_sharedram[address];
}

READ_HANDLER(motos_sharedram_r2)
{
    return mappy_sharedram[address];
}

READ_HANDLER(todruaga_sharedram_r2)
{
    return mappy_sharedram[address];
}

WRITE_HANDLER(mappy_sharedram_w)
{
    mappy_sharedram[address] = data;
}


// ---------------------------------------------------------------------------
// Main CPU RAM handlers (with idle-loop detection for CPU1)
// ---------------------------------------------------------------------------

READ_HANDLER(mappy_cpu1ram_r)
{
    /* CPU1 idles waiting for VBLANK; spin it if we catch the loop */
   // if (address == 0x1382 && Machine->memory_region[CPU0][address] == 0)
   //     cpu_spinuntil_int();
    return Machine->memory_region[CPU0][address];
}

READ_HANDLER(digdug2_cpu1ram_r)
{
   // if (address == 0x1000 && Machine->memory_region[CPU0][address] == 0  && cpu_getpc() == 0x80c4)
    //    cpu_spinuntil_int();
    return Machine->memory_region[CPU0][address];
}

READ_HANDLER(motos_cpu1ram_r)
{
    return Machine->memory_region[CPU0][address];
}

READ_HANDLER(todruaga_cpu1ram_r)
{
    return Machine->memory_region[CPU0][address];
}


// ---------------------------------------------------------------------------
// Custom I/O chip write
// The custom I/O chips are write-to-set-mode, read-to-get-data devices.
// Writing to offset 8 sets the operating mode used by the read handler.
// ---------------------------------------------------------------------------

WRITE_HANDLER(mappy_customio_w_1)
{
    mappy_customio_1[address] = data;
}

WRITE_HANDLER(mappy_customio_w_2)
{
    mappy_customio_2[address] = data;
}


// ---------------------------------------------------------------------------
// Mappy custom I/O read -- chip 1 (joystick, coins, start, credits)
// ---------------------------------------------------------------------------

READ_HANDLER(mappy_customio_r_1)
{
    /* credit/coin ratios for each DSW1 coin setting */
    static int crednum[] = { 1, 2, 3, 6, 1, 3, 1, 2 };
    static int credden[] = { 1, 1, 1, 1, 2, 2, 3, 3 };
    int val, temp;
    int mode = mappy_customio_1[8];

    /* mode 1 and 3 return live gameplay values */
    if (mode == 1 || mode == 3)
    {
        switch (address)
        {
        case 0:     /* coin slots, low nibble of port 4 */
        {
            static int lastval;
            val = readinputport(4) & 0x0f;
            if ((val & 1) && ((val ^ lastval) & 1)) ++credits;
            return lastval = val;
        }
        case 1:     /* start buttons, high nibble of port 4 */
        {
            static int lastval;
            temp = readinputport(1) & 7;
            val  = readinputport(4) >> 4;
            if ((val & 1) && ((val ^ lastval) & 1))
            {
                if (credits >= credden[temp]) credits -= credden[temp];
                else val &= ~1;
            }
            if ((val & 2) && ((val ^ lastval) & 2))
            {
                if (credits >= 2 * credden[temp]) credits -= 2 * credden[temp];
                else val &= ~2;
            }
            return lastval = val;
        }
        case 2:     /* high BCD digit of credit display */
            temp = readinputport(1) & 7;
            return (credits * crednum[temp] / credden[temp]) / 10;
        case 3:     /* low BCD digit of credit display */
            temp = readinputport(1) & 7;
            return (credits * crednum[temp] / credden[temp]) % 10;
        case 4:     /* player 1 joystick */
            return readinputport(3) & 0x0f;
        case 5:     /* player 1 buttons */
            return readinputport(3) >> 4;
        case 6:
        case 7:
            return 0;
        }
    }
    /* mode 5 returns self-test verification values used during power-on */
    else if (mode == 5)
    {
        static int testvals[] = { 8, 4, 6, 14, 13, 9, 13 };
        if (address >= 1 && address <= 7)
            return testvals[address - 1];
    }

    return mappy_customio_1[address];
}


// ---------------------------------------------------------------------------
// Mappy custom I/O read -- chip 2 (DIP switches, service)
// ---------------------------------------------------------------------------

READ_HANDLER(mappy_customio_r_2)
{
    int mode = mappy_customio_2[8];

    if (mode == 4)
    {
        switch (address)
        {
        case 0:     return readinputport(1) & 0x0f;     /* DSW1 low nibble  */
        case 1:     return readinputport(1) >> 4;       /* DSW1 high nibble */
        case 2:     return readinputport(0) & 0x0f;     /* DSW0 low nibble  */
        case 4:     return readinputport(0) >> 4;       /* DSW0 high nibble */
        case 6:     return readinputport(2) & 0x0f;     /* DSW2 / service   */
        case 3:
        case 5:
        case 7:     return 0;
        }
    }
    else if (mode == 5)
    {
        static int testvals[] = { 8, 4, 6, 14, 13, 9, 13 };
        if (address >= 1 && address <= 7)
            return testvals[address - 1];
    }

    return mappy_customio_2[address];
}


// ---------------------------------------------------------------------------
// Dig Dug 2 custom I/O chip 1
// ---------------------------------------------------------------------------

READ_HANDLER(digdug2_customio_r_1)
{
    static int crednum[] = { 1, 1, 2, 2 };
    static int credden[] = { 1, 2, 1, 3 };
    int val, temp;
    int mode = mappy_customio_1[8];

    if (mode == 1 || mode == 3)
    {
        switch (address)
        {
        case 0:
        {
            static int lastval;
            val = readinputport(4) & 0x0f;
            if ((val & 1) && ((val ^ lastval) & 1)) ++credits;
            return lastval = val;
        }
        case 1:
        {
            static int lastval;
            temp = (readinputport(0) >> 6) & 3;
            val  = readinputport(4) >> 4;
            if ((val & 1) && ((val ^ lastval) & 1))
                if (credits >= credden[temp]) credits -= credden[temp];
            if ((val & 2) && ((val ^ lastval) & 2))
                if (credits >= 2 * credden[temp]) credits -= 2 * credden[temp];
            return lastval = val;
        }
        case 2:
            temp = (readinputport(0) >> 6) & 3;
            return (credits * crednum[temp] / credden[temp]) / 10;
        case 3:
            temp = (readinputport(0) >> 6) & 3;
            return (credits * crednum[temp] / credden[temp]) % 10;
        case 4:     return readinputport(3) & 0x0f;
        case 5:     return readinputport(3) >> 4;
        case 6:
        case 7:     return 0;
        }
    }

    return mappy_customio_1[address];
}


// ---------------------------------------------------------------------------
// Dig Dug 2 custom I/O chip 2
// ---------------------------------------------------------------------------

READ_HANDLER(digdug2_customio_r_2)
{
    int mode = mappy_customio_2[8];

    if (mode == 4)
    {
        switch (address)
        {
        case 2:     return readinputport(0) & 0x0f;     /* DSW0 low  */
        case 4:     return readinputport(0) >> 4;       /* DSW0 high */
        case 5:     return readinputport(1) >> 4;       /* DSW1 high */
        case 6:     return readinputport(1) & 0x0f;     /* DSW1 low  */
        case 7:     return readinputport(2) & 0x0f;     /* service   */
        case 0:
        case 1:
        case 3:     return 0;
        }
    }

    return mappy_customio_2[address];
}


// ---------------------------------------------------------------------------
// Motos custom I/O chip 1
// ---------------------------------------------------------------------------
/*
READ_HANDLER(motos_customio_1_r)
{
    int val;
    int mode = mappy_customio_1[8];

    if (mode == 1)
    {
        switch (address)
        {
        case 0:
        {
            static int lastval;
            val = readinputport(3) & 0x0f;
            if ((val & 1) && ((val ^ lastval) & 1)) ++credits;
            return lastval = val;
        }
        case 1:     return readinputport(2) & 0x0f;     // player 1 joystick
        case 3:     return readinputport(3) >> 4;       // start buttons    
        case 9:
        case 2:
        case 4:
        case 5:
        case 6:
        case 7:     return 0;
        }
    }

    return mappy_customio_1[address];
}

// ---------------------------------------------------------------------------
// Motos custom I/O chip 2
// ---------------------------------------------------------------------------

READ_HANDLER(motos_customio_2_r)
{
    int mode = mappy_customio_2[8];

    if (mode == 9)
    {
        switch (address)
        {
        case 2:     return readinputport(0) & 0x0f;                       // DSW0 low       
        case 4:     return readinputport(0) >> 4;                         // DSW0 high      
        case 6:     return (readinputport(1) >> 4) | (readinputport(2) >> 4); // DSW1+buttons 
        case 0:
        case 1:
        case 3:
        case 5:
        case 7:     return 0;
        }
    }

    return mappy_customio_2[address];
}

*/

/*************************************************************************************
 *
 *         Motos custom I/O ports
 *
 *************************************************************************************/

READ_HANDLER(motos_customio_1_r)
{
    int val, mode = mappy_customio_1[8];
   
    LOG_DEBUG("I/O read 1: mode %d offset %d", mode, address);

    // mode 1 is the standard, and returns actual important values 
    if (mode == 1)
    {
        switch (address)
        {
        case 0:		// Coin slots, low nibble of port 3 
        {
            static int lastval;

            val = readinputport(3) & 0x0f;

            // bit 0 is a trigger for the coin slot 
            if ((val & 1) && ((val ^ lastval) & 1)) ++credits;

            return lastval = val;
        }

        case 1:		// Player 1 joystick 
            return readinputport(2) & 0x0f;
        case 3:		// Start buttons, high nibble of port 3 
            return readinputport(3) >> 4;
        case 9:
            return 0;
        case 2:
        case 4:
        case 5:
        case 6:
        case 7:		// Player 2 joystick 
            return readinputport(4) & 0x0f;
        }
    }
    else if (mode == 8)  // I/O tests chip 1 
    {
        switch (address)
        {
        case 0:
            return 0x06;
            break;
        case 1:
            return 0x09;
            break;
        default:
            // by default, return what was stored there 
            return mappy_customio_2[address];
        }
    }

    // by default, return what was stored there 
    return mappy_customio_1[address];
}


READ_HANDLER(motos_customio_2_r)
{
    int mode = mappy_customio_2[8];
   
    LOG_DEBUG("I/O read 2: mode %d, offset %d", mode, address);

    // mode 9 is the standard, and returns actual important values 
    if (mode == 9)
    {
        switch (address)
        {
        case 2:		// DSW0, low nibble 
            return readinputport(0) & 0x0f;

        case 4:		// DSW0, high nibble 
            return readinputport(0) >> 4;

        case 6:         // DSW1, high nibble + Player 1 buttons, high nibble + Player 2? button, high nibble 

            return (readinputport(1) >> 4) | (readinputport(2) >> 4) | (readinputport(4) >> 4);
        case 0:
        case 1:
        case 3:
        case 5:
        case 7:
            return 0;
        }
    }
    else if (mode == 8)  // I/O tests chip 2 
    {
        switch (address)
        {
        case 0:
            return 0x06;
            break;
        case 1:
            return 0x09;
            break;
        default:
            // by default, return what was stored there 
            return mappy_customio_2[address];
        }
    }

    // by default, return what was stored there 
    return mappy_customio_2[address];
}


// ---------------------------------------------------------------------------
// Tower of Druaga custom I/O chip 1
// ---------------------------------------------------------------------------

READ_HANDLER(todruaga_customio_r_1)
{
    static int crednum[] = { 1, 1, 2, 2 };
    static int credden[] = { 1, 2, 1, 3 };
    int val, temp;
    int mode = mappy_customio_1[8];

    if (mode == 1 || mode == 3)
    {
        switch (address)
        {
        case 0:
        {
            static int lastval;
            val = readinputport(5) & 0x0f;
            if ((val & 1) && ((val ^ lastval) & 1)) ++credits;
            return lastval = val;
        }
        case 1:
        {
            static int lastval;
            temp = (readinputport(0) >> 6) & 3;
            val  = readinputport(5) >> 4;
            if ((val & 1) && ((val ^ lastval) & 1))
                if (credits >= credden[temp]) credits -= credden[temp];
            if ((val & 2) && ((val ^ lastval) & 2))
                if (credits >= 2 * credden[temp]) credits -= 2 * credden[temp];
            return lastval = val;
        }
        case 2:
            temp = (readinputport(0) >> 6) & 3;
            return (credits * crednum[temp] / credden[temp]) / 10;
        case 3:
            temp = (readinputport(0) >> 6) & 3;
            return (credits * crednum[temp] / credden[temp]) % 10;
        case 4:     return readinputport(3) & 0x0f;
        case 5:     return readinputport(3) >> 4;
        case 6:     return 0;
        case 7:     return readinputport(4) >> 4;       /* extra buttons */
        }
    }

    return mappy_customio_1[address];
}


// ---------------------------------------------------------------------------
// Tower of Druaga custom I/O chip 2
// ---------------------------------------------------------------------------

READ_HANDLER(todruaga_customio_r_2)
{
    int mode = mappy_customio_2[8];

    if (mode == 4)
    {
        switch (address)
        {
        case 2:     return readinputport(0) & 0x0f;
        case 4:     return readinputport(0) >> 4;
        case 5:     return readinputport(1) >> 4;
        case 6:     return readinputport(1) & 0x0f;
        case 7:     return readinputport(2) & 0x0f;
        case 0:
        case 1:
        case 3:     return 0;
        }
    }

    return mappy_customio_2[address];
}


// ---------------------------------------------------------------------------
// Interrupt enable / generate for both CPUs
// The hardware uses address lines (not data) to set enable state.
// Writing to offset 2 enables; writing to offset 3 disables (or vice versa,
// the exact polarity is captured in the offset value the MAME source uses).
// ---------------------------------------------------------------------------

WRITE_HANDLER(mappy_interrupt_enable_1_w)
{
    interrupt_enable_1 = address & 1;
}

WRITE_HANDLER(mappy_interrupt_enable_2_w)
{
    interrupt_enable_2 = address & 1;
}

/* CPU1 VBLANK interrupt callback */
void mappy_interrupt_1(void)
{
    if (interrupt_enable_1)
        cpu_do_int_imm(CPU0, INT_TYPE_INT);
}

/* CPU2 VBLANK interrupt callback */
void mappy_interrupt_2(void)
{
    if (interrupt_enable_2)
        cpu_do_int_imm(CPU1, INT_TYPE_INT);
}

/* CPU2 (sound CPU) halt control.  offset 0 = halt, offset 1 = run */
WRITE_HANDLER(mappy_cpu_enable_w)
{
    /* address 0x500a = halt sound CPU, 0x500b = enable sound CPU */
    cpu_enable(CPU1, address & 1);
}


// ---------------------------------------------------------------------------
// Sound register write (CPU2 maps Namco sound at 0x0000-0x003f)
// ---------------------------------------------------------------------------

WRITE_HANDLER(mappy_sound_w)
{
    mappy_sound_w(address, data);
 }

/* sound enable register -- just pass through to Namco core */
WRITE_HANDLER(mappy_sound_enable_w)
{
    /* address offset 0 = disable, 1 = enable; data is unused by hardware */
    mappy_sound_enable_w(address, data);
}


// ---------------------------------------------------------------------------
// Video RAM / color RAM write-through handlers (mark dirty buffer entries)
// ---------------------------------------------------------------------------

WRITE_HANDLER(mappy_videoram_w)
{
    if (videoram[address] != (unsigned char)data)
    {
        dirtybuffer[address] = 1;
        videoram[address] = (unsigned char)data;
    }
}

WRITE_HANDLER(mappy_colorram_w)
{
    if (colorram[address] != (unsigned char)data)
    {
        dirtybuffer[address] = 1;
        colorram[address] = (unsigned char)data;
    }
}

/* scroll register: the hardware maps a 0x800-byte window, with the actual
   scroll value encoded in the upper address bits (>>3) */
WRITE_HANDLER(mappy_scroll_w)
{
    mappy_scroll = (unsigned char)(address >> 3);
}


// ---------------------------------------------------------------------------
// GFX layouts
// ---------------------------------------------------------------------------

/* 8x8 characters, 2bpp, rotated 90 degrees in ROM */
static struct GfxLayout mappy_charlayout =
{
    8, 8,           /* 8x8 tile size */
    256,            /* 256 characters */
    2,              /* 2 bits per pixel */
    { 0, 4 },       /* bitplanes packed 4 pixels per byte */
    { 7*8, 6*8, 5*8, 4*8, 3*8, 2*8, 1*8, 0*8 },   /* rotated 90 degrees */
    { 8*8+0, 8*8+1, 8*8+2, 8*8+3, 0, 1, 2, 3 },   /* bits packed in groups of four */
    16 * 8          /* 16 bytes per character */
};

/* 16x16 sprites, 4bpp, 128 sprites (mappy, todruaga low count) */
static struct GfxLayout mappy_spritelayout =
{
    16, 16,         /* 16x16 sprite size */
    128,            /* 128 sprites */
    4,              /* 4 bits per pixel */
    { 0, 4, 8192*8, 8192*8+4 }, /* two bitplane pairs, second pair offset 8k bytes */
    { 39*8, 38*8, 37*8, 36*8, 35*8, 34*8, 33*8, 32*8,
       7*8,  6*8,  5*8,  4*8,  3*8,  2*8,  1*8,  0*8 },
    { 0, 1, 2, 3, 8*8+0, 8*8+1, 8*8+2, 8*8+3,
      16*8+0, 16*8+1, 16*8+2, 16*8+3,
      24*8+0, 24*8+1, 24*8+2, 24*8+3 },
    64 * 8          /* 64 bytes per sprite */
};

/* 16x16 sprites, 4bpp, 256 sprites (digdug2, motos have more sprite ROM) */
static struct GfxLayout digdug2_spritelayout =
{
    16, 16,
    256,            /* 256 sprites */
    4,
    { 0, 4, 16384*8, 16384*8+4 }, /* second bitplane pair at 16k bytes */
    { 39*8, 38*8, 37*8, 36*8, 35*8, 34*8, 33*8, 32*8,
       7*8,  6*8,  5*8,  4*8,  3*8,  2*8,  1*8,  0*8 },
    { 0, 1, 2, 3, 8*8+0, 8*8+1, 8*8+2, 8*8+3,
      16*8+0, 16*8+1, 16*8+2, 16*8+3,
      24*8+0, 24*8+1, 24*8+2, 24*8+3 },
    64 * 8
};


/* Mappy GFX decode: chars from offset 0, sprites from offset 0x1000 in GFX1 */
struct GfxDecodeInfo mappy_gfxdecodeinfo[] =
{
    { REGION_GFX1, 0x0000, &mappy_charlayout,         0, 64 },
    { REGION_GFX1, 0x1000, &mappy_spritelayout,    64*4, 16 },
    { -1 }
};

/* Dig Dug 2 / Motos use more sprite ROM (256 sprites) */
struct GfxDecodeInfo digdug2_gfxdecodeinfo[] =
{
    { REGION_GFX1, 0x0000, &mappy_charlayout,         0, 64 },
    { REGION_GFX1, 0x1000, &digdug2_spritelayout,  64*4, 16 },
    { -1 }
};

/* Tower of Druaga: same as mappy layout but 64 sprite color sets instead of 16 */
struct GfxDecodeInfo todruaga_gfxdecodeinfo[] =
{
    { REGION_GFX1, 0x0000, &mappy_charlayout,         0, 64 },
    { REGION_GFX1, 0x1000, &mappy_spritelayout,    64*4, 64 },
    { -1 }
};


// ---------------------------------------------------------------------------
// Video start / stop / refresh -- implementation is in mappy_video.cpp
// Declarations here; the actual code lives in a companion file following the
// same split used in the original MAME source (vidhrdw/mappy.c).
// ---------------------------------------------------------------------------

/* mappy_scroll is read by mappy_vh_screenrefresh; exposed via mappy.h */
unsigned char mappy_scroll = 0;

/* forward declarations implemented in mappy_video.cpp */
extern int  mappy_vh_start(void);
extern int  motos_vh_start(void);
extern void mappy_vh_stop(void);
extern void mappy_vh_screenrefresh(struct osd_bitmap* bitmap, int full_refresh);


// ---------------------------------------------------------------------------
// run_* callbacks: called every frame by the AAE emulator core
// ---------------------------------------------------------------------------

void run_mappy(void)
{
    watchdog_reset_w(0, 0, 0);
    mappy_vh_screenrefresh(Machine->scrbitmap, 0);
    namco_sh_update();
}

/* motos uses the same run loop; the motos_vh_start sets a mode flag
   that causes mappy_vh_screenrefresh to apply a 1-pixel sprite offset */
void run_motos(void)
{
    watchdog_reset_w(0, 0, 0);
    mappy_vh_screenrefresh(Machine->scrbitmap, 0);
    namco_sh_update();
}


// ---------------------------------------------------------------------------
// init_* functions: pointer fixup and subsystem startup
// ---------------------------------------------------------------------------

int init_mappy(void)
{
    /* video RAM layout: chars at 0x0000, sprites in three banks */
    videoram       = &Machine->memory_region[CPU0][0x0000];
    videoram_size  = 0x0800;
    colorram       = &Machine->memory_region[CPU0][0x0800];

    spriteram      = &Machine->memory_region[CPU0][0x1780];
    spriteram_size = 0x0080;
    spriteram_2    = &Machine->memory_region[CPU0][0x1f80];
    spriteram_3    = &Machine->memory_region[CPU0][0x2780];

    /* point shared RAM at CPU1 address space starting at 0x4040 */
    mappy_sharedram = &Machine->memory_region[CPU0][0x4040];
    mappy_customio_1 = &Machine->memory_region[CPU0][0x4800];
    mappy_customio_2 = &Machine->memory_region[CPU0][0x4810];

    /* start sound CPU halted; main CPU will enable it via mappy_cpu_enable_w */
    cpu_enable(CPU1, 0);

    mappy_init_machine();
    mappy_vh_start();
    namco_sh_start(&namco_interface);

    interrupt_enable_1 = 0;
    interrupt_enable_2 = 0;
    cpu_setOPbaseoverride(nullptr);

    return 1;
}

void end_mappy(void)
{
    mappy_vh_stop();
}

/* Dig Dug 2: same init, different ROM base (8000-ffff vs a000-ffff) */
int init_digdug2(void)
{
    videoram       = &Machine->memory_region[CPU0][0x0000];
    videoram_size  = 0x0800;
    colorram       = &Machine->memory_region[CPU0][0x0800];

    spriteram      = &Machine->memory_region[CPU0][0x1780];
    spriteram_size = 0x0080;
    spriteram_2    = &Machine->memory_region[CPU0][0x1f80];
    spriteram_3    = &Machine->memory_region[CPU0][0x2780];

    mappy_sharedram  = &Machine->memory_region[CPU0][0x4040];
    mappy_customio_1 = &Machine->memory_region[CPU0][0x4800];
    mappy_customio_2 = &Machine->memory_region[CPU0][0x4810];

    cpu_enable(CPU1, 0);

    mappy_init_machine();
    mappy_vh_start();
    namco_sh_start(&namco_interface);

    interrupt_enable_1 = 0;
    interrupt_enable_2 = 0;
    cpu_setOPbaseoverride(nullptr);
    m6809_slapstic = 0;

    return 1;
}

void end_digdug2(void)
{
    mappy_vh_stop();
}

/* Motos: same layout, motos_vh_start sets the 1-pixel sprite offset mode */
int init_motos(void)
{
    videoram       = &Machine->memory_region[CPU0][0x0000];
    videoram_size  = 0x0800;
    colorram       = &Machine->memory_region[CPU0][0x0800];

    spriteram      = &Machine->memory_region[CPU0][0x1780];
    spriteram_size = 0x0080;
    spriteram_2    = &Machine->memory_region[CPU0][0x1f80];
    spriteram_3    = &Machine->memory_region[CPU0][0x2780];

    mappy_sharedram  = &Machine->memory_region[CPU0][0x4040];
    mappy_customio_1 = &Machine->memory_region[CPU0][0x4800];
    mappy_customio_2 = &Machine->memory_region[CPU0][0x4810];
 
    cpu_enable(CPU1, 0);
    credits = 3;
    motos_init_machine();
    motos_vh_start();   /* sets motos_special_display flag */
    namco_sh_start(&namco_interface);

    interrupt_enable_1 = 0;
    interrupt_enable_2 = 0;
    cpu_setOPbaseoverride(nullptr);
    m6809_slapstic = 0;

    return 1;
}

void end_motos(void)
{
    mappy_vh_stop();
}

/* Tower of Druaga: same layout as digdug2 */
int init_todruaga(void)
{
    videoram       = &Machine->memory_region[CPU0][0x0000];
    videoram_size  = 0x0800;
    colorram       = &Machine->memory_region[CPU0][0x0800];

    spriteram      = &Machine->memory_region[CPU0][0x1780];
    spriteram_size = 0x0080;
    spriteram_2    = &Machine->memory_region[CPU0][0x1f80];
    spriteram_3    = &Machine->memory_region[CPU0][0x2780];

    mappy_sharedram  = &Machine->memory_region[CPU0][0x4040];
    mappy_customio_1 = &Machine->memory_region[CPU0][0x4800];
    mappy_customio_2 = &Machine->memory_region[CPU0][0x4810];

    cpu_enable(CPU1, 0);

    mappy_init_machine();
    mappy_vh_start();
    namco_sh_start(&namco_interface);

    interrupt_enable_1 = 0;
    interrupt_enable_2 = 0;
    cpu_setOPbaseoverride(nullptr);

    return 1;
}

void end_todruaga(void)
{
    mappy_vh_stop();
}


// ---------------------------------------------------------------------------
// Memory maps
// ---------------------------------------------------------------------------

/*
 * CPU1 read map -- mappy
 * ROM lives at a000-ffff; RAM and I/O fill in the rest.
 * The mappy_cpu1ram_r handler covers everything not explicitly mapped and
 * also provides idle-loop detection.
 */
MEM_READ(mappy_readmem_cpu1)
MEM_ADDR(0xa000, 0xffff, MRA_ROM)
MEM_ADDR(0x4040, 0x43ff, mappy_sharedram_r)
MEM_ADDR(0x4800, 0x480f, mappy_customio_r_1)
MEM_ADDR(0x4810, 0x481f, mappy_customio_r_2)
MEM_ADDR(0x0000, 0x9fff, mappy_cpu1ram_r)
MEM_END

/* CPU1 read map -- Dig Dug 2 (ROM at 8000-ffff) */
MEM_READ(digdug2_readmem_cpu1)
MEM_ADDR(0x8000, 0xffff, MRA_ROM)
MEM_ADDR(0x4040, 0x43ff, mappy_sharedram_r)
MEM_ADDR(0x4820, 0x4bff, MRA_RAM)
MEM_ADDR(0x4800, 0x480f, digdug2_customio_r_1)
MEM_ADDR(0x4810, 0x481f, digdug2_customio_r_2)
MEM_ADDR(0x0000, 0x7fff, digdug2_cpu1ram_r)
MEM_END

/* CPU1 read map -- Motos */
MEM_READ(motos_readmem_cpu1)
MEM_ADDR(0x8000, 0xffff, MRA_ROM)
MEM_ADDR(0x4040, 0x43ff, mappy_sharedram_r)
MEM_ADDR(0x4800, 0x480f, motos_customio_1_r)
MEM_ADDR(0x4810, 0x481f, motos_customio_2_r)
MEM_ADDR(0x0000, 0x7fff, motos_cpu1ram_r)
MEM_END

/* CPU1 read map -- Tower of Druaga */
MEM_READ(todruaga_readmem_cpu1)
MEM_ADDR(0x8000, 0xffff, MRA_ROM)
MEM_ADDR(0x4040, 0x43ff, mappy_sharedram_r)
MEM_ADDR(0x4800, 0x480f, todruaga_customio_r_1)
MEM_ADDR(0x4810, 0x481f, todruaga_customio_r_2)
MEM_ADDR(0x0000, 0x7fff, todruaga_cpu1ram_r)
MEM_END

/*
 * CPU1 write map -- shared by all variants
 * Sprite RAM banks are mapped as plain MWA_RAM; the pointers set in init_*
 * point into the correct locations inside Memory_region[CPU0].
 */
MEM_WRITE(mappy_writemem_cpu1)
MEM_ADDR(0x0000, 0x07ff, mappy_videoram_w)
MEM_ADDR(0x0800, 0x0fff, mappy_colorram_w)
MEM_ADDR(0x1000, 0x177f, MWA_RAM)
MEM_ADDR(0x1780, 0x17ff, MWA_RAM)      /* sprite RAM area 1 */
MEM_ADDR(0x1800, 0x1f7f, MWA_RAM)
MEM_ADDR(0x1f80, 0x1fff, MWA_RAM)      /* sprite RAM area 2 */
MEM_ADDR(0x2000, 0x277f, MWA_RAM)
MEM_ADDR(0x2780, 0x27ff, MWA_RAM)      /* sprite RAM area 3 */
MEM_ADDR(0x3800, 0x3fff, mappy_scroll_w)
MEM_ADDR(0x4040, 0x43ff, mappy_sharedram_w)
MEM_ADDR(0x4820, 0x4bff, MWA_RAM)      /* extra RAM for digdug2 / motos */
MEM_ADDR(0x4800, 0x480f, mappy_customio_w_1)
MEM_ADDR(0x4810, 0x481f, mappy_customio_w_2)
MEM_ADDR(0x5002, 0x5003, mappy_interrupt_enable_1_w)
MEM_ADDR(0x500a, 0x500b, mappy_cpu_enable_w)
MEM_ADDR(0x8000, 0x8000, watchdog_reset_w)
MEM_ADDR(0x8001, 0xffff, MWA_ROM)
MEM_END

/* CPU2 (sound) read -- mappy */
MEM_READ(mappy_readmem_cpu2)
MEM_ADDR(0xe000, 0xffff, MRA_ROM)
MEM_ADDR(0x0040, 0x03ff, mappy_sharedram_r2)
MEM_ADDR(0x0000, 0x003f, MRA_RAM)      /* Namco sound register readback */
MEM_END

/* CPU2 read -- Dig Dug 2 */
MEM_READ(digdug2_readmem_cpu2)
MEM_ADDR(0xe000, 0xffff, MRA_ROM)
MEM_ADDR(0x0040, 0x03ff, digdug2_sharedram_r2)
MEM_ADDR(0x0000, 0x003f, MRA_RAM)
MEM_END

/* CPU2 read -- Motos */
MEM_READ(motos_readmem_cpu2)
MEM_ADDR(0xe000, 0xffff, MRA_ROM)
MEM_ADDR(0x0040, 0x03ff, motos_sharedram_r2)
MEM_ADDR(0x0000, 0x003f, MRA_RAM)
MEM_END

/* CPU2 read -- Tower of Druaga (same idle handler as motos) */
MEM_READ(todruaga_readmem_cpu2)
MEM_ADDR(0xe000, 0xffff, MRA_ROM)
MEM_ADDR(0x0040, 0x03ff, todruaga_sharedram_r2)
MEM_ADDR(0x0000, 0x003f, MRA_RAM)
MEM_END

/* CPU2 write -- shared by all variants */
MEM_WRITE(mappy_writemem_cpu2)
MEM_ADDR(0xe000, 0xffff, MWA_ROM)
MEM_ADDR(0x0040, 0x03ff, mappy_sharedram_w)
MEM_ADDR(0x0000, 0x003f, mappy_sound_w)
MEM_ADDR(0x2000, 0x2001, mappy_interrupt_enable_2_w)
MEM_ADDR(0x2006, 0x2007, mappy_sound_enable_w)
MEM_END


// ---------------------------------------------------------------------------
// Input ports
// ---------------------------------------------------------------------------

/*
 * Mappy input layout:
 *   Port 0 = DSW0  (difficulty, demo sounds, rack test, freeze)
 *   Port 1 = DSW1  (coins, bonus, lives)
 *   Port 2 = DSW2  (cabinet orientation, service mode)
 *   Port 3 = joystick + button (FAKE -- read by custom I/O chip emulation)
 *   Port 4 = coins + start buttons (FAKE)
 */
INPUT_PORTS_START(mappy)

PORT_START("DSW0")
PORT_DIPNAME(0x03, 0x00, DEF_STR(Difficulty))
PORT_DIPSETTING(0x00, "Easy")
PORT_DIPSETTING(0x01, "Medium")
PORT_DIPSETTING(0x02, "Hard")
PORT_DIPSETTING(0x03, "Hardest")
PORT_BIT(0x1c, IP_ACTIVE_HIGH, IPT_UNUSED)
PORT_DIPNAME(0x20, 0x00, DEF_STR(Demo_Sounds))
PORT_DIPSETTING(0x20, DEF_STR(Off))
PORT_DIPSETTING(0x00, DEF_STR(On))
PORT_BITX(0x40, 0x00, IPT_DIPSWITCH_NAME | IPF_CHEAT, "Rack Test", OSD_KEY_F1, IP_JOY_NONE)
PORT_DIPSETTING(0x00, DEF_STR(Off))
PORT_DIPSETTING(0x40, DEF_STR(On))
PORT_DIPNAME(0x80, 0x00, "Freeze")
PORT_DIPSETTING(0x00, DEF_STR(Off))
PORT_DIPSETTING(0x80, DEF_STR(On))

PORT_START("DSW1")
PORT_DIPNAME(0x07, 0x00, DEF_STR(Coinage))
PORT_DIPSETTING(0x00, DEF_STR(1C_1C))
PORT_DIPSETTING(0x01, DEF_STR(1C_2C))
PORT_DIPSETTING(0x02, DEF_STR(1C_3C))
PORT_DIPSETTING(0x03, "1C/6C")
PORT_DIPSETTING(0x04, DEF_STR(2C_1C))
PORT_DIPSETTING(0x05, DEF_STR(2C_3C))
PORT_DIPSETTING(0x06, DEF_STR(3C_1C))
PORT_DIPSETTING(0x07, DEF_STR(3C_2C))
PORT_DIPNAME(0x38, 0x00, DEF_STR(Bonus_Life))
PORT_DIPSETTING(0x38, "None")
PORT_DIPSETTING(0x20, "20k")
PORT_DIPSETTING(0x08, "20k 60k")
PORT_DIPSETTING(0x00, "20k 70k")
PORT_DIPSETTING(0x10, "20k 80k")
PORT_DIPSETTING(0x18, "30k 100k")
PORT_DIPSETTING(0x28, "20k 70k 70k")
PORT_DIPSETTING(0x30, "20k 80k 80k")
PORT_DIPNAME(0xc0, 0x00, DEF_STR(Lives))
PORT_DIPSETTING(0x80, "1")
PORT_DIPSETTING(0xc0, "2")
PORT_DIPSETTING(0x00, "3")
PORT_DIPSETTING(0x40, "5")

PORT_START("DSW2")
PORT_BIT(0x03, IP_ACTIVE_HIGH, IPT_UNUSED)
PORT_DIPNAME(0x04, 0x00, DEF_STR(Cabinet))
PORT_DIPSETTING(0x00, DEF_STR(Upright))
PORT_DIPSETTING(0x04, DEF_STR(Cocktail))
PORT_BITX(0x08, 0x00, IPT_DIPSWITCH_NAME | IPF_TOGGLE, "Service Mode", OSD_KEY_F2, IP_JOY_NONE)
PORT_DIPSETTING(0x00, DEF_STR(Off))
PORT_DIPSETTING(0x08, DEF_STR(On))
PORT_BIT(0xf0, IP_ACTIVE_HIGH, IPT_UNUSED)

PORT_START("IO1")   /* FAKE: joystick -- read by mappy_customio_r_1 port 3 */
PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_UNUSED)
PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_JOYSTICK_RIGHT | IPF_2WAY)
PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_UNUSED)
PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_JOYSTICK_LEFT | IPF_2WAY)
PORT_BIT_IMPULSE(0x10, IP_ACTIVE_HIGH, IPT_BUTTON1, 1)
PORT_BITX(0x20, IP_ACTIVE_HIGH, IPT_BUTTON1, 0, IP_KEY_PREVIOUS, IP_JOY_PREVIOUS)
PORT_BIT(0xc0, IP_ACTIVE_HIGH, IPT_UNUSED)

PORT_START("IO2")   /* FAKE: coins and start -- read by mappy_customio_r_1 port 4 */
PORT_BIT_IMPULSE(0x01, IP_ACTIVE_HIGH, IPT_COIN1, 1)
PORT_BIT_IMPULSE(0x02, IP_ACTIVE_HIGH, IPT_COIN2, 1)
PORT_BIT(0x0c, IP_ACTIVE_HIGH, IPT_UNUSED)
PORT_BIT_IMPULSE(0x10, IP_ACTIVE_HIGH, IPT_START1, 1)
PORT_BIT_IMPULSE(0x20, IP_ACTIVE_HIGH, IPT_START2, 1)
PORT_BIT(0xc0, IP_ACTIVE_HIGH, IPT_UNUSED)

INPUT_PORTS_END


INPUT_PORTS_START(digdug2)

PORT_START("DSW0")
PORT_BIT(0x1f, IP_ACTIVE_HIGH, IPT_UNUSED)
PORT_DIPNAME(0x20, 0x00, DEF_STR(Lives))
PORT_DIPSETTING(0x00, "3")
PORT_DIPSETTING(0x20, "5")
PORT_DIPNAME(0xc0, 0x00, DEF_STR(Coinage))
PORT_DIPSETTING(0x00, DEF_STR(1C_1C))
PORT_DIPSETTING(0x40, DEF_STR(2C_1C))
PORT_DIPSETTING(0x80, DEF_STR(1C_2C))
PORT_DIPSETTING(0xc0, DEF_STR(3C_1C))

PORT_START("DSW1")
PORT_DIPNAME(0x03, 0x00, "Extend")
PORT_DIPSETTING(0x00, "Type A")
PORT_DIPSETTING(0x02, "Type B")
PORT_DIPSETTING(0x01, "Type C")
PORT_DIPSETTING(0x03, "Type D")
PORT_DIPNAME(0x04, 0x00, "Level Select")
PORT_DIPSETTING(0x00, DEF_STR(Off))
PORT_DIPSETTING(0x04, DEF_STR(On))
PORT_DIPNAME(0x08, 0x00, "Freeze")
PORT_DIPSETTING(0x00, DEF_STR(Off))
PORT_DIPSETTING(0x08, DEF_STR(On))
PORT_BIT_IMPULSE(0x10, IP_ACTIVE_HIGH, IPT_BUTTON2, 1)
PORT_BITX(0x20, IP_ACTIVE_HIGH, IPT_BUTTON2, 0, IP_KEY_PREVIOUS, IP_JOY_PREVIOUS)
PORT_BIT(0x40, IP_ACTIVE_HIGH, IPT_UNUSED)
PORT_DIPNAME(0x80, 0x00, DEF_STR(Cabinet))
PORT_DIPSETTING(0x00, DEF_STR(Upright))
PORT_DIPSETTING(0x80, DEF_STR(Cocktail))

PORT_START("DSW2")
PORT_BIT(0x07, IP_ACTIVE_HIGH, IPT_UNUSED)
PORT_BITX(0x08, 0x00, IPT_DIPSWITCH_NAME | IPF_TOGGLE, "Service Mode", OSD_KEY_F2, IP_JOY_NONE)
PORT_DIPSETTING(0x00, DEF_STR(Off))
PORT_DIPSETTING(0x08, DEF_STR(On))
PORT_BIT(0xf0, IP_ACTIVE_HIGH, IPT_UNUSED)

PORT_START("IO1")   /* FAKE: joystick */
PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_JOYSTICK_UP    | IPF_4WAY)
PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_JOYSTICK_RIGHT | IPF_4WAY)
PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_JOYSTICK_DOWN  | IPF_4WAY)
PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_JOYSTICK_LEFT  | IPF_4WAY)
PORT_BIT_IMPULSE(0x10, IP_ACTIVE_HIGH, IPT_BUTTON1, 1)
PORT_BITX(0x20, IP_ACTIVE_HIGH, IPT_BUTTON1, 0, IP_KEY_PREVIOUS, IP_JOY_PREVIOUS)
PORT_BIT(0xc0, IP_ACTIVE_HIGH, IPT_UNUSED)

PORT_START("IO2")   /* FAKE: coins and start */
PORT_BIT_IMPULSE(0x01, IP_ACTIVE_HIGH, IPT_COIN1, 1)
PORT_BIT_IMPULSE(0x02, IP_ACTIVE_HIGH, IPT_COIN2, 1)
PORT_BIT(0x0c, IP_ACTIVE_HIGH, IPT_UNUSED)
PORT_BIT_IMPULSE(0x10, IP_ACTIVE_HIGH, IPT_START1, 1)
PORT_BIT_IMPULSE(0x20, IP_ACTIVE_HIGH, IPT_START2, 1)
PORT_BIT(0xc0, IP_ACTIVE_HIGH, IPT_UNUSED)

INPUT_PORTS_END


INPUT_PORTS_START(motos)
PORT_START("DSW0")
PORT_DIPNAME(0x01, 0x00, "Reset")
PORT_DIPSETTING(0x00, "Off")
PORT_DIPSETTING(0x01, "On")
PORT_DIPNAME(0x06, 0x00, DEF_STR(Coinage))
PORT_DIPSETTING(0x00, DEF_STR(1C_1C))
PORT_DIPSETTING(0x02, DEF_STR(1C_2C))
PORT_DIPSETTING(0x04, DEF_STR(2C_1C))
PORT_DIPSETTING(0x06, DEF_STR(3C_1C))
PORT_DIPNAME(0x08, 0x00, "Motos")
PORT_DIPSETTING(0x00, "3")
PORT_DIPSETTING(0x08, "5")
PORT_DIPNAME(0x10, 0x00, "Rank")
PORT_DIPSETTING(0x00, "A")
PORT_DIPSETTING(0x10, "B")
PORT_DIPNAME(0x60, 0x00, DEF_STR(Bonus_Life))
PORT_DIPSETTING(0x00, "10k 30k 50k")
PORT_DIPSETTING(0x20, "20k 50k")
PORT_DIPSETTING(0x40, "30k 70k")
PORT_DIPSETTING(0x60, "20k 70k")
PORT_DIPNAME(0x80, 0x00, DEF_STR(Demo_Sounds))
PORT_DIPSETTING(0x80, DEF_STR(Off))
PORT_DIPSETTING(0x00, DEF_STR(On))

PORT_START ("DSW1")     /* DSW1 */
PORT_BIT(0x3f, IP_ACTIVE_HIGH, IPT_UNUSED)
PORT_DIPNAME(0x40, 0x00, "Orientation")
PORT_DIPSETTING(0x00, "Upright")
PORT_DIPSETTING(0x40, "Cocktail")
PORT_BITX(0x80, 0x00, IPT_DIPSWITCH_NAME | IPF_TOGGLE, "Service Mode", OSD_KEY_F2, IP_JOY_NONE)
PORT_DIPSETTING(0x00, "Off")
PORT_DIPSETTING(0x80, "On")

PORT_START("IO1")   /* FAKE: joystick (8-way) */
PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_JOYSTICK_UP    | IPF_8WAY)
PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_JOYSTICK_RIGHT | IPF_8WAY)
PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_JOYSTICK_DOWN  | IPF_8WAY)
PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_JOYSTICK_LEFT  | IPF_8WAY)
PORT_BIT_IMPULSE(0x10, IP_ACTIVE_HIGH, IPT_BUTTON1, 2)
PORT_BITX(0x20, IP_ACTIVE_HIGH, IPT_BUTTON1, 0, IP_KEY_PREVIOUS, IP_JOY_PREVIOUS)
PORT_BIT(0xc0, IP_ACTIVE_HIGH, IPT_UNUSED)

PORT_START("IO2")   /* FAKE: coins and start */
PORT_BIT_IMPULSE(0x01, IP_ACTIVE_HIGH, IPT_COIN1, 2)
PORT_BIT_IMPULSE(0x02, IP_ACTIVE_HIGH, IPT_COIN2, 2)
PORT_BIT(0x0c, IP_ACTIVE_HIGH, IPT_UNUSED)
PORT_BIT_IMPULSE(0x40, IP_ACTIVE_HIGH, IPT_START1, 2)
PORT_BIT_IMPULSE(0x80, IP_ACTIVE_HIGH, IPT_START2, 2)
PORT_BIT(0x30, IP_ACTIVE_HIGH, IPT_UNUSED)
INPUT_PORTS_END


INPUT_PORTS_START(todruaga)

PORT_START("DSW0")
PORT_BIT(0x0f, IP_ACTIVE_HIGH, IPT_UNUSED)
PORT_DIPNAME(0x30, 0x00, DEF_STR(Lives))
PORT_DIPSETTING(0x20, "1")
PORT_DIPSETTING(0x10, "2")
PORT_DIPSETTING(0x00, "3")
PORT_DIPSETTING(0x30, "5")
PORT_DIPNAME(0xc0, 0x00, "Left Coin")
PORT_DIPSETTING(0x00, DEF_STR(1C_1C))
PORT_DIPSETTING(0x40, DEF_STR(2C_1C))
PORT_DIPSETTING(0x80, DEF_STR(1C_2C))
PORT_DIPSETTING(0xc0, DEF_STR(3C_1C))

PORT_START("DSW1")
PORT_DIPNAME(0x01, 0x00, "Freeze")
PORT_DIPSETTING(0x00, DEF_STR(Off))
PORT_DIPSETTING(0x01, DEF_STR(On))
PORT_DIPNAME(0x02, 0x00, "Reset")
PORT_DIPSETTING(0x00, DEF_STR(Off))
PORT_DIPSETTING(0x02, DEF_STR(On))
PORT_DIPNAME(0x0c, 0x00, "Right Coin")
PORT_DIPSETTING(0x00, DEF_STR(1C_1C))
PORT_DIPSETTING(0x04, DEF_STR(2C_1C))
PORT_DIPSETTING(0x08, DEF_STR(1C_2C))
PORT_DIPSETTING(0x0c, DEF_STR(3C_1C))
PORT_BIT(0x70, IP_ACTIVE_HIGH, IPT_UNUSED)
PORT_DIPNAME(0x80, 0x00, DEF_STR(Cabinet))
PORT_DIPSETTING(0x00, DEF_STR(Upright))
PORT_DIPSETTING(0x80, DEF_STR(Cocktail))

PORT_START("DSW2")
PORT_BIT(0x07, IP_ACTIVE_HIGH, IPT_UNUSED)
PORT_BITX(0x08, 0x00, IPT_DIPSWITCH_NAME | IPF_TOGGLE, "Service Mode", OSD_KEY_F2, IP_JOY_NONE)
PORT_DIPSETTING(0x00, DEF_STR(Off))
PORT_DIPSETTING(0x08, DEF_STR(On))
PORT_BIT(0xf0, IP_ACTIVE_HIGH, IPT_UNUSED)

PORT_START("IO1")   /* FAKE: joystick (4-way) */
PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_JOYSTICK_UP    | IPF_4WAY)
PORT_BIT(0x02, IP_ACTIVE_HIGH, IPT_JOYSTICK_RIGHT | IPF_4WAY)
PORT_BIT(0x04, IP_ACTIVE_HIGH, IPT_JOYSTICK_DOWN  | IPF_4WAY)
PORT_BIT(0x08, IP_ACTIVE_HIGH, IPT_JOYSTICK_LEFT  | IPF_4WAY)
PORT_BIT_IMPULSE(0x10, IP_ACTIVE_HIGH, IPT_BUTTON1, 1)
PORT_BITX(0x20, IP_ACTIVE_HIGH, IPT_BUTTON1, 0, IP_KEY_PREVIOUS, IP_JOY_PREVIOUS)
PORT_BIT(0xc0, IP_ACTIVE_HIGH, IPT_UNUSED)

PORT_START("IO2")   /* FAKE: extra buttons (read by todruaga_customio_r_1 port 4) */
PORT_BIT(0x0f, IP_ACTIVE_HIGH, IPT_UNUSED)
PORT_BIT_IMPULSE(0x10, IP_ACTIVE_HIGH, IPT_BUTTON2, 1)
PORT_BITX(0x20, IP_ACTIVE_HIGH, IPT_BUTTON2, 0, IP_KEY_PREVIOUS, IP_JOY_PREVIOUS)
PORT_BIT(0xc0, IP_ACTIVE_HIGH, IPT_UNUSED)

PORT_START("IO3")   /* FAKE: coins and start (port 5 in todruaga I/O) */
PORT_BIT_IMPULSE(0x01, IP_ACTIVE_HIGH, IPT_COIN1, 1)
PORT_BIT_IMPULSE(0x02, IP_ACTIVE_HIGH, IPT_COIN2, 1)
PORT_BIT(0x0c, IP_ACTIVE_HIGH, IPT_UNUSED)
PORT_BIT_IMPULSE(0x10, IP_ACTIVE_HIGH, IPT_START1, 1)
PORT_BIT_IMPULSE(0x20, IP_ACTIVE_HIGH, IPT_START2, 1)
PORT_BIT(0xc0, IP_ACTIVE_HIGH, IPT_UNUSED)

INPUT_PORTS_END


// ---------------------------------------------------------------------------
// ROM definitions
// The GFX region (REGION_GFX1) is used as a temporary decode buffer that
// becomes permanent after mappy_vh_convert_color_prom runs.
// ---------------------------------------------------------------------------

ROM_START(mappy)
/* CPU1: 3 x 8k ROMs mapped at a000-ffff */
ROM_REGION(0x10000, REGION_CPU1, 0)
ROM_LOAD("mpx_3.1d", 0xa000, 0x2000, CRC(52e6c708) SHA1(b9722941438e93325e84691ada4e95620bec73b2))
ROM_LOAD("mp1_2.1c", 0xc000, 0x2000, CRC(a958a61c) SHA1(e5198703cdf47b2cd7fc9f2a5fde7bf4ab2275db))
ROM_LOAD("mpx_1.1b", 0xe000, 0x2000, CRC(203766d4) SHA1(1dbc4f42d4c16a08240a221bec27dcc3a8dd7461))

/* GFX: chars at 0, two sprite bitplane halves at 1000 and 3000 */
ROM_REGION(0x5000, REGION_GFX1, ROMREGION_DISPOSE)
ROM_LOAD("mp1_5.3b", 0x0000, 0x1000, CRC(16498b9f) SHA1(76610149c65f955484fef1c033ddc3fed3f4e568))
ROM_LOAD("mp1_6.3m", 0x1000, 0x2000, CRC(f2d9647a) SHA1(3cc216793c6a5f73c437ad2524563deb3b5e2890))
ROM_LOAD("mp1_7.3n", 0x3000, 0x2000, CRC(757cf2b6) SHA1(8dfbf03953d5219d9eb5fc654ec3392442ba1dc4))

/* CPU2 (sound): 8k ROM at e000-ffff */
ROM_REGION(0x10000, REGION_CPU2, 0)
ROM_LOAD("mp1_4.1k", 0xe000, 0x2000, CRC(8182dd5b) SHA1(f36b57f7f1e79f00b3f07afe1960bca5f5325ee2))

/* Color PROMs: 32-byte palette + 256-byte char lookup + 256-byte sprite lookup */
ROM_REGION(0x0220, REGION_PROMS, 0)
ROM_LOAD("mp1-5.5b", 0x0000, 0x0020, CRC(56531268) SHA1(2e356706c07f43eeb67783fb122bdc7fed1b3589))	/* palette */
ROM_LOAD("mp1-6.4c", 0x0020, 0x0100, CRC(50765082) SHA1(f578e14f15783acb2073644db4a2f0d196cc0957))	/* characters */
ROM_LOAD("mp1-7.5k", 0x0120, 0x0100, CRC(5396bd78) SHA1(2e387e5d8b8cab005f67f821b4db65d0ae8bd362))	/* sprites */

/* Sound PROM: 256-byte waveform table for Namco WSG */
ROM_REGION(0x0100, REGION_SOUND1, 0)
ROM_LOAD("mp1-3.3m", 0x0000, 0x0100, CRC(16a9166a) SHA1(847cbaf7c88616576c410177e066ae1d792ac0ba))
ROM_END

ROM_START(mappyjp)
ROM_REGION(0x10000, REGION_CPU1, 0)
ROM_LOAD("mp1_3.1d", 0xa000, 0x2000, CRC(db9d5ab5) SHA1(32a0190f96f9c00c541b24dd17d6ad487938a8bf))
ROM_LOAD("mp1_2.1c", 0xc000, 0x2000, CRC(a958a61c) SHA1(e5198703cdf47b2cd7fc9f2a5fde7bf4ab2275db))
ROM_LOAD("mp1_1.1b", 0xe000, 0x2000, CRC(77c0b492) SHA1(631b73560ac59c3612e692fa59558773639ceda7))

ROM_REGION(0x5000, REGION_GFX1, ROMREGION_DISPOSE)
ROM_LOAD("mp1_5.3b", 0x0000, 0x1000, CRC(16498b9f) SHA1(76610149c65f955484fef1c033ddc3fed3f4e568))
ROM_LOAD("mp1_6.3m", 0x1000, 0x2000, CRC(f2d9647a) SHA1(3cc216793c6a5f73c437ad2524563deb3b5e2890))
ROM_LOAD("mp1_7.3n", 0x3000, 0x2000, CRC(757cf2b6) SHA1(8dfbf03953d5219d9eb5fc654ec3392442ba1dc4))

ROM_REGION(0x10000, REGION_CPU2, 0)
ROM_LOAD("mp1_4.1k", 0xe000, 0x2000, CRC(8182dd5b) SHA1(f36b57f7f1e79f00b3f07afe1960bca5f5325ee2))

ROM_REGION(0x0220, REGION_PROMS, 0)
ROM_LOAD("mp1-5.5b", 0x0000, 0x0020, CRC(56531268) SHA1(2e356706c07f43eeb67783fb122bdc7fed1b3589))
ROM_LOAD("mp1-6.4c", 0x0020, 0x0100, CRC(50765082) SHA1(f578e14f15783acb2073644db4a2f0d196cc0957))
ROM_LOAD("mp1-7.5k", 0x0120, 0x0100, CRC(5396bd78) SHA1(2e387e5d8b8cab005f67f821b4db65d0ae8bd362))

ROM_REGION(0x0100, REGION_SOUND1, 0)
ROM_LOAD("mp1-3.3m", 0x0000, 0x0100, CRC(16a9166a) SHA1(847cbaf7c88616576c410177e066ae1d792ac0ba))
ROM_END

ROM_START(digdug2)
/* CPU1: 2 x 16k ROMs mapped at 8000-ffff */
ROM_REGION(0x10000, REGION_CPU1, 0)
ROM_LOAD("d23_3.1d", 0x8000, 0x4000, CRC(cc155338) SHA1(d6796479ebb00081e9ae281380a4ce75f730766e))
ROM_LOAD("d23_1.1b", 0xc000, 0x4000, CRC(40e46af8) SHA1(698a5c425e23627331d85216a4edee9c391e5749))

/* GFX: 4k chars + 2 x 16k sprite bitplanes */
ROM_REGION(0x9000, REGION_GFX1, ROMREGION_DISPOSE)
ROM_LOAD("d21_5.3b", 0x0000, 0x1000, CRC(afcb4509) SHA1(c9a54df22b0b92efbe7417a00200587225906b46))
ROM_LOAD("d21_6.3m", 0x1000, 0x4000, CRC(df1f4ad8) SHA1(004fba630018dbf03c4b0e284c98077e19fface3))
ROM_LOAD("d21_7.3n", 0x5000, 0x4000, CRC(ccadb3ea) SHA1(77d8d8e6039272f73e63c8f76084138ec613365a))

ROM_REGION(0x10000, REGION_CPU2, 0)
ROM_LOAD("d21_4.1k", 0xe000, 0x2000, CRC(737443b1) SHA1(0e46204089cc6e5ffab0d2a62f9a1728f8c35948))

ROM_REGION(0x0220, REGION_PROMS, 0)
ROM_LOAD("d21-5.5b", 0x0000, 0x0020, CRC(9b169db5) SHA1(77e840d10ab59708a051c3b15305b33d431ee06d))	/* palette */
ROM_LOAD("d21-6.4c", 0x0020, 0x0100, CRC(55a88695) SHA1(bd6bd641c9f220b6a2cc414a1117d5c089571400))	/* characters */
ROM_LOAD("d21-7.5k", 0x0120, 0x0100, CRC(9c55feda) SHA1(30a4593726f5a4791e0812fd593e592087e730e3))	/* sprites */

ROM_REGION(0x0100, REGION_SOUND1, 0)
ROM_LOAD("d21-3.3m", 0x0000, 0x0100, CRC(e0074ee2) SHA1(f4f02977130110be52f4dd82fc3c0d02f45778b9))
ROM_END

ROM_START(motos)
ROM_REGION(0x10000, REGION_CPU1, 0)
ROM_LOAD("mo1_3.1d", 0x8000, 0x4000, CRC(1104abb2) SHA1(ade809a73ac24494b9f95f65b7592df5f86dce60))
ROM_LOAD("mo1_1.1b", 0xc000, 0x4000, CRC(57b157e2) SHA1(b050495fcc4a4d93551b29d4f05e49f64017c870))

/* GFX: 4k chars + 2 x 16k sprite bitplanes */
ROM_REGION(0x9000, REGION_GFX1, ROMREGION_DISPOSE)
ROM_LOAD("mo1_5.3b", 0x0000, 0x1000, CRC(5d4a2a22) SHA1(4af9bf2ae9bb78d2d029ef38809181ffa3c0eb66))
ROM_LOAD("mo1_6.3m", 0x1000, 0x4000, CRC(2f0e396e) SHA1(664679f9d3d74a3fccb086af910392b4fe40c9bc))
ROM_LOAD("mo1_7.3n", 0x5000, 0x4000, CRC(cf8a3b86) SHA1(2b49cdec516e23783f2a291633d81ab8bd0245fc))

ROM_REGION(0x10000, REGION_CPU2, 0)
ROM_LOAD("mo1_4.1k", 0xe000, 0x2000, CRC(55e45d21) SHA1(a8b195acfec542734751de29c9dafc2b165a5881))

ROM_REGION(0x0220, REGION_PROMS, 0)
ROM_LOAD("mo1-5.5b", 0x0000, 0x0020, CRC(71972383) SHA1(66b0619affcc5168b099108800a941d6e2416ab0))	/* palette */
ROM_LOAD("mo1-6.4c", 0x0020, 0x0100, CRC(730ba7fb) SHA1(24eb167266752b064689662e3ef0f62d0407ac26))	/* characters */
ROM_LOAD("mo1-7.5k", 0x0120, 0x0100, CRC(7721275d) SHA1(543adb5348db81ea82a5c039451001ebd82735e3))	/* sprites */

ROM_REGION(0x0100, REGION_SOUND1, 0)
ROM_LOAD("mo1-3.3m", 0x0000, 0x0100, CRC(2accdfb4) SHA1(e21a0618c0f8e35ce26666b6850ac9c0d95d7971))
ROM_END

ROM_START(todruaga)
ROM_REGION(0x10000, REGION_CPU1, 0)
ROM_LOAD("td2_3.1d", 0x8000, 0x4000, CRC(fbf16299) SHA1(9abbaaaf0a53aff38df8287f62d091b13146cf13))
ROM_LOAD("td2_1.1b", 0xc000, 0x4000, CRC(b238d723) SHA1(ab8eadd45638ff1ab2dacbd5ab2c6870b9f79086))

/* GFX: 4k chars + 2 x 8k sprite bitplanes */
ROM_REGION(0x5000, REGION_GFX1, ROMREGION_DISPOSE)
ROM_LOAD("td1_5.3b", 0x0000, 0x1000, CRC(d32b249f) SHA1(7d7cee4101ef615fb92c3702f89a9823a6231195))
ROM_LOAD("td1_6.3m", 0x1000, 0x2000, CRC(e827e787) SHA1(74e0af4c7d6e334bcd211a33eb18dddc8a182aa7))
ROM_LOAD("td1_7.3n", 0x3000, 0x2000, CRC(962bd060) SHA1(74cdcafc26475bda085bf62ed17e6474ed782453))

ROM_REGION(0x10000, REGION_CPU2, 0)
ROM_LOAD("td1_4.1k", 0xe000, 0x2000, CRC(ae9d06d9) SHA1(3d8621fdd74fafa61f342886faa37f0aab50c5a7))

/* todruaga has a larger sprite color lookup (0x400 bytes vs 0x100) */
ROM_REGION(0x0520, REGION_PROMS, 0)
ROM_LOAD("td1-5.5b", 0x0000, 0x0020, CRC(122cc395) SHA1(a648c53f2e95634bb5b27d79be3fd908021d056e))	/* palette */
ROM_LOAD("td1-6.4c", 0x0020, 0x0100, CRC(8c661d6a) SHA1(1340e4f657f4f2c4ef651a441c3b51632e757d0b))	/* characters */
ROM_LOAD("td1-7.5k", 0x0120, 0x0400, CRC(a86c74dd) SHA1(dfd7d6b2740761c3bcab4c7999d2699d920843e7))	/* sprites */

ROM_REGION(0x0100, REGION_SOUND1, 0)
ROM_LOAD("td1-3.3m", 0x0000, 0x0100, CRC(07104c40) SHA1(16db55525034bacb71e7dc8bd2a7c3c4464d4808))
ROM_END


// ---------------------------------------------------------------------------
// Driver descriptors
// Screen dimensions: 28 tiles wide, 36 tiles tall (28*8=224, 36*8=288)
// Total colors: 32 palette + 64*4 char lookup + 16*16 sprite lookup = varies
//   mappy / mappy jp: 32 + 64*4 + 16*16 = 544   (color_table_len = 64*4+16*16)
//   digdug2 / motos : same (256 sprite colors), use digdug2_gfxdecodeinfo
//   todruaga        : 32 + 64*4 + 64*16 = 1312   (color_table_len = 64*4+64*16)
//
// Both CPUs run at 1.1 MHz for mappy, 1.6 MHz for the later titles.
// cpu_slices = 100 as in original MAME for tight dual-CPU synchronization.
// ---------------------------------------------------------------------------

/* ---- Mappy (US) ---- */
AAE_DRIVER_BEGIN(drv_mappy, "mappy", "Mappy (US)")
AAE_DRIVER_ROM(rom_mappy)
AAE_DRIVER_FUNCS(&init_mappy, &run_mappy, &end_mappy)
AAE_DRIVER_INPUT(input_ports_mappy)
AAE_DRIVER_SAMPLES_NONE()
AAE_DRIVER_ART_NONE()

AAE_DRIVER_CPUS(
    /* CPU0: main game CPU */
    AAE_CPU_ENTRY(
        /*type*/     CPU_M6809,
        /*freq*/     1100000,
        /*div*/      100,
        /*ipf*/      1,
        /*int type*/ INT_TYPE_INT,
        /*int cb*/   &mappy_interrupt_1,
        /*r8*/       mappy_readmem_cpu1,
        /*w8*/       mappy_writemem_cpu1,
        /*pr*/       nullptr,
        /*pw*/       nullptr,
        /*r16*/      nullptr,
        /*w16*/      nullptr
    ),
    /* CPU1: sound CPU */
    AAE_CPU_ENTRY(
        /*type*/     CPU_M6809,
        /*freq*/     1100000,
        /*div*/      100,
        /*ipf*/      1,
        /*int type*/ INT_TYPE_INT,
        /*int cb*/   &mappy_interrupt_2,
        /*r8*/       mappy_readmem_cpu2,
        /*w8*/       mappy_writemem_cpu2,
        /*pr*/       nullptr,
        /*pw*/       nullptr,
        /*r16*/      nullptr,
        /*w16*/      nullptr
    ),
    AAE_CPU_NONE_ENTRY(),
    AAE_CPU_NONE_ENTRY()
)

AAE_DRIVER_VIDEO_CORE(60, DEFAULT_60HZ_VBLANK_DURATION,
    VIDEO_TYPE_RASTER_COLOR | VIDEO_SUPPORTS_DIRTY, ORIENTATION_DEFAULT)
AAE_DRIVER_SCREEN(28 * 8, 36 * 8, 0, 28 * 8 - 1, 0, 36 * 8 - 1)
AAE_DRIVER_RASTER(mappy_gfxdecodeinfo, 32, 64 * 4 + 16 * 16, mappy_vh_convert_color_prom)
AAE_DRIVER_HISCORE_NONE()
AAE_DRIVER_VECTORRAM(0, 0)
AAE_DRIVER_NVRAM_NONE()
AAE_DRIVER_LAYOUT("default.lay", "Upright_Artwork")
AAE_DRIVER_END()

AAE_REGISTER_DRIVER(drv_mappy)


/* ---- Mappy (Japan) -- same hardware, different program ROMs ---- */
AAE_DRIVER_BEGIN(drv_mappyjp, "mappyjp", "Mappy (Japan)")
AAE_DRIVER_ROM(rom_mappyjp)
AAE_DRIVER_FUNCS(&init_mappy, &run_mappy, &end_mappy)
AAE_DRIVER_INPUT(input_ports_mappy)
AAE_DRIVER_SAMPLES_NONE()
AAE_DRIVER_ART_NONE()

AAE_DRIVER_CPUS(
    AAE_CPU_ENTRY(
        CPU_M6809, 1100000, 100, 1, INT_TYPE_INT, &mappy_interrupt_1,
        mappy_readmem_cpu1, mappy_writemem_cpu1, nullptr, nullptr, nullptr, nullptr
    ),
    AAE_CPU_ENTRY(
        CPU_M6809, 1100000, 100, 1, INT_TYPE_INT, &mappy_interrupt_2,
        mappy_readmem_cpu2, mappy_writemem_cpu2, nullptr, nullptr, nullptr, nullptr
    ),
    AAE_CPU_NONE_ENTRY(),
    AAE_CPU_NONE_ENTRY()
)

AAE_DRIVER_VIDEO_CORE(60, DEFAULT_60HZ_VBLANK_DURATION,
    VIDEO_TYPE_RASTER_COLOR | VIDEO_SUPPORTS_DIRTY, ORIENTATION_DEFAULT)
AAE_DRIVER_SCREEN(28 * 8, 36 * 8, 0, 28 * 8 - 1, 0, 36 * 8 - 1)
AAE_DRIVER_RASTER(mappy_gfxdecodeinfo, 32, 64 * 4 + 16 * 16, mappy_vh_convert_color_prom)
AAE_DRIVER_HISCORE_NONE()
AAE_DRIVER_VECTORRAM(0, 0)
AAE_DRIVER_NVRAM_NONE()
AAE_DRIVER_LAYOUT("default.lay", "Upright_Artwork")
AAE_DRIVER_END()

AAE_REGISTER_DRIVER(drv_mappyjp)


/* ---- Dig Dug 2 ---- */
AAE_DRIVER_BEGIN(drv_digdug2, "digdug2", "Dig Dug 2")
AAE_DRIVER_ROM(rom_digdug2)
AAE_DRIVER_FUNCS(&init_digdug2, &run_mappy, &end_digdug2)
AAE_DRIVER_INPUT(input_ports_digdug2)
AAE_DRIVER_SAMPLES_NONE()
AAE_DRIVER_ART_NONE()

AAE_DRIVER_CPUS(
    AAE_CPU_ENTRY(
        CPU_M6809, 1600000, 100, 1, INT_TYPE_INT, &mappy_interrupt_1,
        digdug2_readmem_cpu1, mappy_writemem_cpu1, nullptr, nullptr, nullptr, nullptr
    ),
    AAE_CPU_ENTRY(
        CPU_M6809, 1600000, 100, 1, INT_TYPE_INT, &mappy_interrupt_2,
        digdug2_readmem_cpu2, mappy_writemem_cpu2, nullptr, nullptr, nullptr, nullptr
    ),
    AAE_CPU_NONE_ENTRY(),
    AAE_CPU_NONE_ENTRY()
)

AAE_DRIVER_VIDEO_CORE(60, DEFAULT_60HZ_VBLANK_DURATION,
    VIDEO_TYPE_RASTER_COLOR | VIDEO_SUPPORTS_DIRTY, ORIENTATION_DEFAULT)
AAE_DRIVER_SCREEN(28 * 8, 36 * 8, 0, 28 * 8 - 1, 0, 36 * 8 - 1)
AAE_DRIVER_RASTER(digdug2_gfxdecodeinfo, 32, 64 * 4 + 16 * 16, mappy_vh_convert_color_prom)
AAE_DRIVER_HISCORE_NONE()
AAE_DRIVER_VECTORRAM(0, 0)
AAE_DRIVER_NVRAM_NONE()
AAE_DRIVER_LAYOUT("default.lay", "Upright_Artwork")
AAE_DRIVER_END()

AAE_REGISTER_DRIVER(drv_digdug2)


/* ---- Motos ---- */
AAE_DRIVER_BEGIN(drv_motos, "motos", "Motos")
AAE_DRIVER_ROM(rom_motos)
AAE_DRIVER_FUNCS(&init_motos, &run_motos, &end_motos)
AAE_DRIVER_INPUT(input_ports_motos)
AAE_DRIVER_SAMPLES_NONE()
AAE_DRIVER_ART_NONE()

AAE_DRIVER_CPUS(
    AAE_CPU_ENTRY(
        CPU_M6809, 1600000, 400, 1, INT_TYPE_INT, &mappy_interrupt_1,
        motos_readmem_cpu1, mappy_writemem_cpu1, nullptr, nullptr, nullptr, nullptr
    ),
    AAE_CPU_ENTRY(
        CPU_M6809, 1600000, 400, 1, INT_TYPE_INT, &mappy_interrupt_2,
        motos_readmem_cpu2, mappy_writemem_cpu2, nullptr, nullptr, nullptr, nullptr
    ),
    AAE_CPU_NONE_ENTRY(),
    AAE_CPU_NONE_ENTRY()
)

AAE_DRIVER_VIDEO_CORE(60, DEFAULT_60HZ_VBLANK_DURATION, VIDEO_TYPE_RASTER_COLOR | VIDEO_SUPPORTS_DIRTY, ORIENTATION_DEFAULT)
AAE_DRIVER_SCREEN(28 * 8, 36 * 8, 0, 28 * 8 - 1, 0, 36 * 8 - 1)
/* motos uses the digdug2 gfx decode (256 sprites) */
AAE_DRIVER_RASTER(digdug2_gfxdecodeinfo, 32, 64 * 4 + 16 * 16, mappy_vh_convert_color_prom)
AAE_DRIVER_HISCORE_NONE()
AAE_DRIVER_VECTORRAM(0, 0)
AAE_DRIVER_NVRAM_NONE()
AAE_DRIVER_LAYOUT("default.lay", "Upright_Artwork")
AAE_DRIVER_END()

AAE_REGISTER_DRIVER(drv_motos)


/* ---- Tower of Druaga ---- */
AAE_DRIVER_BEGIN(drv_todruaga, "todruaga", "Tower of Druaga")
AAE_DRIVER_ROM(rom_todruaga)
AAE_DRIVER_FUNCS(&init_todruaga, &run_mappy, &end_todruaga)
AAE_DRIVER_INPUT(input_ports_todruaga)
AAE_DRIVER_SAMPLES_NONE()
AAE_DRIVER_ART_NONE()

AAE_DRIVER_CPUS(
    AAE_CPU_ENTRY(
        CPU_M6809, 1600000, 100, 1, INT_TYPE_INT, &mappy_interrupt_1,
        todruaga_readmem_cpu1, mappy_writemem_cpu1, nullptr, nullptr, nullptr, nullptr
    ),
    AAE_CPU_ENTRY(
        CPU_M6809, 1600000, 100, 1, INT_TYPE_INT, &mappy_interrupt_2,
        todruaga_readmem_cpu2, mappy_writemem_cpu2, nullptr, nullptr, nullptr, nullptr
    ),
    AAE_CPU_NONE_ENTRY(),
    AAE_CPU_NONE_ENTRY()
)

AAE_DRIVER_VIDEO_CORE(60, DEFAULT_60HZ_VBLANK_DURATION,
    VIDEO_TYPE_RASTER_COLOR | VIDEO_SUPPORTS_DIRTY, ORIENTATION_DEFAULT)
AAE_DRIVER_SCREEN(28 * 8, 36 * 8, 0, 28 * 8 - 1, 0, 36 * 8 - 1)
/* todruaga has 64 sprite color sets instead of 16, hence the larger color table */
AAE_DRIVER_RASTER(todruaga_gfxdecodeinfo, 32, 64 * 4 + 64 * 16, mappy_vh_convert_color_prom)
AAE_DRIVER_HISCORE_NONE()
AAE_DRIVER_VECTORRAM(0, 0)
AAE_DRIVER_NVRAM_NONE()
AAE_DRIVER_LAYOUT("default.lay", "Upright_Artwork")
AAE_DRIVER_END()

AAE_REGISTER_DRIVER(drv_todruaga)
